/**
 * AUTO-GENERATED — do not edit manually.
 * Generated by: tools/stackblitz/generate-inline-projects.mjs
 * @ignore
 */
import { Component, ViewEncapsulation } from '@angular/core';
import { MatExpansionModule } from '@angular/material/expansion';
import { MatListModule } from '@angular/material/list';
import { RouterLink, RouterLinkActive } from '@angular/router';
import { NavigationDirective } from '../../directive/navigation.directive';

@Component({
  selector: 'sdux-stackblitz-examples-subnavigation',
  standalone: true,
  imports: [MatExpansionModule, RouterLink, RouterLinkActive, MatListModule],
  templateUrl: './stackblitz-examples.sub-navigation.component.html',
  encapsulation: ViewEncapsulation.None
})
export class StackBlitzExamplesSubNavigationComponent extends NavigationDirective {}
