/**
 * AUTO-GENERATED — do not edit manually.
 * Generated by: tools/sdux-comparison/sdux-comparison.mjs
 */
export const SVELTE_SDUX_OUTPUT = [
  {
    type: 'typescript',
    fileName: 'main.ts',
    source:
      "import { mount } from 'svelte';\nimport App from './App.svelte';\n\nmount(App, { target: document.getElementById('app')! });",
    numberedSource:
      "1 | import { mount } from 'svelte';\n2 | import App from './App.svelte';\n3 | \n4 | mount(App, { target: document.getElementById('app')! });"
  },
  {
    type: 'svelte',
    fileName: 'App.svelte',
    source:
      '<script lang="ts">\n  import ExampleView from \'./ExampleView.svelte\';\n</script>\n\n<ExampleView />',
    numberedSource:
      '1 | <script lang="ts">\n2 |   import ExampleView from \'./ExampleView.svelte\';\n3 | </script>\n4 | \n5 | <ExampleView />'
  },
  {
    type: 'typescript',
    fileName: 'employee.cell.ts',
    source:
      "import { FeatureCell, Vault } from '@sdux-vault/svelte';\nimport { Employee } from './employee.model';\n\nVault({\n  logLevel: 'off'\n});\n\nexport const employeeCell = FeatureCell<Employee[]>({\n  key: 'employees',\n  initialState: []\n});\n\nemployeeCell\n  .filters([\n    (examples: Employee[]) =>\n      examples.filter((example) => example.id % 2 !== 0)\n  ])\n  .reducers([\n    (examples: Employee[]) => {\n      examples.sort((left, right) => left.name.localeCompare(right.name));\n      return examples;\n    }\n  ])\n  .initialize();\n\nexport function replaceEmployees(employees: Employee[]): void {\n  employeeCell.replaceState({\n    loading: false,\n    value: employees,\n    error: null\n  });\n}\n\nexport function resetEmployees(): void {\n  employeeCell.reset();\n}",
    numberedSource:
      " 1 | import { FeatureCell, Vault } from '@sdux-vault/svelte';\n 2 | import { Employee } from './employee.model';\n 3 | \n 4 | Vault({\n 5 |   logLevel: 'off'\n 6 | });\n 7 | \n 8 | export const employeeCell = FeatureCell<Employee[]>({\n 9 |   key: 'employees',\n10 |   initialState: []\n11 | });\n12 | \n13 | employeeCell\n14 |   .filters([\n15 |     (examples: Employee[]) =>\n16 |       examples.filter((example) => example.id % 2 !== 0)\n17 |   ])\n18 |   .reducers([\n19 |     (examples: Employee[]) => {\n20 |       examples.sort((left, right) => left.name.localeCompare(right.name));\n21 |       return examples;\n22 |     }\n23 |   ])\n24 |   .initialize();\n25 | \n26 | export function replaceEmployees(employees: Employee[]): void {\n27 |   employeeCell.replaceState({\n28 |     loading: false,\n29 |     value: employees,\n30 |     error: null\n31 |   });\n32 | }\n33 | \n34 | export function resetEmployees(): void {\n35 |   employeeCell.reset();\n36 | }"
  },
  {
    type: 'svelte',
    fileName: 'ExampleView.svelte',
    source:
      "<script lang=\"ts\">\n  import type { Employee } from './employee.model';\n  import { employeeCell, replaceEmployees, resetEmployees } from './employee.cell';\n\n  const sample: Employee[] = [\n    { id: 11, name: 'Luke' },\n    { id: 38, name: 'Leia' },\n    { id: 9, name: 'Han' }\n  ];\n\n  let snapshot = $derived(employeeCell.state);\n\n  function loadSample(): void {\n    replaceEmployees(sample);\n  }\n\n  function resetState(): void {\n    resetEmployees();\n  }\n</script>\n\n<div>\n  <div>\n    {#if snapshot.isLoading}\n      <div>Loading...</div>\n    {:else if snapshot.error}\n      <div>{String(snapshot.error)}</div>\n    {:else}\n      <textarea readonly>{JSON.stringify(snapshot.value ?? [], null, 2)}</textarea>\n    {/if}\n  </div>\n\n  <div>\n    <button type=\"button\" on:click={loadSample}>Load Sample State</button>\n\n    <button type=\"button\" on:click={resetState}>Reset State</button>\n  </div>\n</div>",
    numberedSource:
      " 1 | <script lang=\"ts\">\n 2 |   import type { Employee } from './employee.model';\n 3 |   import { employeeCell, replaceEmployees, resetEmployees } from './employee.cell';\n 4 | \n 5 |   const sample: Employee[] = [\n 6 |     { id: 11, name: 'Luke' },\n 7 |     { id: 38, name: 'Leia' },\n 8 |     { id: 9, name: 'Han' }\n 9 |   ];\n10 | \n11 |   let snapshot = $derived(employeeCell.state);\n12 | \n13 |   function loadSample(): void {\n14 |     replaceEmployees(sample);\n15 |   }\n16 | \n17 |   function resetState(): void {\n18 |     resetEmployees();\n19 |   }\n20 | </script>\n21 | \n22 | <div>\n23 |   <div>\n24 |     {#if snapshot.isLoading}\n25 |       <div>Loading...</div>\n26 |     {:else if snapshot.error}\n27 |       <div>{String(snapshot.error)}</div>\n28 |     {:else}\n29 |       <textarea readonly>{JSON.stringify(snapshot.value ?? [], null, 2)}</textarea>\n30 |     {/if}\n31 |   </div>\n32 | \n33 |   <div>\n34 |     <button type=\"button\" on:click={loadSample}>Load Sample State</button>\n35 | \n36 |     <button type=\"button\" on:click={resetState}>Reset State</button>\n37 |   </div>\n38 | </div>"
  },
  {
    type: 'typescript',
    fileName: 'employee.model.ts',
    source: 'export interface Employee {\n  id: number;\n  name: string;\n}',
    numberedSource:
      '1 | export interface Employee {\n2 |   id: number;\n3 |   name: string;\n4 | }'
  }
] as const satisfies ReadonlyArray<{
  readonly type:
    'typescript' | 'html' | 'svelte' | 'vue' | 'scss' | 'json' | 'markdown';
  readonly fileName: string;
  readonly source: string;
  readonly numberedSource: string;
}>;
