import fs from 'node:fs';
import path from 'node:path';

/**
 * SitemapUrlMiner
 * ---------------
 * Extracts `routerLink` values from Angular navigation HTML templates
 * and merges them with a static supplement list to produce a complete
 * set of sitemap-eligible URL paths.
 *
 * Pages that are not reachable through the sidenav (e.g. `/`, `/about`,
 * `/contact`) are supplied via the static supplement list.
 */
export class SitemapUrlMiner {
  #navigationDir;
  #supplementUrls;

  /**
   * @param {{ navigationDir: string, supplementUrls: string[] }} options
   */
  constructor({ navigationDir, supplementUrls = [] }) {
    this.#navigationDir = navigationDir;
    this.#supplementUrls = supplementUrls;
  }

  /**
   * Recursively collects all `.html` files under the navigation directory.
   * @param {string} dir
   * @returns {string[]}
   */
  #collectHtmlFiles(dir) {
    const results = [];

    for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
      const fullPath = path.join(dir, entry.name);

      if (entry.isDirectory()) {
        results.push(...this.#collectHtmlFiles(fullPath));
      } else if (entry.name.endsWith('.html')) {
        results.push(fullPath);
      }
    }

    return results;
  }

  /**
   * Extracts all `routerLink` attribute values from an HTML string.
   * Matches both `routerLink="..."` and `[routerLink]="'...'"` patterns.
   * @param {string} html
   * @returns {string[]}
   */
  #extractRouterLinks(html) {
    const links = [];

    const staticPattern = /routerLink="([^"]+)"/g;
    let match;

    while ((match = staticPattern.exec(html)) !== null) {
      links.push(match[1]);
    }

    const boundPattern = /\[routerLink\]="'([^']+)'"/g;

    while ((match = boundPattern.exec(html)) !== null) {
      links.push(match[1]);
    }

    return links;
  }

  /**
   * Normalizes a route path to ensure it starts with `/`.
   * @param {string} route
   * @returns {string}
   */
  #normalize(route) {
    return route.startsWith('/') ? route : `/${route}`;
  }

  /**
   * Mines all navigation HTML files and returns a deduplicated,
   * sorted array of URL paths.
   * @returns {string[]}
   */
  mine() {
    const htmlFiles = this.#collectHtmlFiles(this.#navigationDir);
    const allLinks = new Set(this.#supplementUrls);

    for (const filePath of htmlFiles) {
      const html = fs.readFileSync(filePath, 'utf-8');
      const links = this.#extractRouterLinks(html);

      for (const link of links) {
        allLinks.add(this.#normalize(link));
      }
    }

    return [...allLinks].sort((a, b) => a.localeCompare(b));
  }

  /**
   * Mines URLs and writes the `sitemap-urls.mjs` module.
   * @param {string} outputPath — absolute path to the output file
   */
  write(outputPath) {
    const urls = this.mine();
    const urlEntries = urls.map((url) => `  '${url}'`).join(',\n');

    const content = [
      '/**',
      ' * Sitemap URL Registry',
      ' * --------------------',
      ' * AUTO-GENERATED — do not edit manually.',
      ` * Generated by: tools/sitemap/mine-sitemap-urls.mjs`,
      ` * Generated on: ${new Date().toISOString().split('T')[0]}`,
      ' *',
      ' * To regenerate, run: npm run sitemap:mine',
      ' */',
      `export const SITEMAP_URLS = [`,
      urlEntries,
      '];',
      ''
    ].join('\n');

    fs.writeFileSync(outputPath, content, 'utf-8');
    console.info(
      `Sitemap URL registry written to ${outputPath} (${urls.length} URLs)`
    );
  }
}
