/**
 * StackBlitz Project Imports Map
 * ------------------------------
 * AUTO-GENERATED — do not edit manually.
 * Generated by: tools/stackblitz/generate-inline-projects.mjs
 */
export const STACKBLITZ_PROJECT_IMPORTS: Record<
  string,
  () => Promise<unknown>
> = {
  'angular/basic-filter-reducer-example': () =>
    import('../../../stackblitz/projects/angular/basic-filter-reducer-example.project'),
  'angular/debugger-example': () =>
    import('../../../stackblitz/projects/angular/debugger-example.project'),
  'angular/http-resource-example': () =>
    import('../../../stackblitz/projects/angular/http-resource-example.project'),
  'angular/interceptor-delay-example': () =>
    import('../../../stackblitz/projects/angular/interceptor-delay-example.project'),
  'angular/observable-example': () =>
    import('../../../stackblitz/projects/angular/observable-example.project'),
  'angular/promise-example': () =>
    import('../../../stackblitz/projects/angular/promise-example.project'),
  'angular/replace-example': () =>
    import('../../../stackblitz/projects/angular/replace-example.project'),
  'angular/tab-sync-example': () =>
    import('../../../stackblitz/projects/angular/tab-sync-example.project'),
  'react/basic-filter-reducer-example': () =>
    import('../../../stackblitz/projects/react/basic-filter-reducer-example.project'),
  'react/debugger-example': () =>
    import('../../../stackblitz/projects/react/debugger-example.project'),
  'react/interceptor-delay-example': () =>
    import('../../../stackblitz/projects/react/interceptor-delay-example.project'),
  'react/observable-example': () =>
    import('../../../stackblitz/projects/react/observable-example.project'),
  'react/promise-example': () =>
    import('../../../stackblitz/projects/react/promise-example.project'),
  'react/replace-example': () =>
    import('../../../stackblitz/projects/react/replace-example.project'),
  'react/tab-sync-example': () =>
    import('../../../stackblitz/projects/react/tab-sync-example.project'),
  'svelte/basic-filter-reducer-example': () =>
    import('../../../stackblitz/projects/svelte/basic-filter-reducer-example.project'),
  'svelte/debugger-example': () =>
    import('../../../stackblitz/projects/svelte/debugger-example.project'),
  'svelte/interceptor-delay-example': () =>
    import('../../../stackblitz/projects/svelte/interceptor-delay-example.project'),
  'svelte/observable-example': () =>
    import('../../../stackblitz/projects/svelte/observable-example.project'),
  'svelte/promise-example': () =>
    import('../../../stackblitz/projects/svelte/promise-example.project'),
  'svelte/replace-example': () =>
    import('../../../stackblitz/projects/svelte/replace-example.project'),
  'svelte/tab-sync-example': () =>
    import('../../../stackblitz/projects/svelte/tab-sync-example.project'),
  'vue/basic-filter-reducer-example': () =>
    import('../../../stackblitz/projects/vue/basic-filter-reducer-example.project'),
  'vue/debugger-example': () =>
    import('../../../stackblitz/projects/vue/debugger-example.project'),
  'vue/interceptor-delay-example': () =>
    import('../../../stackblitz/projects/vue/interceptor-delay-example.project'),
  'vue/observable-example': () =>
    import('../../../stackblitz/projects/vue/observable-example.project'),
  'vue/promise-example': () =>
    import('../../../stackblitz/projects/vue/promise-example.project'),
  'vue/replace-example': () =>
    import('../../../stackblitz/projects/vue/replace-example.project'),
  'vue/tab-sync-example': () =>
    import('../../../stackblitz/projects/vue/tab-sync-example.project')
};
