/**
 * StackBlitz Project Imports Map
 * ------------------------------
 * AUTO-GENERATED — do not edit manually.
 * Generated by: tools/stackblitz/generate-inline-projects.mjs
 */
export const STACKBLITZ_PROJECT_IMPORTS: Record<
  string,
  () => Promise<unknown>
> = {
  'angular/array-append-merge-example': () =>
    import('../../../stackblitz/projects/angular/array-append-merge-example.project'),
  'angular/basic-filter-reducer-example': () =>
    import('../../../stackblitz/projects/angular/basic-filter-reducer-example.project'),
  'angular/comparison-example': () =>
    import('../../../stackblitz/projects/angular/comparison-example.project'),
  'angular/debugger-example': () =>
    import('../../../stackblitz/projects/angular/debugger-example.project'),
  'angular/display-character-example': () =>
    import('../../../stackblitz/projects/angular/display-character-example.project'),
  'angular/display-characters-example': () =>
    import('../../../stackblitz/projects/angular/display-characters-example.project'),
  'angular/http-resource-example': () =>
    import('../../../stackblitz/projects/angular/http-resource-example.project'),
  'angular/hydrate-state-example': () =>
    import('../../../stackblitz/projects/angular/hydrate-state-example.project'),
  'angular/initial-state-example': () =>
    import('../../../stackblitz/projects/angular/initial-state-example.project'),
  'angular/interceptor-delay-example': () =>
    import('../../../stackblitz/projects/angular/interceptor-delay-example.project'),
  'angular/observable-example': () =>
    import('../../../stackblitz/projects/angular/observable-example.project'),
  'angular/promise-example': () =>
    import('../../../stackblitz/projects/angular/promise-example.project'),
  'angular/replace-example': () =>
    import('../../../stackblitz/projects/angular/replace-example.project'),
  'angular/tab-sync-example': () =>
    import('../../../stackblitz/projects/angular/tab-sync-example.project'),
  'bun/http-resource-example': () =>
    import('../../../stackblitz/projects/bun/http-resource-example.project'),
  'bun/promise-example': () =>
    import('../../../stackblitz/projects/bun/promise-example.project'),
  'bun/replace-example': () =>
    import('../../../stackblitz/projects/bun/replace-example.project'),
  'deno/array-append-example': () =>
    import('../../../stackblitz/projects/deno/array-append-example.project'),
  'deno/promise-example': () =>
    import('../../../stackblitz/projects/deno/promise-example.project'),
  'deno/replace-example': () =>
    import('../../../stackblitz/projects/deno/replace-example.project'),
  'nodejs/array-append-example': () =>
    import('../../../stackblitz/projects/nodejs/array-append-example.project'),
  'nodejs/promise-example': () =>
    import('../../../stackblitz/projects/nodejs/promise-example.project'),
  'nodejs/replace-example': () =>
    import('../../../stackblitz/projects/nodejs/replace-example.project'),
  'react/array-append-merge-example': () =>
    import('../../../stackblitz/projects/react/array-append-merge-example.project'),
  'react/basic-filter-reducer-example': () =>
    import('../../../stackblitz/projects/react/basic-filter-reducer-example.project'),
  'react/comparison-example': () =>
    import('../../../stackblitz/projects/react/comparison-example.project'),
  'react/debugger-example': () =>
    import('../../../stackblitz/projects/react/debugger-example.project'),
  'react/hydrate-state-example': () =>
    import('../../../stackblitz/projects/react/hydrate-state-example.project'),
  'react/initial-state-example': () =>
    import('../../../stackblitz/projects/react/initial-state-example.project'),
  'react/interceptor-delay-example': () =>
    import('../../../stackblitz/projects/react/interceptor-delay-example.project'),
  'react/observable-example': () =>
    import('../../../stackblitz/projects/react/observable-example.project'),
  'react/promise-example': () =>
    import('../../../stackblitz/projects/react/promise-example.project'),
  'react/replace-example': () =>
    import('../../../stackblitz/projects/react/replace-example.project'),
  'react/tab-sync-example': () =>
    import('../../../stackblitz/projects/react/tab-sync-example.project'),
  'svelte/array-append-merge-example': () =>
    import('../../../stackblitz/projects/svelte/array-append-merge-example.project'),
  'svelte/basic-filter-reducer-example': () =>
    import('../../../stackblitz/projects/svelte/basic-filter-reducer-example.project'),
  'svelte/comparison-example': () =>
    import('../../../stackblitz/projects/svelte/comparison-example.project'),
  'svelte/debugger-example': () =>
    import('../../../stackblitz/projects/svelte/debugger-example.project'),
  'svelte/hydrate-state-example': () =>
    import('../../../stackblitz/projects/svelte/hydrate-state-example.project'),
  'svelte/initial-state-example': () =>
    import('../../../stackblitz/projects/svelte/initial-state-example.project'),
  'svelte/interceptor-delay-example': () =>
    import('../../../stackblitz/projects/svelte/interceptor-delay-example.project'),
  'svelte/observable-example': () =>
    import('../../../stackblitz/projects/svelte/observable-example.project'),
  'svelte/promise-example': () =>
    import('../../../stackblitz/projects/svelte/promise-example.project'),
  'svelte/replace-example': () =>
    import('../../../stackblitz/projects/svelte/replace-example.project'),
  'svelte/tab-sync-example': () =>
    import('../../../stackblitz/projects/svelte/tab-sync-example.project'),
  'vanillajs/array-append-example': () =>
    import('../../../stackblitz/projects/vanillajs/array-append-example.project'),
  'vanillajs/promise-example': () =>
    import('../../../stackblitz/projects/vanillajs/promise-example.project'),
  'vanillajs/replace-example': () =>
    import('../../../stackblitz/projects/vanillajs/replace-example.project'),
  'vue/array-append-merge-example': () =>
    import('../../../stackblitz/projects/vue/array-append-merge-example.project'),
  'vue/basic-filter-reducer-example': () =>
    import('../../../stackblitz/projects/vue/basic-filter-reducer-example.project'),
  'vue/comparison-example': () =>
    import('../../../stackblitz/projects/vue/comparison-example.project'),
  'vue/debugger-example': () =>
    import('../../../stackblitz/projects/vue/debugger-example.project'),
  'vue/hydrate-state-example': () =>
    import('../../../stackblitz/projects/vue/hydrate-state-example.project'),
  'vue/initial-state-example': () =>
    import('../../../stackblitz/projects/vue/initial-state-example.project'),
  'vue/interceptor-delay-example': () =>
    import('../../../stackblitz/projects/vue/interceptor-delay-example.project'),
  'vue/observable-example': () =>
    import('../../../stackblitz/projects/vue/observable-example.project'),
  'vue/promise-example': () =>
    import('../../../stackblitz/projects/vue/promise-example.project'),
  'vue/replace-example': () =>
    import('../../../stackblitz/projects/vue/replace-example.project'),
  'vue/tab-sync-example': () =>
    import('../../../stackblitz/projects/vue/tab-sync-example.project'),
  'typescript/array-append-example': () =>
    import('../../../stackblitz/projects/nodejs/array-append-example.project'),
  'typescript/promise-example': () =>
    import('../../../stackblitz/projects/nodejs/promise-example.project'),
  'typescript/replace-example': () =>
    import('../../../stackblitz/projects/nodejs/replace-example.project')
};
