/**
 * AUTO-GENERATED — do not edit manually.
 * Generated by: tools/sdux-comparison/sdux-comparison.mjs
 */
export const ANGULAR_SDUX_OUTPUT = [
  {
    type: 'typescript',
    fileName: 'main.ts',
    source:
      "import { bootstrapApplication } from '@angular/platform-browser';\nimport { appConfig } from './app.config';\nimport { ExampleComponent } from './example.component';\n\nbootstrapApplication(ExampleComponent, appConfig).catch((error: unknown) => {\n  console.error(error);\n});",
    numberedSource:
      "1 | import { bootstrapApplication } from '@angular/platform-browser';\n2 | import { appConfig } from './app.config';\n3 | import { ExampleComponent } from './example.component';\n4 | \n5 | bootstrapApplication(ExampleComponent, appConfig).catch((error: unknown) => {\n6 |   console.error(error);\n7 | });"
  },
  {
    type: 'typescript',
    fileName: 'app.config.ts',
    source:
      "import { ApplicationConfig } from '@angular/core';\nimport { provideFeatureCell, provideVault } from '@sdux-vault/angular';\nimport { EmployeeCell } from './employee.service';\n\nexport const appConfig: ApplicationConfig = {\n  providers: [\n    provideVault({ logLevel: 'off' }),\n    provideFeatureCell(EmployeeCell, {\n      key: 'employees',\n      initialState: []\n    })\n  ]\n};",
    numberedSource:
      " 1 | import { ApplicationConfig } from '@angular/core';\n 2 | import { provideFeatureCell, provideVault } from '@sdux-vault/angular';\n 3 | import { EmployeeCell } from './employee.service';\n 4 | \n 5 | export const appConfig: ApplicationConfig = {\n 6 |   providers: [\n 7 |     provideVault({ logLevel: 'off' }),\n 8 |     provideFeatureCell(EmployeeCell, {\n 9 |       key: 'employees',\n10 |       initialState: []\n11 |     })\n12 |   ]\n13 | };"
  },
  {
    type: 'typescript',
    fileName: 'employee.service.ts',
    source:
      "import { Injectable } from '@angular/core';\nimport { FeatureCell, injectVault } from '@sdux-vault/angular';\nimport { Employee } from './employee.model';\n\n@FeatureCell<Employee[]>('employees')\n@Injectable({ providedIn: 'root' })\nexport class EmployeeCell {\n  readonly #vault = injectVault<Employee[]>(EmployeeCell);\n  readonly state = this.#vault.state;\n\n  constructor() {\n    this.#vault.\n    .filters([\n      (examples: Example[]) =>\n        examples.filter((example) => example.id % 2 !== 0)\n    ])\n    .reducers([\n      (examples: Example[]) => {\n        examples.sort((left, right) => left.name.localeCompare(right.name));\n        return examples;\n      }\n    ])\n    .initialize();\n  }\n\n  replace(employees: Employee[]): void {\n    this.#vault.replaceState({\n      loading: false,\n      value: employees,\n      error: null\n    });\n  }\n\n  reset(): void {\n    this.#vault.reset();\n  }\n}",
    numberedSource:
      " 1 | import { Injectable } from '@angular/core';\n 2 | import { FeatureCell, injectVault } from '@sdux-vault/angular';\n 3 | import { Employee } from './employee.model';\n 4 | \n 5 | @FeatureCell<Employee[]>('employees')\n 6 | @Injectable({ providedIn: 'root' })\n 7 | export class EmployeeCell {\n 8 |   readonly #vault = injectVault<Employee[]>(EmployeeCell);\n 9 |   readonly state = this.#vault.state;\n10 | \n11 |   constructor() {\n12 |     this.#vault.\n13 |     .filters([\n14 |       (examples: Example[]) =>\n15 |         examples.filter((example) => example.id % 2 !== 0)\n16 |     ])\n17 |     .reducers([\n18 |       (examples: Example[]) => {\n19 |         examples.sort((left, right) => left.name.localeCompare(right.name));\n20 |         return examples;\n21 |       }\n22 |     ])\n23 |     .initialize();\n24 |   }\n25 | \n26 |   replace(employees: Employee[]): void {\n27 |     this.#vault.replaceState({\n28 |       loading: false,\n29 |       value: employees,\n30 |       error: null\n31 |     });\n32 |   }\n33 | \n34 |   reset(): void {\n35 |     this.#vault.reset();\n36 |   }\n37 | }"
  },
  {
    type: 'typescript',
    fileName: 'example.component.ts',
    source:
      "import { CommonModule } from '@angular/common';\nimport { Component, inject } from '@angular/core';\nimport { EmployeeCell } from './employee.service';\n\n@Component({\n  selector: 'example-view',\n  standalone: true,\n  imports: [CommonModule],\n  templateUrl: './example.component.html'\n})\nexport class ExampleComponent {\n  #employeeCell = inject(EmployeeCell);\n\n  readonly state = this.#employeeCell.state;\n\n  readonly sample = [\n    { id: 11, name: 'Luke' },\n    { id: 38, name: 'Leia' },\n    { id: 9, name: 'Han' }\n  ];\n\n  loadSample(): void {\n    this.#employeeCell.replace(this.sample);\n  }\n\n  resetState(): void {\n    this.#employeeCell.reset();\n  }\n}",
    numberedSource:
      " 1 | import { CommonModule } from '@angular/common';\n 2 | import { Component, inject } from '@angular/core';\n 3 | import { EmployeeCell } from './employee.service';\n 4 | \n 5 | @Component({\n 6 |   selector: 'example-view',\n 7 |   standalone: true,\n 8 |   imports: [CommonModule],\n 9 |   templateUrl: './example.component.html'\n10 | })\n11 | export class ExampleComponent {\n12 |   #employeeCell = inject(EmployeeCell);\n13 | \n14 |   readonly state = this.#employeeCell.state;\n15 | \n16 |   readonly sample = [\n17 |     { id: 11, name: 'Luke' },\n18 |     { id: 38, name: 'Leia' },\n19 |     { id: 9, name: 'Han' }\n20 |   ];\n21 | \n22 |   loadSample(): void {\n23 |     this.#employeeCell.replace(this.sample);\n24 |   }\n25 | \n26 |   resetState(): void {\n27 |     this.#employeeCell.reset();\n28 |   }\n29 | }"
  },
  {
    type: 'html',
    fileName: 'example.component.html',
    source:
      '<div>\n  <div>\n    @if (state.isLoading()) {\n      <div>Loading...</div>\n    } @else if (state.error()) {\n      <div>{{ state.error() }}</div>\n    } @else {\n      <textarea readonly>{{ state.value() | json }}</textarea>\n    }\n  </div>\n\n  <div>\n    <button type="button" (click)="loadSample()">\n      Load Sample State\n    </button>\n\n    <button type="button" (click)="resetState()">\n      Reset State\n    </button>\n  </div>\n</div>',
    numberedSource:
      ' 1 | <div>\n 2 |   <div>\n 3 |     @if (state.isLoading()) {\n 4 |       <div>Loading...</div>\n 5 |     } @else if (state.error()) {\n 6 |       <div>{{ state.error() }}</div>\n 7 |     } @else {\n 8 |       <textarea readonly>{{ state.value() | json }}</textarea>\n 9 |     }\n10 |   </div>\n11 | \n12 |   <div>\n13 |     <button type="button" (click)="loadSample()">\n14 |       Load Sample State\n15 |     </button>\n16 | \n17 |     <button type="button" (click)="resetState()">\n18 |       Reset State\n19 |     </button>\n20 |   </div>\n21 | </div>'
  },
  {
    type: 'typescript',
    fileName: 'employee.model.ts',
    source: 'export interface Employee {\n  id: number;\n  name: string;\n}',
    numberedSource:
      '1 | export interface Employee {\n2 |   id: number;\n3 |   name: string;\n4 | }'
  }
] as const satisfies ReadonlyArray<{
  readonly type: 'typescript' | 'html' | 'scss' | 'json' | 'markdown';
  readonly fileName: string;
  readonly source: string;
  readonly numberedSource: string;
}>;
