services:
  apache:
    build:
      context: ./docker/docker-development/apache
      dockerfile: Dockerfile.apache
    image: php:8.2-apache
    container_name: sdux_apache
    depends_on:
      - sdux_node
    ports:
      - '8080:80'
    volumes:
      - ./docker/docker-development/apache/httpd.conf:/etc/apache2/sites-available/000-default.conf
      - ./logs/httpd:/usr/local/apache2/logs/httpd
    networks:
      - sdux_net

  sdux_node:
    build:
      context: .
      dockerfile: ./docker/docker-development/node/Dockerfile.node
      args:
        HOST_IP: ${HOST_IP:-host-gateway}
    container_name: sdux_node
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
      - ./logs:/usr/src/app/logs
    ports:
      - '4200:4200'
    networks:
      - sdux_net
    command: ['npm', 'run', 'start', '--', '--host', '0.0.0.0']
    environment:
      - NODE_ENV=development

networks:
  sdux_net:
    driver: bridge
