/**
 * AUTO-GENERATED — do not edit manually.
 * Generated by: tools/sdux-comparison/sdux-comparison.mjs
 */
export const VUE_PINIA_OUTPUT = [
  {
    type: 'typescript',
    fileName: 'main.ts',
    source:
      "import { createPinia } from 'pinia';\nimport { createApp } from 'vue';\nimport App from './App.vue';\n\ncreateApp(App).use(createPinia()).mount('#app');",
    numberedSource:
      "1 | import { createPinia } from 'pinia';\n2 | import { createApp } from 'vue';\n3 | import App from './App.vue';\n4 | \n5 | createApp(App).use(createPinia()).mount('#app');"
  },
  {
    type: 'vue',
    fileName: 'App.vue',
    source:
      '<script setup lang="ts">\nimport ExampleView from \'./ExampleView.vue\';\n</script>\n\n<template>\n  <ExampleView />\n</template>',
    numberedSource:
      '1 | <script setup lang="ts">\n2 | import ExampleView from \'./ExampleView.vue\';\n3 | </script>\n4 | \n5 | <template>\n6 |   <ExampleView />\n7 | </template>'
  },
  {
    type: 'typescript',
    fileName: 'employee.store.ts',
    source:
      "import { defineStore } from 'pinia';\nimport { Employee } from './employee.model';\n\nconst filterOddEmployees = (employees: Employee[]): Employee[] => {\n  return employees.filter((employee) => employee.id % 2 !== 0);\n};\n\nconst sortEmployeesByName = (employees: Employee[]): Employee[] => {\n  const sortedEmployees = [...employees];\n\n  sortedEmployees.sort((left, right) => left.name.localeCompare(right.name));\n\n  return sortedEmployees;\n};\n\nconst prepareEmployees = (employees: Employee[]): Employee[] => {\n  return sortEmployeesByName(filterOddEmployees(employees));\n};\n\nexport const useEmployeeStore = defineStore('employees', {\n  state: () => ({\n    loading: false,\n    value: [] as Employee[],\n    error: null as string | null\n  }),\n  actions: {\n    replace(employees: Employee[]): void {\n      this.loading = false;\n      this.value = prepareEmployees(employees);\n      this.error = null;\n    },\n\n    reset(): void {\n      this.loading = false;\n      this.value = [];\n      this.error = null;\n    }\n  }\n});",
    numberedSource:
      " 1 | import { defineStore } from 'pinia';\n 2 | import { Employee } from './employee.model';\n 3 | \n 4 | const filterOddEmployees = (employees: Employee[]): Employee[] => {\n 5 |   return employees.filter((employee) => employee.id % 2 !== 0);\n 6 | };\n 7 | \n 8 | const sortEmployeesByName = (employees: Employee[]): Employee[] => {\n 9 |   const sortedEmployees = [...employees];\n10 | \n11 |   sortedEmployees.sort((left, right) => left.name.localeCompare(right.name));\n12 | \n13 |   return sortedEmployees;\n14 | };\n15 | \n16 | const prepareEmployees = (employees: Employee[]): Employee[] => {\n17 |   return sortEmployeesByName(filterOddEmployees(employees));\n18 | };\n19 | \n20 | export const useEmployeeStore = defineStore('employees', {\n21 |   state: () => ({\n22 |     loading: false,\n23 |     value: [] as Employee[],\n24 |     error: null as string | null\n25 |   }),\n26 |   actions: {\n27 |     replace(employees: Employee[]): void {\n28 |       this.loading = false;\n29 |       this.value = prepareEmployees(employees);\n30 |       this.error = null;\n31 |     },\n32 | \n33 |     reset(): void {\n34 |       this.loading = false;\n35 |       this.value = [];\n36 |       this.error = null;\n37 |     }\n38 |   }\n39 | });"
  },
  {
    type: 'vue',
    fileName: 'ExampleView.vue',
    source:
      '<script setup lang="ts">\nimport { storeToRefs } from \'pinia\';\nimport { Employee } from \'./employee.model\';\nimport { useEmployeeStore } from \'./employee.store\';\n\nconst sample: Employee[] = [\n  { id: 11, name: \'Luke\' },\n  { id: 38, name: \'Leia\' },\n  { id: 9, name: \'Han\' }\n];\n\nconst employeeStore = useEmployeeStore();\nconst { error, loading, value } = storeToRefs(employeeStore);\n\nfunction loadSample(): void {\n  employeeStore.replace(sample);\n}\n\nfunction resetState(): void {\n  employeeStore.reset();\n}\n</script>\n\n<template>\n  <div>\n    <div>\n      <div v-if="loading">Loading...</div>\n      <div v-else-if="error">{{ error }}</div>\n      <textarea v-else readonly :value="JSON.stringify(value, null, 2)" />\n    </div>\n\n    <div>\n      <button type="button" @click="loadSample">Load Sample State</button>\n\n      <button type="button" @click="resetState">Reset State</button>\n    </div>\n  </div>\n</template>',
    numberedSource:
      ' 1 | <script setup lang="ts">\n 2 | import { storeToRefs } from \'pinia\';\n 3 | import { Employee } from \'./employee.model\';\n 4 | import { useEmployeeStore } from \'./employee.store\';\n 5 | \n 6 | const sample: Employee[] = [\n 7 |   { id: 11, name: \'Luke\' },\n 8 |   { id: 38, name: \'Leia\' },\n 9 |   { id: 9, name: \'Han\' }\n10 | ];\n11 | \n12 | const employeeStore = useEmployeeStore();\n13 | const { error, loading, value } = storeToRefs(employeeStore);\n14 | \n15 | function loadSample(): void {\n16 |   employeeStore.replace(sample);\n17 | }\n18 | \n19 | function resetState(): void {\n20 |   employeeStore.reset();\n21 | }\n22 | </script>\n23 | \n24 | <template>\n25 |   <div>\n26 |     <div>\n27 |       <div v-if="loading">Loading...</div>\n28 |       <div v-else-if="error">{{ error }}</div>\n29 |       <textarea v-else readonly :value="JSON.stringify(value, null, 2)" />\n30 |     </div>\n31 | \n32 |     <div>\n33 |       <button type="button" @click="loadSample">Load Sample State</button>\n34 | \n35 |       <button type="button" @click="resetState">Reset State</button>\n36 |     </div>\n37 |   </div>\n38 | </template>'
  },
  {
    type: 'typescript',
    fileName: 'employee.model.ts',
    source: 'export interface Employee {\n  id: number;\n  name: string;\n}',
    numberedSource:
      '1 | export interface Employee {\n2 |   id: number;\n3 |   name: string;\n4 | }'
  }
] as const satisfies ReadonlyArray<{
  readonly type:
    'typescript' | 'html' | 'svelte' | 'vue' | 'scss' | 'json' | 'markdown';
  readonly fileName: string;
  readonly source: string;
  readonly numberedSource: string;
}>;
