#!/usr/bin/env node

// --- AI Model File Path (DO NOT DELETE) ---
// FilePath: libs > testing > integration > integration-build.script.mjs
// Updated: 2026-04-09 19:09
//	 Generated by pathcomment [tab] (see .vscode/typescript.code-snippets) or
//	 cmd+alt+j (see .vscode/keybindings.json)
// --- END AI MODEL FILE PATH ---

import { execSync } from 'child_process';
import fs from 'fs';
import path from 'path';

// ---------------------------------------------
// 🧠 Resolve paths
// ---------------------------------------------
const ROOT = process.cwd();
const DIST = path.join(ROOT, 'dist');
const INTEGRATION = path.join(ROOT, '.integration');
const NM = path.join(INTEGRATION, 'node_modules');
const SCOPE = path.join(NM, '@sdux-vault');

// ---------------------------------------------
// 🛠️ Helpers
// ---------------------------------------------
const log = (msg) => console.info(`\n\x1b[36m▶ ${msg}\x1b[0m`);
const success = (msg) => console.info(`\x1b[32m✔ ${msg}\x1b[0m`);
const error = (msg) => console.error(`\x1b[31m✖ ${msg}\x1b[0m`);

const run = (cmd, options = {}) => {
  log(cmd);
  try {
    execSync(cmd, {
      stdio: 'inherit',
      cwd: ROOT,
      env: {
        ...process.env,
        NODE_ENV: 'test'
      },
      ...options
    });
  } catch (err) {
    error(`Command failed: ${cmd}`);
    process.exit(1);
  }
};

const ensureDir = (dir) => {
  fs.mkdirSync(dir, { recursive: true });
};

const removeDir = (dir) => {
  fs.rmSync(dir, { recursive: true, force: true });
};

const copyDir = (src, dest) => {
  if (!fs.existsSync(src)) {
    error(`Missing build output: ${src}`);
    process.exit(1);
  }

  fs.cpSync(src, dest, { recursive: true });
};

// ---------------------------------------------
// 📦 Config (order matters)
// ---------------------------------------------
const LIB_BUILD_ORDER = [
  //'shared',
  //'devtools/tooling',
  'core',
  'addons',
  'angular',
  'testing-utils'
];

const LIB_CONFIG = {
  /*
  shared: {
    dist: 'shared',
    pkg: 'shared'
  },
  */
  core: {
    dist: 'core',
    pkg: 'core'
  },
  addons: {
    dist: 'addons',
    pkg: 'addons'
  },
  angular: {
    dist: 'core-extensions/angular',
    pkg: 'angular'
  },
  'testing-utils': {
    dist: 'testing/utils',
    pkg: 'testing-utils'
  }
};

// ---------------------------------------------
// 🧹 Step 1: Clean
// ---------------------------------------------
const clean = () => {
  log('Cleaning previous artifacts');

  removeDir(INTEGRATION);

  success('Clean complete');
};

// ---------------------------------------------
// 🔨 Step 2: Build all libs
// ---------------------------------------------
const buildLibs = () => {
  log('Building libraries in dependency order');

  for (const lib of LIB_BUILD_ORDER) {
    run(`ng build ${lib}`);
  }

  success('All libraries built');
};

// ---------------------------------------------
// 📁 Step 3: Setup integration sandbox
// ---------------------------------------------
const setupIntegrationDir = () => {
  log('Setting up integration sandbox');

  ensureDir(SCOPE);

  success('Integration directory ready');
};

// ---------------------------------------------
// 📦 Step 4: Copy built libs into sandbox
// ---------------------------------------------
const copyLibraries = () => {
  log('Copying built libraries into sandbox');

  for (const lib of LIB_BUILD_ORDER) {
    const config = LIB_CONFIG[lib];

    const src = path.join(DIST, config.dist);
    const dest = path.join(SCOPE, config.pkg);

    copyDir(src, dest);

    success(`Copied ${config.pkg}`);
  }
};

// ---------------------------------------------
// 🌐 Step 5: Install real engine + deps
// ---------------------------------------------
const installEngine = () => {
  log('Installing engine + dependencies');

  // Create minimal package.json for sandbox
  const pkgJson = {
    name: 'integration-sandbox',
    private: true,
    dependencies: {
      '@sdux-vault/engine': 'latest',
      rxjs: '^7.8.0',
      tslib: '^2.6.0'
    }
  };

  fs.writeFileSync(
    path.join(INTEGRATION, 'package.json'),
    JSON.stringify(pkgJson, null, 2)
  );

  run(`npm install --legacy-peer-deps`, { cwd: INTEGRATION });

  success('Engine installed');
};

// ---------------------------------------------
// 🚀 Main
// ---------------------------------------------
const main = () => {
  console.info('\n========================================');
  console.info('🚀 SDUX Integration Test Runner');
  console.info('========================================\n');

  clean();
  buildLibs();
  setupIntegrationDir();
  installEngine();
  copyLibraries();

  console.info('\n========================================');
  console.info('✅ DONE');
  console.info('========================================\n');
};

main();
