/**
 * AUTO-GENERATED — do not edit manually.
 * Generated by: tools/sdux-comparison/sdux-comparison.mjs
 */
export const REACT_REDUX_V2_OUTPUT_METADATA = {
  competitorTotalLines: 138,
  sduxTotalLines: 110,
  lineDifference: 28,
  percentageSavings: 20.29
} as const;

export const REACT_REDUX_V2_OUTPUT = [
  {
    type: 'typescript',
    fileName: 'main.tsx',
    source:
      "import { StrictMode } from 'react';\nimport { createRoot } from 'react-dom/client';\nimport { Provider } from 'react-redux';\nimport { ExampleView } from './ExampleView';\nimport { store } from './store';\n\ncreateRoot(document.getElementById('root')!).render(\n  <StrictMode>\n    <Provider store={store}>\n      <ExampleView />\n    </Provider>\n  </StrictMode>\n);\n",
    numberedSource:
      " 1 | import { StrictMode } from 'react';\n 2 | import { createRoot } from 'react-dom/client';\n 3 | import { Provider } from 'react-redux';\n 4 | import { ExampleView } from './ExampleView';\n 5 | import { store } from './store';\n 6 | \n 7 | createRoot(document.getElementById('root')!).render(\n 8 |   <StrictMode>\n 9 |     <Provider store={store}>\n10 |       <ExampleView />\n11 |     </Provider>\n12 |   </StrictMode>\n13 | );\n14 | "
  },
  {
    type: 'typescript',
    fileName: 'store.ts',
    source:
      "import { configureStore } from '@reduxjs/toolkit';\nimport { setupListeners } from '@reduxjs/toolkit/query';\nimport { employeeApi } from './employee.api';\n\nexport const store = configureStore({\n  reducer: {\n    [employeeApi.reducerPath]: employeeApi.reducer\n  },\n  middleware: (getDefaultMiddleware) =>\n    getDefaultMiddleware().concat(employeeApi.middleware)\n});\n\nsetupListeners(store.dispatch);\n\nexport type AppDispatch = typeof store.dispatch;\n",
    numberedSource:
      " 1 | import { configureStore } from '@reduxjs/toolkit';\n 2 | import { setupListeners } from '@reduxjs/toolkit/query';\n 3 | import { employeeApi } from './employee.api';\n 4 | \n 5 | export const store = configureStore({\n 6 |   reducer: {\n 7 |     [employeeApi.reducerPath]: employeeApi.reducer\n 8 |   },\n 9 |   middleware: (getDefaultMiddleware) =>\n10 |     getDefaultMiddleware().concat(employeeApi.middleware)\n11 | });\n12 | \n13 | setupListeners(store.dispatch);\n14 | \n15 | export type AppDispatch = typeof store.dispatch;\n16 | "
  },
  {
    type: 'typescript',
    fileName: 'ExampleView.tsx',
    source:
      "import {\n  replaceEmployees,\n  replaceEmployeesAsync,\n  resetEmployees\n} from './employee.actions';\nimport { useGetEmployeesState } from './employee.api';\nimport type { Employee } from './employee.model';\n\nconst sample: Employee[] = [\n  { id: 11, name: 'Luke' },\n  { id: 38, name: 'Leia' },\n  { id: 9, name: 'Han' }\n];\n\nexport function ExampleView() {\n  const {\n    data = [],\n    error,\n    isFetching,\n    isLoading\n  } = useGetEmployeesState();\n\n  return (\n    <div>\n      <div>\n        {isLoading ? (\n          <div>Loading...</div>\n        ) : error ? (\n          <div>{String(error)}</div>\n        ) : (\n          <textarea readOnly value={JSON.stringify(data, null, 2)} />\n        )}\n      </div>\n\n      <div>\n        <button type=\"button\" onClick={() => replaceEmployees(sample)}>\n          Load Sample State\n        </button>\n\n        <button type=\"button\" onClick={replaceEmployeesAsync}>\n          Load Async State\n        </button>\n\n        <button type=\"button\" onClick={resetEmployees}>\n          Reset State\n        </button>\n\n        {isFetching && !isLoading ? <div>Loading...</div> : null}\n      </div>\n    </div>\n  );\n}\n",
    numberedSource:
      " 1 | import {\n 2 |   replaceEmployees,\n 3 |   replaceEmployeesAsync,\n 4 |   resetEmployees\n 5 | } from './employee.actions';\n 6 | import { useGetEmployeesState } from './employee.api';\n 7 | import type { Employee } from './employee.model';\n 8 | \n 9 | const sample: Employee[] = [\n10 |   { id: 11, name: 'Luke' },\n11 |   { id: 38, name: 'Leia' },\n12 |   { id: 9, name: 'Han' }\n13 | ];\n14 | \n15 | export function ExampleView() {\n16 |   const {\n17 |     data = [],\n18 |     error,\n19 |     isFetching,\n20 |     isLoading\n21 |   } = useGetEmployeesState();\n22 | \n23 |   return (\n24 |     <div>\n25 |       <div>\n26 |         {isLoading ? (\n27 |           <div>Loading...</div>\n28 |         ) : error ? (\n29 |           <div>{String(error)}</div>\n30 |         ) : (\n31 |           <textarea readOnly value={JSON.stringify(data, null, 2)} />\n32 |         )}\n33 |       </div>\n34 | \n35 |       <div>\n36 |         <button type=\"button\" onClick={() => replaceEmployees(sample)}>\n37 |           Load Sample State\n38 |         </button>\n39 | \n40 |         <button type=\"button\" onClick={replaceEmployeesAsync}>\n41 |           Load Async State\n42 |         </button>\n43 | \n44 |         <button type=\"button\" onClick={resetEmployees}>\n45 |           Reset State\n46 |         </button>\n47 | \n48 |         {isFetching && !isLoading ? <div>Loading...</div> : null}\n49 |       </div>\n50 |     </div>\n51 |   );\n52 | }\n53 | "
  },
  {
    type: 'typescript',
    fileName: 'employee.model.ts',
    source: 'export interface Employee {\n  id: number;\n  name: string;\n}\n',
    numberedSource:
      '1 | export interface Employee {\n2 |   id: number;\n3 |   name: string;\n4 | }\n5 | '
  },
  {
    type: 'typescript',
    fileName: 'employee.api.ts',
    source:
      "import { createApi, fetchBaseQuery } from '@reduxjs/toolkit/query/react';\nimport type { Employee } from './employee.model';\n\nexport const prepareEmployees = (employees: Employee[]): Employee[] => {\n  return employees\n    .filter((employee) => employee.id % 2 !== 0)\n    .sort((left, right) => left.name.localeCompare(right.name));\n};\n\nexport const employeeApi = createApi({\n  reducerPath: 'employeeApi',\n  baseQuery: fetchBaseQuery({ baseUrl: '/api' }),\n  endpoints: (build) => ({\n    getEmployees: build.query<Employee[], void>({\n      query: () => 'employees',\n      transformResponse: prepareEmployees\n    })\n  })\n});\n\nexport const useGetEmployeesState =\n  employeeApi.endpoints.getEmployees.useQueryState;\n",
    numberedSource:
      " 1 | import { createApi, fetchBaseQuery } from '@reduxjs/toolkit/query/react';\n 2 | import type { Employee } from './employee.model';\n 3 | \n 4 | export const prepareEmployees = (employees: Employee[]): Employee[] => {\n 5 |   return employees\n 6 |     .filter((employee) => employee.id % 2 !== 0)\n 7 |     .sort((left, right) => left.name.localeCompare(right.name));\n 8 | };\n 9 | \n10 | export const employeeApi = createApi({\n11 |   reducerPath: 'employeeApi',\n12 |   baseQuery: fetchBaseQuery({ baseUrl: '/api' }),\n13 |   endpoints: (build) => ({\n14 |     getEmployees: build.query<Employee[], void>({\n15 |       query: () => 'employees',\n16 |       transformResponse: prepareEmployees\n17 |     })\n18 |   })\n19 | });\n20 | \n21 | export const useGetEmployeesState =\n22 |   employeeApi.endpoints.getEmployees.useQueryState;\n23 | "
  },
  {
    type: 'typescript',
    fileName: 'employee.actions.ts',
    source:
      "import { employeeApi, prepareEmployees } from './employee.api';\nimport type { Employee } from './employee.model';\nimport { store } from './store';\n\nexport function replaceEmployees(employees: Employee[]): void {\n  store.dispatch(\n    employeeApi.util.upsertQueryData(\n      'getEmployees',\n      undefined,\n      prepareEmployees(employees)\n    )\n  );\n}\n\nexport function replaceEmployeesAsync(): void {\n  void store.dispatch(\n    employeeApi.endpoints.getEmployees.initiate(undefined, {\n      forceRefetch: true,\n      subscribe: false\n    })\n  );\n}\n\nexport function resetEmployees(): void {\n  store.dispatch(employeeApi.util.resetApiState());\n}\n",
    numberedSource:
      " 1 | import { employeeApi, prepareEmployees } from './employee.api';\n 2 | import type { Employee } from './employee.model';\n 3 | import { store } from './store';\n 4 | \n 5 | export function replaceEmployees(employees: Employee[]): void {\n 6 |   store.dispatch(\n 7 |     employeeApi.util.upsertQueryData(\n 8 |       'getEmployees',\n 9 |       undefined,\n10 |       prepareEmployees(employees)\n11 |     )\n12 |   );\n13 | }\n14 | \n15 | export function replaceEmployeesAsync(): void {\n16 |   void store.dispatch(\n17 |     employeeApi.endpoints.getEmployees.initiate(undefined, {\n18 |       forceRefetch: true,\n19 |       subscribe: false\n20 |     })\n21 |   );\n22 | }\n23 | \n24 | export function resetEmployees(): void {\n25 |   store.dispatch(employeeApi.util.resetApiState());\n26 | }\n27 | "
  }
] as const satisfies ReadonlyArray<{
  readonly type:
    'typescript' | 'html' | 'svelte' | 'vue' | 'scss' | 'json' | 'markdown';
  readonly fileName: string;
  readonly source: string;
  readonly numberedSource: string;
}>;
