// --- AI Model File Path (DO NOT DELETE) ---
// FilePath: tools > tutorial > generate-tutorial-source.class.mjs
// Updated: 2026-07-17
// --- END AI MODEL FILE PATH ---

import fs from 'node:fs';
import path from 'node:path';
import archiver from 'archiver';

export const ArchiveModule = {
  create(format, options) {
    return archiver(format, options);
  }
};

const EXCLUDED_DIRECTORIES = new Set([
  '.angular',
  '.git',
  '__MACOSX',
  'node_modules'
]);
const EXCLUDED_FILES = new Set(['.DS_Store']);
const SOURCE_FILE_TYPES = [
  { type: 'component', suffix: '.component.ts' },
  { type: 'service', suffix: '.service.ts' },
  { type: 'html', suffix: '.component.html' },
  { type: 'filter', suffix: '.filter.ts' },
  { type: 'timer', suffix: '.elapsed-timer.ts' },
  { type: 'hydrate', suffix: '.hydrate.ts' },
  { type: 'observable', suffix: '.observable.ts' },
  { type: 'promise', suffix: '.promise.ts' },
  { type: 'httpResource', suffix: '.http-resource.ts' },
  { type: 'scss', suffix: '.component.scss' },
  { type: 'main', suffix: 'main.ts' },
  { type: 'appConfig', suffix: '.config.ts' },
  { type: 'constant', suffix: '.constant.ts' },
  { type: 'shape', suffix: '.shape.ts' },
  { type: 'componentSpec', suffix: '.component.spec.ts' },
  { type: 'serviceSpec', suffix: '.service.spec.ts' },
  { type: 'timerSpec', suffix: '.elapsed-timer.spec.ts' },
  { type: 'observableSpec', suffix: '.observable.spec.ts' },
  { type: 'promiseSpec', suffix: '.promise.spec.ts' },
  { type: 'httpResourceSpec', suffix: '.http-resource.spec.ts' },
  { type: 'hydrateSpec', suffix: '.hydrate.spec.ts' },
  { type: 'characterDomain', suffix: '.character-domain.ts' },
  { type: 'characterDomainSpec', suffix: '.character-domain.spec.ts' },
  { type: 'characterEditor', suffix: '.character-editor.ts' },
  { type: 'characterEditorSpec', suffix: '.character-editor.spec.ts' }
];
const SOURCE_FILE_TYPE_ORDER = new Map(
  SOURCE_FILE_TYPES.map(({ type }, index) => [type, index])
);
const SOURCE_FILE_TYPE_MATCH_ORDER = [...SOURCE_FILE_TYPES].sort(
  (left, right) => right.suffix.length - left.suffix.length
);
const SOURCE_FILE_TYPE_UNION = SOURCE_FILE_TYPES.map(
  ({ type }) => `'${type}'`
).join(' | ');

export class TutorialSourceGenerator {
  constructor({ projectRoot, sourceGroups }) {
    if (!projectRoot) {
      throw new Error('projectRoot is required');
    }

    if (!Array.isArray(sourceGroups) || sourceGroups.length === 0) {
      throw new Error('At least one tutorial source group is required');
    }

    this.projectRoot = projectRoot;
    this.sourceGroups = sourceGroups;
  }

  collectFiles(directory, baseDirectory = directory) {
    const files = [];
    const entries = fs
      .readdirSync(directory, { withFileTypes: true })
      .sort((left, right) => left.name.localeCompare(right.name));

    for (const entry of entries) {
      if (
        EXCLUDED_DIRECTORIES.has(entry.name) ||
        EXCLUDED_FILES.has(entry.name)
      ) {
        continue;
      }

      const absolutePath = path.join(directory, entry.name);

      if (entry.isDirectory()) {
        files.push(...this.collectFiles(absolutePath, baseDirectory));
        continue;
      }

      const sourceFileType = SOURCE_FILE_TYPE_MATCH_ORDER.find(({ suffix }) =>
        entry.name.endsWith(suffix)
      );

      if (!sourceFileType) {
        continue;
      }

      const relativePath = path
        .relative(baseDirectory, absolutePath)
        .split(path.sep)
        .join('/');

      files.push({
        type: sourceFileType.type,
        fileName: relativePath,
        source: fs.readFileSync(absolutePath, 'utf8')
      });
    }

    return files.sort((left, right) => {
      const typeDifference =
        SOURCE_FILE_TYPE_ORDER.get(left.type) -
        SOURCE_FILE_TYPE_ORDER.get(right.type);

      return typeDifference || left.fileName.localeCompare(right.fileName);
    });
  }

  generateSourceFile(exportName, files) {
    return `/**
 * AUTO-GENERATED — do not edit manually.
 * Generated by: tools/tutorial/generate-tutorial-source.mjs
 */
export const ${exportName} = ${JSON.stringify(files, null, 2)} as const satisfies ReadonlyArray<{
  readonly type: ${SOURCE_FILE_TYPE_UNION};
  readonly fileName: string;
  readonly source: string;
}>;
`;
  }

  generateSingleSourceFile(exportName, source) {
    return `/**
 * AUTO-GENERATED — do not edit manually.
 * Generated by: tools/tutorial/generate-tutorial-source.mjs
 */
export const ${exportName} = ${JSON.stringify(source)};
`;
  }

  zipDirectory(sourceDirectory, outputDirectory) {
    const zipFile = path.join(
      outputDirectory,
      `${path.basename(sourceDirectory)}.tutorial.zip`
    );

    fs.mkdirSync(outputDirectory, { recursive: true });

    return new Promise((resolve, reject) => {
      const output = fs.createWriteStream(zipFile);
      const archive = ArchiveModule.create('zip', { zlib: { level: 9 } });

      output.on('close', resolve);
      archive.on('error', reject);
      archive.pipe(output);
      archive.directory(sourceDirectory, false);
      archive.finalize();
    });
  }

  async run() {
    for (const sourceGroup of this.sourceGroups) {
      const hasSourceDirectory = Boolean(sourceGroup.sourceDirectory);
      const hasSourceFile = Boolean(sourceGroup.sourceFile);

      if (hasSourceDirectory === hasSourceFile) {
        throw new Error(
          `Tutorial source group "${sourceGroup.exportName}" must define exactly one sourceDirectory or sourceFile`
        );
      }

      const sourcePath = hasSourceFile
        ? sourceGroup.sourceFile
        : sourceGroup.sourceDirectory;
      const sourceKind = hasSourceFile ? 'file' : 'directory';

      if (!fs.existsSync(sourcePath)) {
        throw new Error(
          `Tutorial source ${sourceKind} was not found: ${sourcePath}`
        );
      }

      const sourceCount = hasSourceFile ? 1 : undefined;
      const files = hasSourceDirectory
        ? this.collectFiles(sourceGroup.sourceDirectory)
        : undefined;
      const generatedSource = hasSourceFile
        ? this.generateSingleSourceFile(
            sourceGroup.exportName,
            fs.readFileSync(sourceGroup.sourceFile, 'utf8')
          )
        : this.generateSourceFile(sourceGroup.exportName, files);

      fs.mkdirSync(path.dirname(sourceGroup.outputFile), { recursive: true });
      fs.writeFileSync(sourceGroup.outputFile, generatedSource, 'utf8');

      if (hasSourceDirectory) {
        await this.zipDirectory(
          sourceGroup.sourceDirectory,
          path.join(path.dirname(sourceGroup.outputFile), 'zip-files')
        );
      }

      console.info(
        `Generated ${sourceCount ?? files.length} tutorial source file(s): ${path.relative(this.projectRoot, sourceGroup.outputFile)}`
      );
    }
  }
}
