FROM node:22-bullseye AS builder

ENV HUSKY=0
ENV npm_config_ignore_scripts=true

WORKDIR /build

ARG DOCS_BUILD_CONFIGURATION=enterprise

COPY ../../angular.json ./
COPY ../../tsconfig.json ./
COPY ../../tsconfig.base.json ./
COPY ../../tsconfig.app.json ./
COPY ../../apps ./apps
COPY ../../libs ./libs
COPY ../../public ./public

COPY ../../apps/docs-app/package.json ./
RUN npm install
RUN npx ng build docs-app --configuration ${DOCS_BUILD_CONFIGURATION}

FROM nginx:1.27-alpine

RUN rm /etc/nginx/conf.d/default.conf && \
	printf 'server {\n  listen 80;\n  server_name _;\n  root /usr/share/nginx/html;\n  index index.html;\n\n  location / {\n    try_files $uri $uri/ /index.html;\n  }\n}\n' > /etc/nginx/conf.d/default.conf

COPY --from=builder /build/dist/docs-app/browser /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]