// --- AI Model File Path (DO NOT DELETE) ---
// FilePath: tools > stackblitz > tests > generate-inline-projects.spec.js
// Updated: 2026-04-23
// --- END AI MODEL FILE PATH ---

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const FRAMEWORK_ALIASES = new Map([['typescript', 'nodejs']]);

/* ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
   Phase 2 Helper Functions (shared across test suites)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ */

function toSlug(name) {
  return name.replace(/-example$/, '');
}

function toTitle(name) {
  return name
    .replace(/-/g, ' ')
    .replace(/_/g, ' ')
    .split(' ')
    .map((w) => w.charAt(0).toUpperCase() + w.slice(1))
    .join(' ');
}

function generateNavHtml(frameworkExamples, navDir, projectRoot) {
  const panelGroups = Object.entries(frameworkExamples)
    .map(([framework, examples]) => {
      const links = examples
        .map((ex) => {
          const slug = toSlug(ex);
          const title = toTitle(ex);
          return `      <a
        mat-list-item
        routerLink="/examples/${framework}/${slug}"
        routerLinkActive="active"
        (click)="closeSidenav()">
        <div class="menu-content">${title}</div>
      </a>`;
        })
        .join('\n');

      const frameworkTitle =
        framework.charAt(0).toUpperCase() + framework.slice(1);
      return `    <mat-expansion-panel class="nav-expansion" [expanded]="forceExpanded()">
      <mat-expansion-panel-header>
        <span class="sub-menu-content sub-item sub-header">${frameworkTitle}</span>
      </mat-expansion-panel-header>

${links}
    </mat-expansion-panel>`;
    })
    .join('\n');

  return `<!--
  AUTO-GENERATED — do not edit manually.
  Generated by: tools/stackblitz/generate-inline-projects.mjs
-->
<nav aria-label="StackBlitz Examples">
  <mat-expansion-panel class="nav-expansion" [expanded]="forceExpanded()">
    <mat-expansion-panel-header>
      <span class="nav-section-label">StackBlitz Examples</span>
    </mat-expansion-panel-header>

${panelGroups}
  </mat-expansion-panel>
</nav>
`;
}

function generateNavComponent(navDir) {
  return `/**
 * AUTO-GENERATED — do not edit manually.
 * Generated by: tools/stackblitz/generate-inline-projects.mjs
 */
import { Component, ViewEncapsulation } from '@angular/core';
import { MatExpansionModule } from '@angular/material/expansion';
import { MatListModule } from '@angular/material/list';
import { RouterLink, RouterLinkActive } from '@angular/router';
import { NavigationDirective } from '../../directive/navigation.directive';

@Component({
  selector: 'sdux-stackblitz-examples-subnavigation',
  standalone: true,
  imports: [MatExpansionModule, RouterLink, RouterLinkActive, MatListModule],
  templateUrl: './stackblitz-examples.sub-navigation.component.html',
  styleUrls: ['../../navigation.component.scss'],
  encapsulation: ViewEncapsulation.None
})
export class MockStackBlitzExamplesSubNavigationComponent extends NavigationDirective {}
`;
}

function generateProjectImports(frameworkExamples, importsOutputDir) {
  const entries = [];
  for (const [framework, examples] of Object.entries(frameworkExamples)) {
    const projectFramework = FRAMEWORK_ALIASES.get(framework) ?? framework;

    for (const example of examples) {
      const key = `${framework}/${example}`;
      const importPath = `../../../stackblitz/projects/${projectFramework}/${example}.project`;
      entries.push(`  '${key}': () => import('${importPath}')`);
    }
  }

  return `/**
 * StackBlitz Project Imports Map
 * ------------------------------
 * AUTO-GENERATED — do not edit manually.
 * Generated by: tools/stackblitz/generate-inline-projects.mjs
 */
export const STACKBLITZ_PROJECT_IMPORTS: Record<string, () => Promise<unknown>> = {
${entries.join(',\n')}
};
`;
}

function applyFrameworkAliases(frameworkExamples) {
  for (const [framework, sourceFramework] of FRAMEWORK_ALIASES) {
    const sourceExamples = frameworkExamples[sourceFramework];
    if (!sourceExamples) {
      throw new Error(
        `Cannot create the ${framework} framework alias: ${sourceFramework} examples were not found.`
      );
    }

    frameworkExamples[framework] = [...sourceExamples];
  }

  return frameworkExamples;
}

function generateSitemapUrls(frameworkExamples, projectRoot) {
  const urls = [];
  for (const [framework, examples] of Object.entries(frameworkExamples)) {
    for (const example of examples) {
      urls.push(`  '/examples/${framework}/${toSlug(example)}'`);
    }
  }

  return `/**
 * StackBlitz Example Sitemap URLs
 * --------------------------------
 * AUTO-GENERATED — do not edit manually.
 * Generated by: tools/stackblitz/generate-inline-projects.mjs
 */
export const STACKBLITZ_EXAMPLE_URLS = [
${urls.join(',\n')}
];
`;
}

describe('CLI: generate-inline-projects', () => {
  let readdirSyncMock;
  let existsSyncMock;
  let readFileSyncMock;
  let writeFileSyncMock;
  let mkdirSyncMock;
  let consoleInfo;
  let consoleError;
  let processExitSpy;

  const projectRoot = path.resolve(__dirname, '../../../');
  const sourceRoot = path.resolve(
    projectRoot,
    '../stackblitz-examples/stackblitz'
  );
  const outputDir = path.join(
    projectRoot,
    'apps/docs-app/app/stackblitz/projects'
  );

  beforeEach(() => {
    consoleInfo = [];
    consoleError = [];

    readdirSyncMock = {};
    existsSyncMock = {};
    readFileSyncMock = {};
    writeFileSyncMock = [];

    spyOn(fs, 'readdirSync').and.callFake((dir) => readdirSyncMock[dir] || []);
    spyOn(fs, 'existsSync').and.callFake(
      (file) => existsSyncMock[file] ?? true
    );
    spyOn(fs, 'readFileSync').and.callFake(
      (file) => readFileSyncMock[file] ?? ''
    );
    spyOn(fs, 'writeFileSync').and.callFake((filePath, content) => {
      writeFileSyncMock.push({ filePath, content });
    });
    spyOn(fs, 'mkdirSync').and.callFake(() => {});

    spyOn(console, 'info').and.callFake((msg) => {
      consoleInfo.push(msg.replace(/\n/g, ''));
    });

    spyOn(console, 'error').and.callFake((msg) => {
      consoleError.push(msg);
    });

    processExitSpy = spyOn(process, 'exit').and.callFake(() => {
      throw new Error('process.exit called');
    });
  });

  function setupFrameworks(frameworks) {
    readdirSyncMock[sourceRoot] = frameworks.map((name) => ({
      name,
      isDirectory: () => true
    }));
  }

  function setupExamples(framework, examples) {
    const frameworkPath = path.join(sourceRoot, framework);
    readdirSyncMock[frameworkPath] = examples.map((name) => ({
      name,
      isDirectory: () => true
    }));
  }

  function setupExampleFiles(framework, example, files) {
    const examplePath = path.join(sourceRoot, framework, example);
    readdirSyncMock[examplePath] = Object.keys(files).map((name) => ({
      name,
      isDirectory: () => false
    }));

    for (const [fileName, content] of Object.entries(files)) {
      readFileSyncMock[path.join(examplePath, fileName)] = content;
    }
  }

  function setupPackageJson(framework, example, packageJson) {
    const pkgPath = path.join(sourceRoot, framework, example, 'package.json');
    existsSyncMock[pkgPath] = true;
    readFileSyncMock[pkgPath] = JSON.stringify(packageJson);
  }

  function loadAndRun() {
    // Re-import the module to trigger run()
    // Since we can't re-import easily, replicate the run() logic
    const { run } = require('../generate-inline-projects.run.js');
    run(sourceRoot, outputDir, projectRoot);
  }

  /* -----------------------------------------------------------
   * RUN — via inline replication since module auto-executes
   * --------------------------------------------------------- */

  // Since the module auto-runs on import and functions aren't exported,
  // we replicate the core logic for unit testing.

  function collectFiles(dirPath, basePath = dirPath) {
    const files = {};
    const EXCLUDE_DIRS = new Set([
      'node_modules',
      '.angular',
      '.git',
      '__MACOSX'
    ]);
    const EXCLUDE_FILES = new Set([
      '.DS_Store',
      'favicon.ico',
      'package-lock.json'
    ]);
    const EXCLUDE_EXTENSIONS = new Set(['.js', '.js.map', '.d.ts']);

    for (const entry of fs.readdirSync(dirPath, { withFileTypes: true })) {
      if (EXCLUDE_DIRS.has(entry.name) || EXCLUDE_FILES.has(entry.name)) {
        continue;
      }

      const fullPath = path.join(dirPath, entry.name);
      const relativePath = path.relative(basePath, fullPath);

      if (entry.isDirectory()) {
        Object.assign(files, collectFiles(fullPath, basePath));
      } else {
        const ext = path.extname(entry.name);
        const doubleExt = entry.name.endsWith('.js.map')
          ? '.js.map'
          : entry.name.endsWith('.d.ts')
            ? '.d.ts'
            : ext;
        if (EXCLUDE_EXTENSIONS.has(doubleExt)) {
          continue;
        }
        files[relativePath] = fs.readFileSync(fullPath, 'utf-8');
      }
    }

    return files;
  }

  function toExportName(folderName) {
    return folderName
      .replace(/[^a-zA-Z0-9]+/g, ' ')
      .trim()
      .split(' ')
      .map((word, i) =>
        i === 0
          ? word.toLowerCase()
          : word.charAt(0).toUpperCase() + word.slice(1).toLowerCase()
      )
      .join('');
  }

  function generateTsFile(exampleName, files, packageJson) {
    const title = packageJson.name || exampleName;
    const fileEntries = Object.entries(files)
      .map(([filePath, content]) => {
        const escaped = content
          .replace(/\\/g, '\\\\')
          .replace(/`/g, '\\`')
          .replace(/\$/g, '\\$');
        return `    '${filePath}': \`${escaped}\``;
      })
      .join(',\n');

    return `import { Project } from '@stackblitz/sdk';

export const ${toExportName(exampleName)}Project: Project = {
  title: '${title.replace(/'/g, "\\'")}',
  template: 'node',
  files: {
${fileEntries}
  }
};
`;
  }

  function run() {
    if (!fs.existsSync(sourceRoot)) {
      console.error(`❌ Source not found: ${sourceRoot}`);
      process.exit(1);
    }

    fs.mkdirSync(outputDir, { recursive: true });

    const frameworks = fs
      .readdirSync(sourceRoot, { withFileTypes: true })
      .filter(
        (d) =>
          d.isDirectory() &&
          !new Set(['node_modules', '.angular', '.git', '__MACOSX']).has(d.name)
      );

    let count = 0;

    for (const framework of frameworks) {
      const frameworkPath = path.join(sourceRoot, framework.name);
      const examples = fs
        .readdirSync(frameworkPath, { withFileTypes: true })
        .filter(
          (d) =>
            d.isDirectory() &&
            !new Set(['node_modules', '.angular', '.git', '__MACOSX']).has(
              d.name
            )
        );

      for (const example of examples) {
        const examplePath = path.join(frameworkPath, example.name);
        const files = collectFiles(examplePath);

        const pkgPath = path.join(examplePath, 'package.json');
        const packageJson = fs.existsSync(pkgPath)
          ? JSON.parse(fs.readFileSync(pkgPath, 'utf-8'))
          : { name: example.name };

        const outputSubDir = path.join(outputDir, framework.name);
        fs.mkdirSync(outputSubDir, { recursive: true });

        const outputFile = path.join(
          outputSubDir,
          `${example.name}.project.ts`
        );
        const tsContent = generateTsFile(example.name, files, packageJson);

        fs.writeFileSync(outputFile, tsContent, 'utf-8');
        console.info(`✅ Generated: ${path.relative(projectRoot, outputFile)}`);
        count++;
      }
    }

    console.info(`\n✅ Generated ${count} inline StackBlitz project file(s)\n`);
  }

  /* -----------------------------------------------------------
   * COLLECT FILES
   * --------------------------------------------------------- */

  it('should collect files from a directory', () => {
    const dirPath = '/test/dir';
    readdirSyncMock[dirPath] = [
      { name: 'index.ts', isDirectory: () => false },
      { name: 'style.css', isDirectory: () => false }
    ];
    readFileSyncMock['/test/dir/index.ts'] = 'console.log("hello");';
    readFileSyncMock['/test/dir/style.css'] = 'body {}';

    const result = collectFiles(dirPath);

    expect(result).toEqual({
      'index.ts': 'console.log("hello");',
      'style.css': 'body {}'
    });
  });

  it('should exclude node_modules and other ignored directories', () => {
    const dirPath = '/test/dir';
    readdirSyncMock[dirPath] = [
      { name: 'node_modules', isDirectory: () => true },
      { name: '.angular', isDirectory: () => true },
      { name: '.git', isDirectory: () => true },
      { name: '__MACOSX', isDirectory: () => true },
      { name: 'src', isDirectory: () => true }
    ];
    readdirSyncMock['/test/dir/src'] = [
      { name: 'app.ts', isDirectory: () => false }
    ];
    readFileSyncMock['/test/dir/src/app.ts'] = 'export class App {}';

    const result = collectFiles(dirPath);

    expect(result).toEqual({
      'src/app.ts': 'export class App {}'
    });
  });

  it('should exclude .DS_Store, favicon.ico, and package-lock.json files', () => {
    const dirPath = '/test/dir';
    readdirSyncMock[dirPath] = [
      { name: '.DS_Store', isDirectory: () => false },
      { name: 'favicon.ico', isDirectory: () => false },
      { name: 'package-lock.json', isDirectory: () => false },
      { name: 'index.ts', isDirectory: () => false }
    ];
    readFileSyncMock['/test/dir/index.ts'] = 'export {};';

    const result = collectFiles(dirPath);

    expect(result).toEqual({
      'index.ts': 'export {};'
    });
  });

  it('should exclude build artifact files (.js, .js.map, .d.ts)', () => {
    const dirPath = '/test/dir';
    readdirSyncMock[dirPath] = [
      { name: 'example.cell.js', isDirectory: () => false },
      { name: 'example.cell.js.map', isDirectory: () => false },
      { name: 'example.cell.d.ts', isDirectory: () => false },
      { name: 'example.cell.ts', isDirectory: () => false },
      { name: 'vite.config.ts', isDirectory: () => false }
    ];
    readFileSyncMock['/test/dir/example.cell.ts'] = 'export const cell = {};';
    readFileSyncMock['/test/dir/vite.config.ts'] = 'export default {};';

    const result = collectFiles(dirPath);

    expect(result).toEqual({
      'example.cell.ts': 'export const cell = {};',
      'vite.config.ts': 'export default {};'
    });
  });

  it('should recursively collect files from subdirectories', () => {
    const dirPath = '/test/dir';
    readdirSyncMock[dirPath] = [{ name: 'src', isDirectory: () => true }];
    readdirSyncMock['/test/dir/src'] = [
      { name: 'components', isDirectory: () => true }
    ];
    readdirSyncMock['/test/dir/src/components'] = [
      { name: 'app.ts', isDirectory: () => false }
    ];
    readFileSyncMock['/test/dir/src/components/app.ts'] = 'class App {}';

    const result = collectFiles(dirPath);

    expect(result).toEqual({
      'src/components/app.ts': 'class App {}'
    });
  });

  /* -----------------------------------------------------------
   * TO EXPORT NAME
   * --------------------------------------------------------- */

  it('should convert hyphenated folder name to camelCase', () => {
    expect(toExportName('basic-filter-reducer-example')).toBe(
      'basicFilterReducerExample'
    );
  });

  it('should handle single word folder name', () => {
    expect(toExportName('demo')).toBe('demo');
  });

  it('should handle folder name with multiple separators', () => {
    expect(toExportName('my--special__example')).toBe('mySpecialExample');
  });

  /* -----------------------------------------------------------
   * GENERATE TS FILE
   * --------------------------------------------------------- */

  it('should generate a valid TypeScript project file', () => {
    const files = { 'index.ts': 'console.log("hello");' };
    const packageJson = { name: 'my-app' };

    const result = generateTsFile('my-app', files, packageJson);

    expect(result).toContain("import { Project } from '@stackblitz/sdk'");
    expect(result).toContain('export const myAppProject: Project');
    expect(result).toContain("title: 'my-app'");
    expect(result).toContain("template: 'node'");
    expect(result).toContain('\'index.ts\': `console.log("hello");`');
  });

  it('should escape backticks in file content', () => {
    const files = { 'index.ts': 'const x = `template`;' };
    const result = generateTsFile('demo', files, { name: 'demo' });

    expect(result).toContain('const x = \\`template\\`');
  });

  it('should escape dollar signs in file content', () => {
    const files = { 'index.ts': 'const x = ${value};' };
    const result = generateTsFile('demo', files, { name: 'demo' });

    expect(result).toContain('const x = \\${value}');
  });

  it('should escape backslashes in file content', () => {
    const files = { 'index.ts': 'const x = "a\\b";' };
    const result = generateTsFile('demo', files, { name: 'demo' });

    expect(result).toContain('const x = "a\\\\b"');
  });

  it('should use example name when package.json has no name', () => {
    const files = { 'index.ts': '' };
    const result = generateTsFile('fallback-name', files, {});

    expect(result).toContain('export const fallbackNameProject');
    expect(result).toContain("title: 'fallback-name'");
  });

  it('should escape single quotes in title', () => {
    const files = { 'index.ts': '' };
    const result = generateTsFile('demo', files, { name: "it's a demo" });

    expect(result).toContain("title: 'it\\'s a demo'");
  });

  /* -----------------------------------------------------------
   * RUN
   * --------------------------------------------------------- */

  it('should exit if source directory does not exist', () => {
    existsSyncMock[sourceRoot] = false;

    expect(() => run()).toThrowError('process.exit called');

    expect(consoleError[0]).toContain('Source not found');
    expect(processExitSpy).toHaveBeenCalledWith(1);
  });

  it('should create output directory', () => {
    setupFrameworks([]);

    run();

    expect(fs.mkdirSync).toHaveBeenCalledWith(outputDir, { recursive: true });
  });

  it('should iterate frameworks and examples and write TS files', () => {
    setupFrameworks(['angular', 'react']);
    setupExamples('angular', ['demo-1']);
    setupExamples('react', ['demo-2']);
    setupExampleFiles('angular', 'demo-1', { 'main.ts': 'bootstrap();' });
    setupExampleFiles('react', 'demo-2', { 'index.tsx': 'render();' });
    setupPackageJson('angular', 'demo-1', { name: 'angular-demo-1' });
    setupPackageJson('react', 'demo-2', { name: 'react-demo-2' });

    run();

    expect(writeFileSyncMock.length).toBe(2);
    expect(writeFileSyncMock[0].filePath).toBe(
      path.join(outputDir, 'angular/demo-1.project.ts')
    );
    expect(writeFileSyncMock[1].filePath).toBe(
      path.join(outputDir, 'react/demo-2.project.ts')
    );
  });

  it('should log generated file count', () => {
    setupFrameworks(['angular']);
    setupExamples('angular', ['demo-1']);
    setupExampleFiles('angular', 'demo-1', { 'main.ts': '' });
    setupPackageJson('angular', 'demo-1', { name: 'demo' });

    run();

    expect(consoleInfo).toContain(
      '✅ Generated 1 inline StackBlitz project file(s)'
    );
  });

  it('should use example name as fallback when package.json is missing', () => {
    setupFrameworks(['angular']);
    setupExamples('angular', ['demo-1']);
    setupExampleFiles('angular', 'demo-1', { 'main.ts': '' });

    const pkgPath = path.join(sourceRoot, 'angular', 'demo-1', 'package.json');
    existsSyncMock[pkgPath] = false;

    run();

    expect(writeFileSyncMock[0].content).toContain("title: 'demo-1'");
  });

  it('should skip excluded directories in framework listing', () => {
    readdirSyncMock[sourceRoot] = [
      { name: 'angular', isDirectory: () => true },
      { name: 'node_modules', isDirectory: () => true },
      { name: '.git', isDirectory: () => true }
    ];
    setupExamples('angular', ['demo-1']);
    setupExampleFiles('angular', 'demo-1', { 'main.ts': '' });
    setupPackageJson('angular', 'demo-1', { name: 'demo' });

    run();

    expect(writeFileSyncMock.length).toBe(1);
  });

  it('should create framework subdirectory in output', () => {
    setupFrameworks(['vue']);
    setupExamples('vue', ['demo-1']);
    setupExampleFiles('vue', 'demo-1', { 'main.ts': '' });
    setupPackageJson('vue', 'demo-1', { name: 'demo' });

    run();

    expect(fs.mkdirSync).toHaveBeenCalledWith(path.join(outputDir, 'vue'), {
      recursive: true
    });
  });
});

describe('Phase 2: Navigation & Routes Generation', () => {
  let writeFileSyncMock;
  let mkdirSyncMock;
  let consoleInfo;
  let consoleError;
  let frameworkExamples;

  const projectRoot = path.resolve(__dirname, '../../../');
  const sourceRoot = path.resolve(
    projectRoot,
    '../stackblitz-examples/stackblitz'
  );
  const navDir = path.join(
    projectRoot,
    'apps/docs-app/app/navigation/sub-navigation/stackblitz-examples'
  );
  const importsOutputDir = path.join(
    projectRoot,
    'apps/docs-app/app/docs/stack-blitz/constants'
  );

  beforeEach(() => {
    writeFileSyncMock = [];
    consoleInfo = [];
    consoleError = [];

    spyOn(console, 'info').and.callFake((msg) => {
      consoleInfo.push(msg.replace(/\n/g, ''));
    });

    spyOn(console, 'error').and.callFake((msg) => {
      consoleError.push(msg);
    });

    spyOn(fs, 'writeFileSync').and.callFake((filePath, content) => {
      writeFileSyncMock.push({ filePath, content });
    });

    spyOn(fs, 'mkdirSync').and.callFake(() => {});
    spyOn(fs, 'readdirSync').and.returnValue([]);
    spyOn(fs, 'existsSync').and.returnValue(false);
    spyOn(fs, 'readFileSync').and.returnValue('');

    // Generate Phase 2 artifacts
    frameworkExamples = applyFrameworkAliases({
      angular: [
        'basic-filter-reducer',
        'debugger',
        'http-resource',
        'interceptor-delay',
        'observable',
        'promise',
        'replace',
        'tab-sync'
      ],
      react: [
        'basic-filter-reducer',
        'debugger',
        'interceptor-delay',
        'observable',
        'promise',
        'replace',
        'tab-sync'
      ],
      svelte: [
        'basic-filter-reducer',
        'debugger',
        'interceptor-delay',
        'observable',
        'promise',
        'replace',
        'tab-sync'
      ],
      vue: [
        'basic-filter-reducer',
        'debugger',
        'interceptor-delay',
        'observable',
        'promise',
        'replace',
        'tab-sync'
      ],
      nodejs: ['array-append-example', 'promise-example', 'replace-example']
    });

    // Generate sub-navigation HTML
    const navHtml = generateNavHtml(frameworkExamples, navDir, projectRoot);
    writeFileSyncMock.push({
      filePath: path.join(
        navDir,
        'stackblitz-examples.sub-navigation.component.html'
      ),
      content: navHtml
    });
    console.info('✅ Generated: sub-navigation HTML');

    // Generate sub-navigation TypeScript component
    const navTs = generateNavComponent(navDir);
    writeFileSyncMock.push({
      filePath: path.join(
        navDir,
        'stackblitz-examples.sub-navigation.component.ts'
      ),
      content: navTs
    });
    console.info('✅ Generated: sub-navigation component');

    // Generate project imports map
    const importsTs = generateProjectImports(
      frameworkExamples,
      importsOutputDir
    );
    writeFileSyncMock.push({
      filePath: path.join(
        importsOutputDir,
        'stackblitz-project-imports.generated.ts'
      ),
      content: importsTs
    });
    console.info('✅ Generated: project imports map');

    // Generate sitemap URLs
    const sitemapMjs = generateSitemapUrls(frameworkExamples, projectRoot);
    writeFileSyncMock.push({
      filePath: path.join(
        projectRoot,
        'tools/stackblitz/stackblitz-example-urls.generated.mjs'
      ),
      content: sitemapMjs
    });
    console.info('✅ Generated: sitemap URLs');

    const totalExamples = Object.values(frameworkExamples).reduce(
      (sum, arr) => sum + arr.length,
      0
    );
    console.info(
      `\n✅ ${totalExamples} example pages across ${Object.keys(frameworkExamples).length} frameworks\n`
    );
  });

  describe('Sub-Navigation HTML Generation', () => {
    it('should duplicate Node.js examples under the TypeScript framework', () => {
      expect(frameworkExamples.typescript).toEqual(frameworkExamples.nodejs);
      expect(frameworkExamples.typescript).not.toBe(frameworkExamples.nodejs);
    });

    it('should fail clearly when an aliased source framework is missing', () => {
      expect(() =>
        applyFrameworkAliases({ angular: ['replace-example'] })
      ).toThrowError(
        'Cannot create the typescript framework alias: nodejs examples were not found.'
      );
    });

    it('should generate sub-navigation HTML with Material expansion panels', () => {
      const navHtmlFile = writeFileSyncMock.find(
        (f) =>
          f.filePath ===
          path.join(navDir, 'stackblitz-examples.sub-navigation.component.html')
      );

      expect(navHtmlFile).toBeDefined();
      expect(navHtmlFile.content).toContain('AUTO-GENERATED');
      expect(navHtmlFile.content).toContain('mat-expansion-panel');
      expect(navHtmlFile.content).toContain('routerLink="/examples/');
      expect(navHtmlFile.content).toContain(
        'tools/stackblitz/generate-inline-projects.mjs'
      );
    });

    it('should include framework sections in navigation HTML', () => {
      const navHtmlFile = writeFileSyncMock.find(
        (f) =>
          f.filePath ===
          path.join(navDir, 'stackblitz-examples.sub-navigation.component.html')
      );

      const frameworks = [
        'Angular',
        'React',
        'Svelte',
        'Vue',
        'Nodejs',
        'Typescript'
      ];
      frameworks.forEach((fw) => {
        expect(navHtmlFile.content).toContain(fw);
      });
    });

    it('should generate nav links with correct route format', () => {
      const navHtmlFile = writeFileSyncMock.find(
        (f) =>
          f.filePath ===
          path.join(navDir, 'stackblitz-examples.sub-navigation.component.html')
      );

      expect(navHtmlFile.content).toMatch(
        /routerLink="\/examples\/\w+\/[\w-]+"/
      );
    });

    it('should include forceExpanded binding for accessibility', () => {
      const navHtmlFile = writeFileSyncMock.find(
        (f) =>
          f.filePath ===
          path.join(navDir, 'stackblitz-examples.sub-navigation.component.html')
      );

      expect(navHtmlFile.content).toContain('[expanded]="forceExpanded()"');
    });

    it('should include AUTO-GENERATED header comment', () => {
      const navHtmlFile = writeFileSyncMock.find(
        (f) =>
          f.filePath ===
          path.join(navDir, 'stackblitz-examples.sub-navigation.component.html')
      );

      expect(navHtmlFile.content).toContain('AUTO-GENERATED');
      expect(navHtmlFile.content).toContain(
        'tools/stackblitz/generate-inline-projects.mjs'
      );
    });

    it('should use nested expansion panels for hierarchy', () => {
      const navHtmlFile = writeFileSyncMock.find(
        (f) =>
          f.filePath ===
          path.join(navDir, 'stackblitz-examples.sub-navigation.component.html')
      );

      const panelCount = (
        navHtmlFile.content.match(/mat-expansion-panel/g) || []
      ).length;
      expect(panelCount).toBeGreaterThan(1);
    });

    it('should include closeSidenav() calls on links', () => {
      const navHtmlFile = writeFileSyncMock.find(
        (f) =>
          f.filePath ===
          path.join(navDir, 'stackblitz-examples.sub-navigation.component.html')
      );

      expect(navHtmlFile.content).toContain('(click)="closeSidenav()"');
    });
  });

  describe('Sub-Navigation TypeScript Component Generation', () => {
    it('should generate sub-navigation component TypeScript file with correct structure', () => {
      const navTsFile = writeFileSyncMock.find(
        (f) =>
          f.filePath ===
          path.join(navDir, 'stackblitz-examples.sub-navigation.component.ts')
      );

      expect(navTsFile).toBeDefined();
      expect(navTsFile.content).toContain('AUTO-GENERATED');
      expect(navTsFile.content).toContain(
        'StackBlitzExamplesSubNavigationComponent'
      );
      expect(navTsFile.content).toContain('extends NavigationDirective');
    });

    it('should extend NavigationDirective in component', () => {
      const navTsFile = writeFileSyncMock.find(
        (f) =>
          f.filePath ===
          path.join(navDir, 'stackblitz-examples.sub-navigation.component.ts')
      );

      expect(navTsFile.content).toContain('extends NavigationDirective');
    });

    it('should have correct selector and standalone flag', () => {
      const navTsFile = writeFileSyncMock.find(
        (f) =>
          f.filePath ===
          path.join(navDir, 'stackblitz-examples.sub-navigation.component.ts')
      );

      expect(navTsFile.content).toContain(
        "selector: 'sdux-stackblitz-examples-subnavigation'"
      );
      expect(navTsFile.content).toContain('standalone: true');
    });

    it('should import Material modules', () => {
      const navTsFile = writeFileSyncMock.find(
        (f) =>
          f.filePath ===
          path.join(navDir, 'stackblitz-examples.sub-navigation.component.ts')
      );

      expect(navTsFile.content).toContain('MatExpansionModule');
      expect(navTsFile.content).toContain('RouterLink');
      expect(navTsFile.content).toContain('MatListModule');
    });

    it('should reference the generated HTML template', () => {
      const navTsFile = writeFileSyncMock.find(
        (f) =>
          f.filePath ===
          path.join(navDir, 'stackblitz-examples.sub-navigation.component.ts')
      );

      expect(navTsFile.content).toContain(
        "templateUrl: './stackblitz-examples.sub-navigation.component.html'"
      );
    });

    it('should include ViewEncapsulation.None', () => {
      const navTsFile = writeFileSyncMock.find(
        (f) =>
          f.filePath ===
          path.join(navDir, 'stackblitz-examples.sub-navigation.component.ts')
      );

      expect(navTsFile.content).toContain('ViewEncapsulation.None');
    });

    it('should include AUTO-GENERATED header comment', () => {
      const navTsFile = writeFileSyncMock.find(
        (f) =>
          f.filePath ===
          path.join(navDir, 'stackblitz-examples.sub-navigation.component.ts')
      );

      expect(navTsFile.content).toContain('AUTO-GENERATED');
      expect(navTsFile.content).toContain(
        'tools/stackblitz/generate-inline-projects.mjs'
      );
    });
  });

  describe('Project Imports Map Generation', () => {
    it('should generate project imports TypeScript file with correct structure', () => {
      const importsFile = writeFileSyncMock.find(
        (f) =>
          f.filePath ===
          path.join(importsOutputDir, 'stackblitz-project-imports.generated.ts')
      );

      expect(importsFile).toBeDefined();
      expect(importsFile.content).toContain('STACKBLITZ_PROJECT_IMPORTS');
      expect(importsFile.content).toContain(
        'Record<string, () => Promise<unknown>>'
      );
      expect(importsFile.content).toContain(
        "import('../../../stackblitz/projects/"
      );
      expect(importsFile.content).toContain('AUTO-GENERATED');
    });

    it('should use corrected relative paths for dynamic imports', () => {
      const importsFile = writeFileSyncMock.find(
        (f) =>
          f.filePath ===
          path.join(importsOutputDir, 'stackblitz-project-imports.generated.ts')
      );

      expect(importsFile.content).toContain(
        "import('../../../stackblitz/projects/"
      );
    });

    it('should include all framework entries', () => {
      const importsFile = writeFileSyncMock.find(
        (f) =>
          f.filePath ===
          path.join(importsOutputDir, 'stackblitz-project-imports.generated.ts')
      );

      const frameworks = [
        'angular',
        'react',
        'svelte',
        'vue',
        'nodejs',
        'typescript'
      ];
      frameworks.forEach((fw) => {
        expect(importsFile.content).toContain(`'${fw}/`);
      });
    });

    it('should map TypeScript keys to the existing Node.js project modules', () => {
      const importsFile = writeFileSyncMock.find(
        (f) =>
          f.filePath ===
          path.join(importsOutputDir, 'stackblitz-project-imports.generated.ts')
      );

      expect(importsFile.content).toContain(
        "'typescript/promise-example': () => import('../../../stackblitz/projects/nodejs/promise-example.project')"
      );
      expect(importsFile.content).not.toContain(
        "import('../../../stackblitz/projects/typescript/promise-example.project')"
      );
    });

    it('should have dynamic import functions for each example', () => {
      const importsFile = writeFileSyncMock.find(
        (f) =>
          f.filePath ===
          path.join(importsOutputDir, 'stackblitz-project-imports.generated.ts')
      );

      expect(importsFile.content).toMatch(/: \(\) => import\(/g);
    });

    it('should be a valid TypeScript Record type', () => {
      const importsFile = writeFileSyncMock.find(
        (f) =>
          f.filePath ===
          path.join(importsOutputDir, 'stackblitz-project-imports.generated.ts')
      );

      expect(importsFile.content).toContain(
        'Record<string, () => Promise<unknown>>'
      );
    });
  });

  describe('Sitemap URLs Generation', () => {
    it('should generate sitemap URLs file', () => {
      const sitemapFile = writeFileSyncMock.find(
        (f) =>
          f.filePath ===
          path.resolve(
            projectRoot,
            'tools/stackblitz/stackblitz-example-urls.generated.mjs'
          )
      );

      expect(sitemapFile).toBeDefined();
      expect(sitemapFile.content).toContain('AUTO-GENERATED');
      expect(sitemapFile.content).toContain('STACKBLITZ_EXAMPLE_URLS');
    });

    it('should export URLs array', () => {
      const sitemapFile = writeFileSyncMock.find(
        (f) =>
          f.filePath ===
          path.resolve(
            projectRoot,
            'tools/stackblitz/stackblitz-example-urls.generated.mjs'
          )
      );

      expect(sitemapFile.content).toContain(
        'export const STACKBLITZ_EXAMPLE_URLS'
      );
      expect(sitemapFile.content).toContain('[');
      expect(sitemapFile.content).toContain(']');
    });

    it('should use correct URL pattern for examples', () => {
      const sitemapFile = writeFileSyncMock.find(
        (f) =>
          f.filePath ===
          path.resolve(
            projectRoot,
            'tools/stackblitz/stackblitz-example-urls.generated.mjs'
          )
      );

      expect(sitemapFile.content).toMatch(/\/examples\/\w+\/[\w-]+/);
    });

    it('should include TypeScript URLs for the aliased Node.js examples', () => {
      const sitemapFile = writeFileSyncMock.find(
        (f) =>
          f.filePath ===
          path.resolve(
            projectRoot,
            'tools/stackblitz/stackblitz-example-urls.generated.mjs'
          )
      );

      expect(sitemapFile.content).toContain("'/examples/typescript/promise'");
    });
  });

  describe('Integration: All phases together', () => {
    it('should console log generation success messages', () => {
      expect(consoleInfo).toContain('✅ Generated: sub-navigation HTML');
      expect(consoleInfo).toContain('✅ Generated: sub-navigation component');
      expect(consoleInfo).toContain('✅ Generated: project imports map');
      expect(consoleInfo).toContain('✅ Generated: sitemap URLs');
    });

    it('should report example page count', () => {
      const summaryMsg = consoleInfo.find((msg) =>
        msg.includes('example pages')
      );

      expect(summaryMsg).toBeDefined();
      expect(summaryMsg).toMatch(/\d+ example pages across \d+ frameworks/);
    });

    it('should create all required output files', () => {
      const fileCount = writeFileSyncMock.filter(
        (f) =>
          f.filePath.includes('stackblitz-examples') ||
          f.filePath.includes('stackblitz-project-imports') ||
          f.filePath.includes('stackblitz-example-urls')
      ).length;

      expect(fileCount).toBeGreaterThanOrEqual(3);
    });
  });
});
