/**
 * StackBlitz Project Imports Map
 * ------------------------------
 * AUTO-GENERATED — do not edit manually.
 * Generated by: tools/stackblitz/generate-inline-projects.mjs
 */
export const STACKBLITZ_PROJECT_IMPORTS: Record<
  string,
  () => Promise<unknown>
> = {
  'angular/basic-filter-reducer': () =>
    import('../../../stackblitz/projects/angular/basic-filter-reducer.project'),
  'react/debugger': () =>
    import('../../../stackblitz/projects/react/debugger.project'),
  'svelte/observable': () =>
    import('../../../stackblitz/projects/svelte/observable.project'),
  'vue/tab-sync': () =>
    import('../../../stackblitz/projects/vue/tab-sync.project')
};
