// --- AI Model File Path (DO NOT DELETE) ---
// FilePath: tools > documentation > enterprise-docs > build-enterprise-docs.class.mjs
// Updated: 2026-03-09 14:55
//	 Generated by pathcomment [tab] (see .vscode/typescript.code-snippets) or
//	 cmd+alt+j (see .vscode/keybindings.json)
// --- END AI MODEL FILE PATH ---

import archiver from 'archiver';
import fs from 'fs';
import path from 'path';
import { ExecModule } from '../../utils/exec-sync.util.mjs';

export const ArchiveModule = {
  create(format, options) {
    return archiver(format, options);
  }
};

export class EnterpriseDocsBuilder {
  constructor({ root }) {
    this.ROOT = root;
    this.DIST = path.join(root, 'dist');
    this.ENTERPRISE_DIR = path.join(this.DIST, 'enterprise-docs');
  }

  run() {
    console.info('\n===================================');
    console.info(' SDuX Enterprise Documentation Build');
    console.info('===================================\n');

    this.clean();
    this.copyAssets();
    this.normalizeIndex();
    this.writeOfflineManifest();
    this.writeLaunchers();
    this.writeReadme();

    return this.zipDocs().then(() => {
      this.openOutputFolder();
      console.info('\nEnterprise documentation build complete\n');
    });
  }

  normalizeIndex() {
    const offline = path.join(this.ENTERPRISE_DIR, 'index.offline.html');
    const normal = path.join(this.ENTERPRISE_DIR, 'index.html');

    if (fs.existsSync(offline)) {
      fs.renameSync(offline, normal);
    }
  }

  writeReadme() {
    const readme = `
# SDuX Enterprise Documentation

Welcome to the **SDuX Enterprise Offline Documentation Bundle**.

This package contains the complete SDuX documentation site and can run entirely offline.

---

## Launch the Documentation

### Mac
Double-click:

start-docs.command

### Windows
Double-click:

start-docs.bat

### Linux
Run:

./start-docs.sh

---

## Manual Launch (Optional)

If needed, you can also run the Node launcher manually:

node start-docs.js

The documentation will be available at:

http://localhost:4321

---

## Contents

This bundle includes:

- Complete SDuX documentation
- Architecture diagrams
- Code examples
- Search index
- Offline assets (fonts, icons, styles)

No internet connection is required.

---

## Notes

• Requires Node.js installed on your system  
• Documentation runs locally in your browser  
• No data is transmitted externally

---

## About SDuX

SDuX is a reactive signal-based architecture for building scalable applications using plain TypeScript with zero magic.

https://sdux.dev

---
`;

    fs.writeFileSync(
      path.join(this.ENTERPRISE_DIR, 'README.md'),
      readme.trim()
    );
  }

  clean() {
    console.info('Cleaning enterprise docs folder');

    if (fs.existsSync(this.ENTERPRISE_DIR)) {
      fs.rmSync(this.ENTERPRISE_DIR, { recursive: true, force: true });
    }

    fs.mkdirSync(this.ENTERPRISE_DIR, { recursive: true });
  }

  copyDir(src, dest) {
    if (!fs.existsSync(src)) return;

    fs.mkdirSync(dest, { recursive: true });

    for (const file of fs.readdirSync(src)) {
      const srcPath = path.join(src, file);
      const destPath = path.join(dest, file);

      if (fs.statSync(srcPath).isDirectory()) {
        this.copyDir(srcPath, destPath);
      } else {
        fs.copyFileSync(srcPath, destPath);
      }
    }
  }

  copyAssets() {
    console.info('\nCopying documentation assets');

    const siteDist = path.join(this.DIST, 'webapp', 'browser');

    this.copyDir(siteDist, this.ENTERPRISE_DIR);

    this.copyDir(
      path.join(this.ROOT, 'src/assets/diagrams'),
      path.join(this.ENTERPRISE_DIR, 'diagrams')
    );

    this.copyDir(
      path.join(this.ROOT, 'src/assets/search-index'),
      path.join(this.ENTERPRISE_DIR, 'search-index')
    );

    this.copyDir(
      path.join(this.ROOT, 'documentation'),
      path.join(this.ENTERPRISE_DIR, 'reference')
    );
  }

  writeOfflineManifest() {
    const manifest = {
      name: 'SDuX Enterprise Documentation',
      version: '1.0.0',
      generated: new Date().toISOString(),
      offline: true
    };

    fs.writeFileSync(
      path.join(this.ENTERPRISE_DIR, 'enterprise-docs.json'),
      JSON.stringify(manifest, null, 2)
    );
  }

  writeMacLauncher() {
    const script = `#!/bin/bash

set -e

echo "Starting SDuX Enterprise Documentation..."

DOCS_DIR="$(cd "$(dirname "$0")" && pwd)"
PORT=4321
URL="http://localhost:$PORT"
LOG_FILE="$DOCS_DIR/start-docs.log"

cd "$DOCS_DIR"

echo "Docs directory: $DOCS_DIR"
echo "Log file: $LOG_FILE"

# Start static server in SPA mode from the docs directory
nohup npx serve "$DOCS_DIR" -l "$PORT" -s > "$LOG_FILE" 2>&1 &

# Wait for server to come up
for i in {1..20}; do
  if curl -s "$URL" > /dev/null 2>&1; then
    echo "Server is ready."
    open "$URL"
    echo ""
    echo "SDuX Enterprise Docs running at:"
    echo "$URL"
    exit 0
  fi
  sleep 1
done

echo ""
echo "Failed to start SDuX Enterprise Docs."
echo "Check log file:"
echo "$LOG_FILE"
exit 1
`;

    const filePath = path.join(this.ENTERPRISE_DIR, 'start-docs.command');

    fs.writeFileSync(filePath, script);
    fs.chmodSync(filePath, '755');
  }

  writeLauncher() {
    const launcher = `
const { exec } = require('child_process');
const os = require('os');

const port = 4321;
const url = "http://localhost:" + port;

console.log("Starting SDuX Enterprise Docs...");

exec("npx serve . -p " + port, { stdio: "inherit" });

setTimeout(() => {
  const platform = os.platform();

  if (platform === "darwin") {
    exec("open " + url);
  } else if (platform === "win32") {
    exec("start " + url);
  } else {
    exec("xdg-open " + url);
  }

  console.log("Docs available at " + url);
}, 1500);
`;

    fs.writeFileSync(path.join(this.ENTERPRISE_DIR, 'start-docs.js'), launcher);
  }

  writeWindowsLauncher() {
    const script = `
@echo off
setlocal

echo Starting SDuX Enterprise Documentation...

set DOCS_DIR=%~dp0
set PORT=4321
set URL=http://localhost:%PORT%

cd /d "%DOCS_DIR%"

echo Docs directory: %DOCS_DIR%

start "" cmd /c "npx serve \"%DOCS_DIR%\" -l %PORT% -s"

echo Waiting for server...

timeout /t 3 >nul

start "" "%URL%"

echo.
echo SDuX Enterprise Docs running at:
echo %URL%
`;

    fs.writeFileSync(path.join(this.ENTERPRISE_DIR, 'start-docs.bat'), script);
  }

  writeLinuxLauncher() {
    const script = `#!/bin/bash

set -e

echo "Starting SDuX Enterprise Documentation..."

DOCS_DIR="$(cd "$(dirname "$0")" && pwd)"
PORT=4321
URL="http://localhost:$PORT"

cd "$DOCS_DIR"

echo "Docs directory: $DOCS_DIR"

npx serve "$DOCS_DIR" -l "$PORT" -s &

echo "Waiting for server..."

sleep 3

xdg-open "$URL"

echo ""
echo "SDuX Enterprise Docs running at:"
echo "$URL"
`;

    const filePath = path.join(this.ENTERPRISE_DIR, 'start-docs.sh');

    fs.writeFileSync(filePath, script);
    fs.chmodSync(filePath, '755');
  }

  writeLaunchers() {
    this.writeLauncher();
    this.writeMacLauncher();
    this.writeWindowsLauncher();
    this.writeLinuxLauncher();
  }

  zipDocs() {
    console.info('\nCreating enterprise documentation archive');

    const zipPath = path.join(this.DIST, 'sdux-enterprise-docs.zip');

    const output = fs.createWriteStream(zipPath);
    const archive = ArchiveModule.create('zip', { zlib: { level: 9 } });

    archive.pipe(output);
    archive.directory(this.ENTERPRISE_DIR, false);

    return new Promise((resolve) => {
      output.on('close', resolve);
      archive.finalize();
    });
  }

  openOutputFolder() {
    console.info('\nOpening enterprise documentation folder\n');

    const cmd =
      process.platform === 'darwin'
        ? `open -R "${path.join(this.DIST, 'sdux-enterprise-docs.zip')}"`
        : process.platform === 'win32'
          ? `start "" "${this.DIST}"`
          : `xdg-open "${this.DIST}"`;

    ExecModule.exec(cmd);
  }
}
