/**
 * AUTO-GENERATED — do not edit manually.
 * Generated by: tools/sdux-comparison/sdux-comparison.mjs
 */
export const SVELTE_STORES_OUTPUT = [
  {
    type: 'typescript',
    fileName: 'main.ts',
    source:
      "import { mount } from 'svelte';\nimport App from './App.svelte';\n\nmount(App, { target: document.getElementById('app')! });",
    numberedSource:
      "1 | import { mount } from 'svelte';\n2 | import App from './App.svelte';\n3 | \n4 | mount(App, { target: document.getElementById('app')! });"
  },
  {
    type: 'svelte',
    fileName: 'App.svelte',
    source:
      '<script lang="ts">\n  import ExampleView from \'./ExampleView.svelte\';\n</script>\n\n<ExampleView />',
    numberedSource:
      '1 | <script lang="ts">\n2 |   import ExampleView from \'./ExampleView.svelte\';\n3 | </script>\n4 | \n5 | <ExampleView />'
  },
  {
    type: 'typescript',
    fileName: 'employee.store.ts',
    source:
      "import { writable } from 'svelte/store';\nimport { Employee, EmployeeState } from './employee.model';\n\nconst filterOddEmployees = (employees: Employee[]): Employee[] => {\n  return employees.filter((employee) => employee.id % 2 !== 0);\n};\n\nconst sortEmployeesByName = (employees: Employee[]): Employee[] => {\n  const sortedEmployees = [...employees];\n\n  sortedEmployees.sort((left, right) => left.name.localeCompare(right.name));\n\n  return sortedEmployees;\n};\n\nconst prepareEmployees = (employees: Employee[]): Employee[] => {\n  return sortEmployeesByName(filterOddEmployees(employees));\n};\n\nconst initialEmployeeState: EmployeeState = {\n  loading: false,\n  value: [],\n  error: null\n};\n\nconst { subscribe, set, update } = writable<EmployeeState>(initialEmployeeState);\n\nexport const employeeState = {\n  subscribe\n};\n\nexport function replaceEmployees(employees: Employee[]): void {\n  update(() => ({\n    loading: false,\n    value: prepareEmployees(employees),\n    error: null\n  }));\n}\n\nexport function resetEmployees(): void {\n  set(initialEmployeeState);\n}",
    numberedSource:
      " 1 | import { writable } from 'svelte/store';\n 2 | import { Employee, EmployeeState } from './employee.model';\n 3 | \n 4 | const filterOddEmployees = (employees: Employee[]): Employee[] => {\n 5 |   return employees.filter((employee) => employee.id % 2 !== 0);\n 6 | };\n 7 | \n 8 | const sortEmployeesByName = (employees: Employee[]): Employee[] => {\n 9 |   const sortedEmployees = [...employees];\n10 | \n11 |   sortedEmployees.sort((left, right) => left.name.localeCompare(right.name));\n12 | \n13 |   return sortedEmployees;\n14 | };\n15 | \n16 | const prepareEmployees = (employees: Employee[]): Employee[] => {\n17 |   return sortEmployeesByName(filterOddEmployees(employees));\n18 | };\n19 | \n20 | const initialEmployeeState: EmployeeState = {\n21 |   loading: false,\n22 |   value: [],\n23 |   error: null\n24 | };\n25 | \n26 | const { subscribe, set, update } = writable<EmployeeState>(initialEmployeeState);\n27 | \n28 | export const employeeState = {\n29 |   subscribe\n30 | };\n31 | \n32 | export function replaceEmployees(employees: Employee[]): void {\n33 |   update(() => ({\n34 |     loading: false,\n35 |     value: prepareEmployees(employees),\n36 |     error: null\n37 |   }));\n38 | }\n39 | \n40 | export function resetEmployees(): void {\n41 |   set(initialEmployeeState);\n42 | }"
  },
  {
    type: 'svelte',
    fileName: 'ExampleView.svelte',
    source:
      "<script lang=\"ts\">\n  import type { Employee } from './employee.model';\n  import { employeeState, replaceEmployees, resetEmployees } from './employee.store';\n\n  const sample: Employee[] = [\n    { id: 11, name: 'Luke' },\n    { id: 38, name: 'Leia' },\n    { id: 9, name: 'Han' }\n  ];\n\n  function loadSample(): void {\n    replaceEmployees(sample);\n  }\n\n  function resetState(): void {\n    resetEmployees();\n  }\n</script>\n\n<div>\n  <div>\n    {#if $employeeState.loading}\n      <div>Loading...</div>\n    {:else if $employeeState.error}\n      <div>{$employeeState.error}</div>\n    {:else}\n      <textarea readonly>{JSON.stringify($employeeState.value, null, 2)}</textarea>\n    {/if}\n  </div>\n\n  <div>\n    <button type=\"button\" on:click={loadSample}>Load Sample State</button>\n\n    <button type=\"button\" on:click={resetState}>Reset State</button>\n  </div>\n</div>",
    numberedSource:
      " 1 | <script lang=\"ts\">\n 2 |   import type { Employee } from './employee.model';\n 3 |   import { employeeState, replaceEmployees, resetEmployees } from './employee.store';\n 4 | \n 5 |   const sample: Employee[] = [\n 6 |     { id: 11, name: 'Luke' },\n 7 |     { id: 38, name: 'Leia' },\n 8 |     { id: 9, name: 'Han' }\n 9 |   ];\n10 | \n11 |   function loadSample(): void {\n12 |     replaceEmployees(sample);\n13 |   }\n14 | \n15 |   function resetState(): void {\n16 |     resetEmployees();\n17 |   }\n18 | </script>\n19 | \n20 | <div>\n21 |   <div>\n22 |     {#if $employeeState.loading}\n23 |       <div>Loading...</div>\n24 |     {:else if $employeeState.error}\n25 |       <div>{$employeeState.error}</div>\n26 |     {:else}\n27 |       <textarea readonly>{JSON.stringify($employeeState.value, null, 2)}</textarea>\n28 |     {/if}\n29 |   </div>\n30 | \n31 |   <div>\n32 |     <button type=\"button\" on:click={loadSample}>Load Sample State</button>\n33 | \n34 |     <button type=\"button\" on:click={resetState}>Reset State</button>\n35 |   </div>\n36 | </div>"
  },
  {
    type: 'typescript',
    fileName: 'employee.model.ts',
    source:
      'export interface Employee {\n  id: number;\n  name: string;\n}\n\nexport interface EmployeeState {\n  loading: boolean;\n  value: Employee[];\n  error: string | null;\n}',
    numberedSource:
      ' 1 | export interface Employee {\n 2 |   id: number;\n 3 |   name: string;\n 4 | }\n 5 | \n 6 | export interface EmployeeState {\n 7 |   loading: boolean;\n 8 |   value: Employee[];\n 9 |   error: string | null;\n10 | }'
  }
] as const satisfies ReadonlyArray<{
  readonly type:
    'typescript' | 'html' | 'svelte' | 'vue' | 'scss' | 'json' | 'markdown';
  readonly fileName: string;
  readonly source: string;
  readonly numberedSource: string;
}>;
