// AUTO-GENERATED – DO NOT EDIT
export const p433Snapshot = [
  {
    id: 'id-removed',
    cell: 'partial-tab-sync',
    behaviorKey: 'vault-feature-cell',
    name: 'lifecycle:start:initialized',
    timestamp: 'ts-removed',
    monotonicTimestamp: 'mts-removed',
    type: 'lifecycle',
    boundary: 'start'
  },
  {
    id: 'id-removed',
    cell: 'partial-tab-sync',
    behaviorKey: 'partial-tab-sync::license',
    name: 'lifecycle:notification:license-attempt',
    timestamp: 'ts-removed',
    monotonicTimestamp: 'mts-removed',
    type: 'lifecycle',
    boundary: 'notification'
  },
  {
    id: 'id-removed',
    cell: 'partial-tab-sync',
    behaviorKey: 'vault-conductor',
    name: 'conductor:start:attempt',
    timestamp: 'ts-removed',
    monotonicTimestamp: 'mts-removed',
    type: 'conductor',
    boundary: 'start',
    traceId: 'trace-id-removed'
  },
  {
    id: 'id-removed',
    cell: 'partial-tab-sync',
    behaviorKey: 'vault-feature-cell',
    name: 'lifecycle:end:initialized',
    timestamp: 'ts-removed',
    monotonicTimestamp: 'mts-removed',
    type: 'lifecycle',
    boundary: 'end'
  },
  {
    id: 'id-removed',
    cell: 'partial-tab-sync',
    behaviorKey: 'partial-tab-sync::license',
    name: 'lifecycle:notification:license-approved',
    timestamp: 'ts-removed',
    monotonicTimestamp: 'mts-removed',
    type: 'lifecycle',
    boundary: 'notification'
  },
  {
    id: 'id-removed',
    cell: 'partial-tab-sync',
    behaviorKey: 'vault-conductor',
    name: 'controller:start:attempt',
    timestamp: 'ts-removed',
    monotonicTimestamp: 'mts-removed',
    type: 'controller',
    boundary: 'start',
    traceId: 'trace-id-removed'
  },
  {
    id: 'id-removed',
    cell: 'partial-tab-sync',
    behaviorKey: 'vault-conductor',
    name: 'controller:start:vote',
    timestamp: 'ts-removed',
    monotonicTimestamp: 'mts-removed',
    type: 'controller',
    boundary: 'start',
    traceId: 'trace-id-removed'
  },
  {
    id: 'id-removed',
    cell: 'partial-tab-sync',
    behaviorKey: 'SDUX::Controller::Policy::CoreAbstain',
    name: 'controller:start:vote',
    timestamp: 'ts-removed',
    monotonicTimestamp: 'mts-removed',
    type: 'controller',
    boundary: 'start',
    traceId: 'trace-id-removed'
  },
  {
    id: 'id-removed',
    cell: 'partial-tab-sync',
    behaviorKey: 'SDUX::Controller::Policy::CoreLicense',
    name: 'controller:start:vote',
    timestamp: 'ts-removed',
    monotonicTimestamp: 'mts-removed',
    type: 'controller',
    boundary: 'start',
    traceId: 'trace-id-removed'
  },
  {
    id: 'id-removed',
    cell: 'partial-tab-sync',
    behaviorKey: 'SDUX::Controller::Policy::CoreError',
    name: 'controller:start:vote',
    timestamp: 'ts-removed',
    monotonicTimestamp: 'mts-removed',
    type: 'controller',
    boundary: 'start',
    traceId: 'trace-id-removed'
  },
  {
    id: 'id-removed',
    cell: 'partial-tab-sync',
    behaviorKey: 'SDUX::Controller::Policy::TabSync',
    name: 'controller:start:vote',
    timestamp: 'ts-removed',
    monotonicTimestamp: 'mts-removed',
    type: 'controller',
    boundary: 'start',
    traceId: 'trace-id-removed'
  },
  {
    id: 'id-removed',
    cell: 'partial-tab-sync',
    behaviorKey: 'SDUX::Controller::Policy::CoreAbstain',
    name: 'controller:end:vote',
    timestamp: 'ts-removed',
    monotonicTimestamp: 'mts-removed',
    type: 'controller',
    boundary: 'end',
    traceId: 'trace-id-removed'
  },
  {
    id: 'id-removed',
    cell: 'partial-tab-sync',
    behaviorKey: 'SDUX::Controller::Policy::CoreLicense',
    name: 'controller:end:vote',
    timestamp: 'ts-removed',
    monotonicTimestamp: 'mts-removed',
    type: 'controller',
    boundary: 'end',
    traceId: 'trace-id-removed'
  },
  {
    id: 'id-removed',
    cell: 'partial-tab-sync',
    behaviorKey: 'SDUX::Controller::Policy::CoreError',
    name: 'controller:end:vote',
    timestamp: 'ts-removed',
    monotonicTimestamp: 'mts-removed',
    type: 'controller',
    boundary: 'end',
    traceId: 'trace-id-removed'
  },
  {
    id: 'id-removed',
    cell: 'partial-tab-sync',
    behaviorKey: 'SDUX::Controller::Policy::TabSync',
    name: 'controller:end:vote',
    timestamp: 'ts-removed',
    monotonicTimestamp: 'mts-removed',
    type: 'controller',
    boundary: 'end',
    traceId: 'trace-id-removed'
  },
  {
    id: 'id-removed',
    cell: 'partial-tab-sync',
    behaviorKey: 'vault-conductor',
    name: 'controller:end:vote',
    timestamp: 'ts-removed',
    monotonicTimestamp: 'mts-removed',
    type: 'controller',
    boundary: 'end',
    traceId: 'trace-id-removed'
  },
  {
    id: 'id-removed',
    cell: 'partial-tab-sync',
    behaviorKey: 'vault-conductor',
    name: 'controller:end:attempt',
    timestamp: 'ts-removed',
    monotonicTimestamp: 'mts-removed',
    type: 'controller',
    boundary: 'end',
    traceId: 'trace-id-removed'
  },
  {
    id: 'id-removed',
    cell: 'partial-tab-sync',
    behaviorKey: 'decision-engine',
    name: 'lifecycle:notification:success',
    timestamp: 'ts-removed',
    monotonicTimestamp: 'mts-removed',
    type: 'lifecycle',
    boundary: 'notification',
    traceId: 'trace-id-removed'
  },
  {
    id: 'id-removed',
    cell: 'partial-tab-sync',
    behaviorKey: 'vault-conductor',
    name: 'conductor:end:attempt',
    timestamp: 'ts-removed',
    monotonicTimestamp: 'mts-removed',
    type: 'conductor',
    boundary: 'end',
    traceId: 'trace-id-removed'
  },
  {
    id: 'id-removed',
    cell: 'partial-tab-sync',
    behaviorKey: 'decision-engine',
    name: 'lifecycle:notification:finalize',
    timestamp: 'ts-removed',
    monotonicTimestamp: 'mts-removed',
    type: 'lifecycle',
    boundary: 'notification',
    traceId: 'trace-id-removed'
  },
  {
    id: 'id-removed',
    cell: 'partial-tab-sync',
    behaviorKey: 'vault-feature-cell',
    name: 'lifecycle:start:initialized',
    timestamp: 'ts-removed',
    monotonicTimestamp: 'mts-removed',
    type: 'lifecycle',
    boundary: 'start'
  },
  {
    id: 'id-removed',
    cell: 'partial-tab-sync',
    behaviorKey: 'partial-tab-sync::license',
    name: 'lifecycle:notification:license-attempt',
    timestamp: 'ts-removed',
    monotonicTimestamp: 'mts-removed',
    type: 'lifecycle',
    boundary: 'notification'
  },
  {
    id: 'id-removed',
    cell: 'partial-tab-sync',
    behaviorKey: 'vault-conductor',
    name: 'conductor:start:attempt',
    timestamp: 'ts-removed',
    monotonicTimestamp: 'mts-removed',
    type: 'conductor',
    boundary: 'start',
    traceId: 'trace-id-removed'
  },
  {
    id: 'id-removed',
    cell: 'partial-tab-sync',
    behaviorKey: 'vault-feature-cell',
    name: 'lifecycle:end:initialized',
    timestamp: 'ts-removed',
    monotonicTimestamp: 'mts-removed',
    type: 'lifecycle',
    boundary: 'end'
  },
  {
    id: 'id-removed',
    cell: 'partial-tab-sync',
    behaviorKey: 'partial-tab-sync::license',
    name: 'lifecycle:notification:license-approved',
    timestamp: 'ts-removed',
    monotonicTimestamp: 'mts-removed',
    type: 'lifecycle',
    boundary: 'notification'
  },
  {
    id: 'id-removed',
    cell: 'partial-tab-sync',
    behaviorKey: 'vault-conductor',
    name: 'controller:start:attempt',
    timestamp: 'ts-removed',
    monotonicTimestamp: 'mts-removed',
    type: 'controller',
    boundary: 'start',
    traceId: 'trace-id-removed'
  },
  {
    id: 'id-removed',
    cell: 'partial-tab-sync',
    behaviorKey: 'vault-conductor',
    name: 'controller:start:vote',
    timestamp: 'ts-removed',
    monotonicTimestamp: 'mts-removed',
    type: 'controller',
    boundary: 'start',
    traceId: 'trace-id-removed'
  },
  {
    id: 'id-removed',
    cell: 'partial-tab-sync',
    behaviorKey: 'SDUX::Controller::Policy::CoreAbstain',
    name: 'controller:start:vote',
    timestamp: 'ts-removed',
    monotonicTimestamp: 'mts-removed',
    type: 'controller',
    boundary: 'start',
    traceId: 'trace-id-removed'
  },
  {
    id: 'id-removed',
    cell: 'partial-tab-sync',
    behaviorKey: 'SDUX::Controller::Policy::CoreLicense',
    name: 'controller:start:vote',
    timestamp: 'ts-removed',
    monotonicTimestamp: 'mts-removed',
    type: 'controller',
    boundary: 'start',
    traceId: 'trace-id-removed'
  },
  {
    id: 'id-removed',
    cell: 'partial-tab-sync',
    behaviorKey: 'SDUX::Controller::Policy::CoreError',
    name: 'controller:start:vote',
    timestamp: 'ts-removed',
    monotonicTimestamp: 'mts-removed',
    type: 'controller',
    boundary: 'start',
    traceId: 'trace-id-removed'
  },
  {
    id: 'id-removed',
    cell: 'partial-tab-sync',
    behaviorKey: 'SDUX::Controller::Policy::TabSync',
    name: 'controller:start:vote',
    timestamp: 'ts-removed',
    monotonicTimestamp: 'mts-removed',
    type: 'controller',
    boundary: 'start',
    traceId: 'trace-id-removed'
  },
  {
    id: 'id-removed',
    cell: 'partial-tab-sync',
    behaviorKey: 'SDUX::Controller::Policy::CoreAbstain',
    name: 'controller:end:vote',
    timestamp: 'ts-removed',
    monotonicTimestamp: 'mts-removed',
    type: 'controller',
    boundary: 'end',
    traceId: 'trace-id-removed'
  },
  {
    id: 'id-removed',
    cell: 'partial-tab-sync',
    behaviorKey: 'SDUX::Controller::Policy::CoreLicense',
    name: 'controller:end:vote',
    timestamp: 'ts-removed',
    monotonicTimestamp: 'mts-removed',
    type: 'controller',
    boundary: 'end',
    traceId: 'trace-id-removed'
  },
  {
    id: 'id-removed',
    cell: 'partial-tab-sync',
    behaviorKey: 'SDUX::Controller::Policy::CoreError',
    name: 'controller:end:vote',
    timestamp: 'ts-removed',
    monotonicTimestamp: 'mts-removed',
    type: 'controller',
    boundary: 'end',
    traceId: 'trace-id-removed'
  },
  {
    id: 'id-removed',
    cell: 'partial-tab-sync',
    behaviorKey: 'SDUX::Controller::Policy::TabSync',
    name: 'controller:end:vote',
    timestamp: 'ts-removed',
    monotonicTimestamp: 'mts-removed',
    type: 'controller',
    boundary: 'end',
    traceId: 'trace-id-removed'
  },
  {
    id: 'id-removed',
    cell: 'partial-tab-sync',
    behaviorKey: 'vault-conductor',
    name: 'controller:end:vote',
    timestamp: 'ts-removed',
    monotonicTimestamp: 'mts-removed',
    type: 'controller',
    boundary: 'end',
    traceId: 'trace-id-removed'
  },
  {
    id: 'id-removed',
    cell: 'partial-tab-sync',
    behaviorKey: 'vault-conductor',
    name: 'controller:end:attempt',
    timestamp: 'ts-removed',
    monotonicTimestamp: 'mts-removed',
    type: 'controller',
    boundary: 'end',
    traceId: 'trace-id-removed'
  },
  {
    id: 'id-removed',
    cell: 'partial-tab-sync',
    behaviorKey: 'decision-engine',
    name: 'lifecycle:notification:success',
    timestamp: 'ts-removed',
    monotonicTimestamp: 'mts-removed',
    type: 'lifecycle',
    boundary: 'notification',
    traceId: 'trace-id-removed'
  },
  {
    id: 'id-removed',
    cell: 'partial-tab-sync',
    behaviorKey: 'vault-conductor',
    name: 'conductor:end:attempt',
    timestamp: 'ts-removed',
    monotonicTimestamp: 'mts-removed',
    type: 'conductor',
    boundary: 'end',
    traceId: 'trace-id-removed'
  },
  {
    id: 'id-removed',
    cell: 'partial-tab-sync',
    behaviorKey: 'decision-engine',
    name: 'lifecycle:notification:finalize',
    timestamp: 'ts-removed',
    monotonicTimestamp: 'mts-removed',
    type: 'lifecycle',
    boundary: 'notification',
    traceId: 'trace-id-removed'
  }
];
