// --- AI Model File Path (DO NOT DELETE) ---
// FilePath: tools > documentation > link-generator > link-generator.class.mjs
// Updated: 2026-03-24 12:50
//	 Generated by pathcomment [tab] (see .vscode/typescript.code-snippets) or
//	 cmd+alt+j (see .vscode/keybindings.json)
// --- END AI MODEL FILE PATH ---

import fs from 'node:fs';
import path from 'node:path';
import { setSafeNamePrefix } from '../../utils/get-safe-name.util.mjs';
import { buildLink } from '../../utils/links/build-link.util.mjs';

export class DocumentationLinkGenerator {
  constructor({ typeIndexPath, sourceDirs }) {
    this.typeIndexPath = typeIndexPath;
    this.sourceDirs = sourceDirs;
    this.symbolMap = new Map();
  }

  // Symbols that should ONLY be linked in identifier-like contexts
  excludedSymbols = new Set([
    'Vault'
    // add more explicitly if needed
    // 'State',
    // 'Controller',
  ]);

  run() {
    this.loadIndex();
    this.walkSources();
    console.info('✔ Documentation linking complete');
  }

  loadIndex() {
    setSafeNamePrefix('');
    const raw = fs.readFileSync(this.typeIndexPath, 'utf8');
    const index = JSON.parse(raw);

    for (const kind of Object.values(index)) {
      for (const [symbol, entry] of Object.entries(kind)) {
        if (!entry.docLink) continue;
        if (this.excludedSymbols.has(symbol)) continue; // ⬅️ HARD STOP

        const url = buildLink(entry);
        this.symbolMap.set(symbol, url);
      }
    }

    // Longest-first prevents partial matches
    this.symbols = [...this.symbolMap.keys()].sort(
      (a, b) => b.length - a.length
    );
  }

  walkSources() {
    for (const dir of this.sourceDirs) {
      this.walk(dir);
    }
  }

  walk(dir) {
    for (const file of fs.readdirSync(dir)) {
      const full = path.join(dir, file);
      const stat = fs.statSync(full);

      if (stat.isDirectory()) {
        this.walk(full);
      } else if (this.isTargetFile(file)) {
        this.processFile(full);
      }
    }
  }

  isTargetFile(file) {
    if (file.endsWith('.spec.ts')) return false;
    return (
      file.endsWith('.html') || file.endsWith('.ts') || file.endsWith('.md')
    );
  }

  processFile(filePath) {
    console.info(`Processing File: ${filePath}`);

    const AUTO_MARKER = '<!-- AUTO-GENERATED DOCUMENTATION LINKS -->';

    const original = fs.readFileSync(filePath, 'utf8');

    // Remove existing auto-generated marker (if present)
    const withoutMarker = original.startsWith(AUTO_MARKER)
      ? original.slice(AUTO_MARKER.length).replace(/^\s*\n/, '')
      : original;

    const updated = this.linkContent(withoutMarker);

    if (updated !== withoutMarker) {
      let output = updated;

      // Re-add marker exactly once for HTML files
      if (filePath.endsWith('.html')) {
        output = `${AUTO_MARKER}\n${updated}`;
      }

      fs.writeFileSync(filePath, output, 'utf8');
      console.info('\tLinked');
    } else {
      console.info('\tIgnored');
    }
  }

  linkContent(content) {
    const hardBlocks = [];
    const softBlocks = [];

    // 1️⃣ Protect HARD blocks (pre, code, script, style)
    let result = content.replace(
      /<(sdux-multi-framework-example|sdux-example-viewer-tab|sdux-diagram|h3|h4|pre|code|script|style)\b[\s\S]*?<\/\1\s*>/gi,
      (match) => {
        const key = `__HARD_${hardBlocks.length}__`;
        hardBlocks.push(match);
        return key;
      }
    );

    // 1a️⃣ Protect section-title divs (heading-like, should not be auto-linked)
    result = result.replace(
      /<div\s+class="section-title"[\s\S]*?<\/div\s*>/gi,
      (match) => {
        const key = `__HARD_${hardBlocks.length}__`;
        hardBlocks.push(match);
        return key;
      }
    );

    // 1b️⃣ Protect self-closing elements (sdux-diagram)
    result = result.replace(/<sdux-diagram\b[^>]*\/>/gi, (match) => {
      const key = `__HARD_${hardBlocks.length}__`;
      hardBlocks.push(match);
      return key;
    });

    // 2️⃣ Protect existing anchors (formatter-safe)
    result = result.replace(/<a\b[\s\S]*?>[\s\S]*?<\/a\s*>/gi, (match) => {
      const key = `__SOFT_${softBlocks.length}__`;
      softBlocks.push(match);
      return key;
    });

    // 2b️⃣ Protect HTML attribute values (aria-label, title, alt, [tooltip], etc.)
    result = result.replace(
      /(?:aria-label|aria-describedby|title|alt|\[tooltip\])="[^"]*"/gi,
      (match) => {
        const key = `__SOFT_${softBlocks.length}__`;
        softBlocks.push(match);
        return key;
      }
    );

    // 3️⃣ Apply symbol linking ONLY to unprotected content
    for (const symbol of this.symbols) {
      const url = this.symbolMap.get(symbol);
      const re = new RegExp(`\\b${symbol}\\b`, 'g');
      result = result.replace(re, `<a href="${url}">${symbol}</a>`);
    }

    // 4️⃣ Restore SOFT blocks (anchors)
    softBlocks.forEach((block, i) => {
      result = result.replace(`__SOFT_${i}__`, block);
    });

    // 5️⃣ Restore HARD blocks LAST (never touched)
    hardBlocks.forEach((block, i) => {
      result = result.replace(`__HARD_${i}__`, block);
    });

    return result;
  }
}
