/**
 * AUTO-GENERATED — do not edit manually.
 * Generated by: tools/sdux-comparison/sdux-comparison.mjs
 */
export const REACT_REDUX_OUTPUT = [
  {
    type: 'typescript',
    fileName: 'main.tsx',
    source:
      "import { StrictMode } from 'react';\nimport { createRoot } from 'react-dom/client';\nimport { Provider } from 'react-redux';\nimport { ExampleView } from './ExampleView';\nimport { store } from './store';\n\ncreateRoot(document.getElementById('root')!).render(\n  <StrictMode>\n    <Provider store={store}>\n      <ExampleView />\n    </Provider>\n  </StrictMode>\n);",
    numberedSource:
      " 1 | import { StrictMode } from 'react';\n 2 | import { createRoot } from 'react-dom/client';\n 3 | import { Provider } from 'react-redux';\n 4 | import { ExampleView } from './ExampleView';\n 5 | import { store } from './store';\n 6 | \n 7 | createRoot(document.getElementById('root')!).render(\n 8 |   <StrictMode>\n 9 |     <Provider store={store}>\n10 |       <ExampleView />\n11 |     </Provider>\n12 |   </StrictMode>\n13 | );"
  },
  {
    type: 'typescript',
    fileName: 'useEmployeeFacade.ts',
    source:
      "import { useDispatch, useSelector } from 'react-redux';\nimport { AppDispatch, RootState } from './store';\nimport { EmployeeActions } from './employee.actions';\nimport { Employee } from './employee.model';\nimport {\n  selectEmployees,\n  selectEmployeesError,\n  selectEmployeesLoading\n} from './employee.selectors';\n\nconst useAppDispatch = useDispatch.withTypes<AppDispatch>();\nconst useAppSelector = useSelector.withTypes<RootState>();\n\nexport function useEmployeeFacade() {\n  const dispatch = useAppDispatch();\n  const value = useAppSelector(selectEmployees);\n  const loading = useAppSelector(selectEmployeesLoading);\n  const error = useAppSelector(selectEmployeesError);\n\n  return {\n    state: {\n      value,\n      loading,\n      error\n    },\n    replace(employees: Employee[]): void {\n      dispatch(EmployeeActions.replace(employees));\n    },\n    reset(): void {\n      dispatch(EmployeeActions.reset());\n    }\n  };\n}",
    numberedSource:
      " 1 | import { useDispatch, useSelector } from 'react-redux';\n 2 | import { AppDispatch, RootState } from './store';\n 3 | import { EmployeeActions } from './employee.actions';\n 4 | import { Employee } from './employee.model';\n 5 | import {\n 6 |   selectEmployees,\n 7 |   selectEmployeesError,\n 8 |   selectEmployeesLoading\n 9 | } from './employee.selectors';\n10 | \n11 | const useAppDispatch = useDispatch.withTypes<AppDispatch>();\n12 | const useAppSelector = useSelector.withTypes<RootState>();\n13 | \n14 | export function useEmployeeFacade() {\n15 |   const dispatch = useAppDispatch();\n16 |   const value = useAppSelector(selectEmployees);\n17 |   const loading = useAppSelector(selectEmployeesLoading);\n18 |   const error = useAppSelector(selectEmployeesError);\n19 | \n20 |   return {\n21 |     state: {\n22 |       value,\n23 |       loading,\n24 |       error\n25 |     },\n26 |     replace(employees: Employee[]): void {\n27 |       dispatch(EmployeeActions.replace(employees));\n28 |     },\n29 |     reset(): void {\n30 |       dispatch(EmployeeActions.reset());\n31 |     }\n32 |   };\n33 | }"
  },
  {
    type: 'typescript',
    fileName: 'ExampleView.tsx',
    source:
      "import { Employee } from './employee.model';\nimport { useEmployeeFacade } from './useEmployeeFacade';\n\nconst sample: Employee[] = [\n  { id: 11, name: 'Luke' },\n  { id: 38, name: 'Leia' },\n  { id: 9, name: 'Han' }\n];\n\nexport function ExampleView() {\n  const { state, replace, reset } = useEmployeeFacade();\n\n  const loadSample = () => {\n    replace(sample);\n  };\n\n  const resetState = () => {\n    reset();\n  };\n\n  return (\n    <div>\n      <div>\n        {state.loading ? (\n          <div>Loading...</div>\n        ) : state.error ? (\n          <div>{state.error}</div>\n        ) : (\n          <textarea readOnly value={JSON.stringify(state.value, null, 2)} />\n        )}\n      </div>\n\n      <div>\n        <button type=\"button\" onClick={loadSample}>\n          Load Sample State\n        </button>\n\n        <button type=\"button\" onClick={resetState}>\n          Reset State\n        </button>\n      </div>\n    </div>\n  );\n}",
    numberedSource:
      " 1 | import { Employee } from './employee.model';\n 2 | import { useEmployeeFacade } from './useEmployeeFacade';\n 3 | \n 4 | const sample: Employee[] = [\n 5 |   { id: 11, name: 'Luke' },\n 6 |   { id: 38, name: 'Leia' },\n 7 |   { id: 9, name: 'Han' }\n 8 | ];\n 9 | \n10 | export function ExampleView() {\n11 |   const { state, replace, reset } = useEmployeeFacade();\n12 | \n13 |   const loadSample = () => {\n14 |     replace(sample);\n15 |   };\n16 | \n17 |   const resetState = () => {\n18 |     reset();\n19 |   };\n20 | \n21 |   return (\n22 |     <div>\n23 |       <div>\n24 |         {state.loading ? (\n25 |           <div>Loading...</div>\n26 |         ) : state.error ? (\n27 |           <div>{state.error}</div>\n28 |         ) : (\n29 |           <textarea readOnly value={JSON.stringify(state.value, null, 2)} />\n30 |         )}\n31 |       </div>\n32 | \n33 |       <div>\n34 |         <button type=\"button\" onClick={loadSample}>\n35 |           Load Sample State\n36 |         </button>\n37 | \n38 |         <button type=\"button\" onClick={resetState}>\n39 |           Reset State\n40 |         </button>\n41 |       </div>\n42 |     </div>\n43 |   );\n44 | }"
  },
  {
    type: 'typescript',
    fileName: 'employee.model.ts',
    source: 'export interface Employee {\n  id: number;\n  name: string;\n}',
    numberedSource:
      '1 | export interface Employee {\n2 |   id: number;\n3 |   name: string;\n4 | }'
  },
  {
    type: 'typescript',
    fileName: 'employee.actions.ts',
    source:
      "import { createAction } from '@reduxjs/toolkit';\nimport { Employee } from './employee.model';\n\nexport const EmployeeActions = {\n  replace: createAction<Employee[]>('[Employees] Replace'),\n  reset: createAction('[Employees] Reset')\n} as const;",
    numberedSource:
      "1 | import { createAction } from '@reduxjs/toolkit';\n2 | import { Employee } from './employee.model';\n3 | \n4 | export const EmployeeActions = {\n5 |   replace: createAction<Employee[]>('[Employees] Replace'),\n6 |   reset: createAction('[Employees] Reset')\n7 | } as const;"
  },
  {
    type: 'typescript',
    fileName: 'employee.state.ts',
    source:
      "import { Employee } from './employee.model';\n\nexport interface EmployeeState {\n  loading: boolean;\n  value: Employee[];\n  error: string | null;\n}\n\nexport const initialEmployeeState: EmployeeState = {\n  loading: false,\n  value: [],\n  error: null\n};",
    numberedSource:
      " 1 | import { Employee } from './employee.model';\n 2 | \n 3 | export interface EmployeeState {\n 4 |   loading: boolean;\n 5 |   value: Employee[];\n 6 |   error: string | null;\n 7 | }\n 8 | \n 9 | export const initialEmployeeState: EmployeeState = {\n10 |   loading: false,\n11 |   value: [],\n12 |   error: null\n13 | };"
  },
  {
    type: 'typescript',
    fileName: 'employee.reducer.ts',
    source:
      "import { createReducer } from '@reduxjs/toolkit';\nimport { EmployeeActions } from './employee.actions';\nimport { Employee } from './employee.model';\nimport { EmployeeState, initialEmployeeState } from './employee.state';\n\nexport const employeeFeatureKey = 'employees';\n\nconst filterOddEmployees = (employees: Employee[]): Employee[] => {\n  return employees.filter((employee) => employee.id % 2 !== 0);\n};\n\nconst sortEmployeesByName = (employees: Employee[]): Employee[] => {\n  const sortedEmployees = [...employees];\n\n  sortedEmployees.sort((left, right) => left.name.localeCompare(right.name));\n\n  return sortedEmployees;\n};\n\nconst prepareEmployees = (employees: Employee[]): Employee[] => {\n  return sortEmployeesByName(filterOddEmployees(employees));\n};\n\nexport const employeeReducer = createReducer(initialEmployeeState, (builder) => {\n  builder\n    .addCase(EmployeeActions.replace, (state, action) => {\n      state.loading = false;\n      state.value = prepareEmployees(action.payload);\n      state.error = null;\n    })\n    .addCase(EmployeeActions.reset, () => initialEmployeeState);\n});",
    numberedSource:
      " 1 | import { createReducer } from '@reduxjs/toolkit';\n 2 | import { EmployeeActions } from './employee.actions';\n 3 | import { Employee } from './employee.model';\n 4 | import { EmployeeState, initialEmployeeState } from './employee.state';\n 5 | \n 6 | export const employeeFeatureKey = 'employees';\n 7 | \n 8 | const filterOddEmployees = (employees: Employee[]): Employee[] => {\n 9 |   return employees.filter((employee) => employee.id % 2 !== 0);\n10 | };\n11 | \n12 | const sortEmployeesByName = (employees: Employee[]): Employee[] => {\n13 |   const sortedEmployees = [...employees];\n14 | \n15 |   sortedEmployees.sort((left, right) => left.name.localeCompare(right.name));\n16 | \n17 |   return sortedEmployees;\n18 | };\n19 | \n20 | const prepareEmployees = (employees: Employee[]): Employee[] => {\n21 |   return sortEmployeesByName(filterOddEmployees(employees));\n22 | };\n23 | \n24 | export const employeeReducer = createReducer(initialEmployeeState, (builder) => {\n25 |   builder\n26 |     .addCase(EmployeeActions.replace, (state, action) => {\n27 |       state.loading = false;\n28 |       state.value = prepareEmployees(action.payload);\n29 |       state.error = null;\n30 |     })\n31 |     .addCase(EmployeeActions.reset, () => initialEmployeeState);\n32 | });"
  },
  {
    type: 'typescript',
    fileName: 'employee.selectors.ts',
    source:
      "import { RootState } from './store';\nimport { employeeFeatureKey } from './employee.reducer';\n\nexport const selectEmployeeState = (state: RootState) => {\n  return state[employeeFeatureKey];\n};\n\nexport const selectEmployees = (state: RootState) => {\n  return selectEmployeeState(state).value;\n};\n\nexport const selectEmployeesLoading = (state: RootState) => {\n  return selectEmployeeState(state).loading;\n};\n\nexport const selectEmployeesError = (state: RootState) => {\n  return selectEmployeeState(state).error;\n};",
    numberedSource:
      " 1 | import { RootState } from './store';\n 2 | import { employeeFeatureKey } from './employee.reducer';\n 3 | \n 4 | export const selectEmployeeState = (state: RootState) => {\n 5 |   return state[employeeFeatureKey];\n 6 | };\n 7 | \n 8 | export const selectEmployees = (state: RootState) => {\n 9 |   return selectEmployeeState(state).value;\n10 | };\n11 | \n12 | export const selectEmployeesLoading = (state: RootState) => {\n13 |   return selectEmployeeState(state).loading;\n14 | };\n15 | \n16 | export const selectEmployeesError = (state: RootState) => {\n17 |   return selectEmployeeState(state).error;\n18 | };"
  },
  {
    type: 'typescript',
    fileName: 'store.ts',
    source:
      "import { configureStore } from '@reduxjs/toolkit';\nimport { employeeFeatureKey, employeeReducer } from './employee.reducer';\n\nexport const store = configureStore({\n  reducer: {\n    [employeeFeatureKey]: employeeReducer\n  }\n});\n\nexport type RootState = ReturnType<typeof store.getState>;\nexport type AppDispatch = typeof store.dispatch;",
    numberedSource:
      " 1 | import { configureStore } from '@reduxjs/toolkit';\n 2 | import { employeeFeatureKey, employeeReducer } from './employee.reducer';\n 3 | \n 4 | export const store = configureStore({\n 5 |   reducer: {\n 6 |     [employeeFeatureKey]: employeeReducer\n 7 |   }\n 8 | });\n 9 | \n10 | export type RootState = ReturnType<typeof store.getState>;\n11 | export type AppDispatch = typeof store.dispatch;"
  }
] as const satisfies ReadonlyArray<{
  readonly type:
    'typescript' | 'html' | 'svelte' | 'vue' | 'scss' | 'json' | 'markdown';
  readonly fileName: string;
  readonly source: string;
  readonly numberedSource: string;
}>;
