/**
 * AUTO-GENERATED — do not edit manually.
 * Generated by: tools/sdux-comparison/sdux-comparison.mjs
 */
export const REACT_REDUX_OUTPUT = [
  {
    type: 'typescript',
    fileName: 'main.tsx',
    source:
      "import { StrictMode } from 'react';\nimport { createRoot } from 'react-dom/client';\nimport { Provider } from 'react-redux';\nimport { store } from './app.config';\nimport { ExampleComponent } from './example.component';\n\ncreateRoot(document.getElementById('root')!).render(\n  <StrictMode>\n    <Provider store={store}>\n      <ExampleComponent />\n    </Provider>\n  </StrictMode>\n);",
    numberedSource:
      " 1 | import { StrictMode } from 'react';\n 2 | import { createRoot } from 'react-dom/client';\n 3 | import { Provider } from 'react-redux';\n 4 | import { store } from './app.config';\n 5 | import { ExampleComponent } from './example.component';\n 6 | \n 7 | createRoot(document.getElementById('root')!).render(\n 8 |   <StrictMode>\n 9 |     <Provider store={store}>\n10 |       <ExampleComponent />\n11 |     </Provider>\n12 |   </StrictMode>\n13 | );"
  },
  {
    type: 'typescript',
    fileName: 'app.config.ts',
    source:
      "import { configureStore } from '@reduxjs/toolkit';\nimport { employeeFeatureKey, employeeReducer } from './employee.reducer';\n\nexport const store = configureStore({\n  reducer: {\n    [employeeFeatureKey]: employeeReducer\n  }\n});\n\nexport type RootState = ReturnType<typeof store.getState>;\nexport type AppDispatch = typeof store.dispatch;",
    numberedSource:
      " 1 | import { configureStore } from '@reduxjs/toolkit';\n 2 | import { employeeFeatureKey, employeeReducer } from './employee.reducer';\n 3 | \n 4 | export const store = configureStore({\n 5 |   reducer: {\n 6 |     [employeeFeatureKey]: employeeReducer\n 7 |   }\n 8 | });\n 9 | \n10 | export type RootState = ReturnType<typeof store.getState>;\n11 | export type AppDispatch = typeof store.dispatch;"
  },
  {
    type: 'typescript',
    fileName: 'employee.hook.ts',
    source:
      "import { useEffect } from 'react';\nimport { useDispatch, useSelector } from 'react-redux';\nimport { AppDispatch, RootState } from './app.config';\nimport { EmployeeActions } from './employee.actions';\nimport { Employee } from './employee.model';\nimport {\n  selectEmployees,\n  selectEmployeesError,\n  selectEmployeesLoading\n} from './employee.selectors';\n\nconst useAppDispatch = useDispatch.withTypes<AppDispatch>();\nconst useAppSelector = useSelector.withTypes<RootState>();\n\nexport function useEmployeeFacade() {\n  const dispatch = useAppDispatch();\n  const value = useAppSelector(selectEmployees);\n  const loading = useAppSelector(selectEmployeesLoading);\n  const error = useAppSelector(selectEmployeesError);\n\n  useEffect(() => {\n    dispatch(EmployeeActions.seed());\n  }, [dispatch]);\n\n  return {\n    state: {\n      value,\n      loading,\n      error\n    },\n    replace(employees: Employee[]): void {\n      dispatch(EmployeeActions.replace(employees));\n    },\n    reset(): void {\n      dispatch(EmployeeActions.reset());\n    }\n  };\n}",
    numberedSource:
      " 1 | import { useEffect } from 'react';\n 2 | import { useDispatch, useSelector } from 'react-redux';\n 3 | import { AppDispatch, RootState } from './app.config';\n 4 | import { EmployeeActions } from './employee.actions';\n 5 | import { Employee } from './employee.model';\n 6 | import {\n 7 |   selectEmployees,\n 8 |   selectEmployeesError,\n 9 |   selectEmployeesLoading\n10 | } from './employee.selectors';\n11 | \n12 | const useAppDispatch = useDispatch.withTypes<AppDispatch>();\n13 | const useAppSelector = useSelector.withTypes<RootState>();\n14 | \n15 | export function useEmployeeFacade() {\n16 |   const dispatch = useAppDispatch();\n17 |   const value = useAppSelector(selectEmployees);\n18 |   const loading = useAppSelector(selectEmployeesLoading);\n19 |   const error = useAppSelector(selectEmployeesError);\n20 | \n21 |   useEffect(() => {\n22 |     dispatch(EmployeeActions.seed());\n23 |   }, [dispatch]);\n24 | \n25 |   return {\n26 |     state: {\n27 |       value,\n28 |       loading,\n29 |       error\n30 |     },\n31 |     replace(employees: Employee[]): void {\n32 |       dispatch(EmployeeActions.replace(employees));\n33 |     },\n34 |     reset(): void {\n35 |       dispatch(EmployeeActions.reset());\n36 |     }\n37 |   };\n38 | }"
  },
  {
    type: 'typescript',
    fileName: 'example.component.tsx',
    source:
      "import { Employee } from './employee.model';\nimport { useEmployeeFacade } from './employee.hook';\n\nconst sample: Employee[] = [\n  { id: 11, name: 'Luke' },\n  { id: 38, name: 'Leia' },\n  { id: 9, name: 'Han' }\n];\n\nexport function ExampleComponent() {\n  const { state, replace, reset } = useEmployeeFacade();\n\n  const loadSample = () => {\n    replace(sample);\n  };\n\n  const resetState = () => {\n    reset();\n  };\n\n  return (\n    <div>\n      <div>\n        {state.loading ? (\n          <div>Loading...</div>\n        ) : state.error ? (\n          <div>{state.error}</div>\n        ) : (\n          <textarea readOnly value={JSON.stringify(state.value, null, 2)} />\n        )}\n      </div>\n\n      <div>\n        <button type=\"button\" onClick={loadSample}>\n          Load Sample State\n        </button>\n\n        <button type=\"button\" onClick={resetState}>\n          Reset State\n        </button>\n      </div>\n    </div>\n  );\n}",
    numberedSource:
      " 1 | import { Employee } from './employee.model';\n 2 | import { useEmployeeFacade } from './employee.hook';\n 3 | \n 4 | const sample: Employee[] = [\n 5 |   { id: 11, name: 'Luke' },\n 6 |   { id: 38, name: 'Leia' },\n 7 |   { id: 9, name: 'Han' }\n 8 | ];\n 9 | \n10 | export function ExampleComponent() {\n11 |   const { state, replace, reset } = useEmployeeFacade();\n12 | \n13 |   const loadSample = () => {\n14 |     replace(sample);\n15 |   };\n16 | \n17 |   const resetState = () => {\n18 |     reset();\n19 |   };\n20 | \n21 |   return (\n22 |     <div>\n23 |       <div>\n24 |         {state.loading ? (\n25 |           <div>Loading...</div>\n26 |         ) : state.error ? (\n27 |           <div>{state.error}</div>\n28 |         ) : (\n29 |           <textarea readOnly value={JSON.stringify(state.value, null, 2)} />\n30 |         )}\n31 |       </div>\n32 | \n33 |       <div>\n34 |         <button type=\"button\" onClick={loadSample}>\n35 |           Load Sample State\n36 |         </button>\n37 | \n38 |         <button type=\"button\" onClick={resetState}>\n39 |           Reset State\n40 |         </button>\n41 |       </div>\n42 |     </div>\n43 |   );\n44 | }"
  },
  {
    type: 'typescript',
    fileName: 'employee.model.ts',
    source: 'export interface Employee {\n  id: number;\n  name: string;\n}',
    numberedSource:
      '1 | export interface Employee {\n2 |   id: number;\n3 |   name: string;\n4 | }'
  },
  {
    type: 'typescript',
    fileName: 'employee.actions.ts',
    source:
      "import { createAction } from '@reduxjs/toolkit';\nimport { Employee } from './employee.model';\n\nexport const EmployeeActions = {\n  seed: createAction('[Employees] Seed'),\n  replace: createAction<Employee[]>('[Employees] Replace'),\n  reset: createAction('[Employees] Reset')\n} as const;",
    numberedSource:
      "1 | import { createAction } from '@reduxjs/toolkit';\n2 | import { Employee } from './employee.model';\n3 | \n4 | export const EmployeeActions = {\n5 |   seed: createAction('[Employees] Seed'),\n6 |   replace: createAction<Employee[]>('[Employees] Replace'),\n7 |   reset: createAction('[Employees] Reset')\n8 | } as const;"
  },
  {
    type: 'typescript',
    fileName: 'employee.state.ts',
    source:
      "import { Employee } from './employee.model';\n\nexport interface EmployeeState {\n  loading: boolean;\n  value: Employee[];\n  error: string | null;\n}\n\nexport const initialEmployeeState: EmployeeState = {\n  loading: false,\n  value: [],\n  error: null\n};",
    numberedSource:
      " 1 | import { Employee } from './employee.model';\n 2 | \n 3 | export interface EmployeeState {\n 4 |   loading: boolean;\n 5 |   value: Employee[];\n 6 |   error: string | null;\n 7 | }\n 8 | \n 9 | export const initialEmployeeState: EmployeeState = {\n10 |   loading: false,\n11 |   value: [],\n12 |   error: null\n13 | };"
  },
  {
    type: 'typescript',
    fileName: 'employee.reducer.ts',
    source:
      "import { createReducer } from '@reduxjs/toolkit';\nimport { EmployeeActions } from './employee.actions';\nimport { Employee } from './employee.model';\nimport { EmployeeState, initialEmployeeState } from './employee.state';\n\nexport const employeeFeatureKey = 'employees';\n\nconst seededEmployees = [\n  { id: 1, name: 'Ada' },\n  { id: 2, name: 'Brian' }\n];\n\nconst filterOddEmployees = (employees: Employee[]): Employee[] => {\n  return employees.filter((employee) => employee.id % 2 !== 0);\n};\n\nconst sortEmployeesByName = (employees: Employee[]): Employee[] => {\n  const sortedEmployees = [...employees];\n\n  sortedEmployees.sort((left, right) => left.name.localeCompare(right.name));\n\n  return sortedEmployees;\n};\n\nconst prepareEmployees = (employees: Employee[]): Employee[] => {\n  return sortEmployeesByName(filterOddEmployees(employees));\n};\n\nexport const employeeReducer = createReducer(initialEmployeeState, (builder) => {\n  builder\n    .addCase(EmployeeActions.seed, (state) => {\n      state.loading = false;\n      state.value = prepareEmployees(seededEmployees);\n      state.error = null;\n    })\n    .addCase(EmployeeActions.replace, (state, action) => {\n      state.loading = false;\n      state.value = prepareEmployees(action.payload);\n      state.error = null;\n    })\n    .addCase(EmployeeActions.reset, () => initialEmployeeState);\n});",
    numberedSource:
      " 1 | import { createReducer } from '@reduxjs/toolkit';\n 2 | import { EmployeeActions } from './employee.actions';\n 3 | import { Employee } from './employee.model';\n 4 | import { EmployeeState, initialEmployeeState } from './employee.state';\n 5 | \n 6 | export const employeeFeatureKey = 'employees';\n 7 | \n 8 | const seededEmployees = [\n 9 |   { id: 1, name: 'Ada' },\n10 |   { id: 2, name: 'Brian' }\n11 | ];\n12 | \n13 | const filterOddEmployees = (employees: Employee[]): Employee[] => {\n14 |   return employees.filter((employee) => employee.id % 2 !== 0);\n15 | };\n16 | \n17 | const sortEmployeesByName = (employees: Employee[]): Employee[] => {\n18 |   const sortedEmployees = [...employees];\n19 | \n20 |   sortedEmployees.sort((left, right) => left.name.localeCompare(right.name));\n21 | \n22 |   return sortedEmployees;\n23 | };\n24 | \n25 | const prepareEmployees = (employees: Employee[]): Employee[] => {\n26 |   return sortEmployeesByName(filterOddEmployees(employees));\n27 | };\n28 | \n29 | export const employeeReducer = createReducer(initialEmployeeState, (builder) => {\n30 |   builder\n31 |     .addCase(EmployeeActions.seed, (state) => {\n32 |       state.loading = false;\n33 |       state.value = prepareEmployees(seededEmployees);\n34 |       state.error = null;\n35 |     })\n36 |     .addCase(EmployeeActions.replace, (state, action) => {\n37 |       state.loading = false;\n38 |       state.value = prepareEmployees(action.payload);\n39 |       state.error = null;\n40 |     })\n41 |     .addCase(EmployeeActions.reset, () => initialEmployeeState);\n42 | });"
  },
  {
    type: 'typescript',
    fileName: 'employee.selectors.ts',
    source:
      "import { RootState } from './app.config';\nimport { employeeFeatureKey } from './employee.reducer';\n\nexport const selectEmployeeState = (state: RootState) => {\n  return state[employeeFeatureKey];\n};\n\nexport const selectEmployees = (state: RootState) => {\n  return selectEmployeeState(state).value;\n};\n\nexport const selectEmployeesLoading = (state: RootState) => {\n  return selectEmployeeState(state).loading;\n};\n\nexport const selectEmployeesError = (state: RootState) => {\n  return selectEmployeeState(state).error;\n};",
    numberedSource:
      " 1 | import { RootState } from './app.config';\n 2 | import { employeeFeatureKey } from './employee.reducer';\n 3 | \n 4 | export const selectEmployeeState = (state: RootState) => {\n 5 |   return state[employeeFeatureKey];\n 6 | };\n 7 | \n 8 | export const selectEmployees = (state: RootState) => {\n 9 |   return selectEmployeeState(state).value;\n10 | };\n11 | \n12 | export const selectEmployeesLoading = (state: RootState) => {\n13 |   return selectEmployeeState(state).loading;\n14 | };\n15 | \n16 | export const selectEmployeesError = (state: RootState) => {\n17 |   return selectEmployeeState(state).error;\n18 | };"
  }
] as const satisfies ReadonlyArray<{
  readonly type: 'typescript' | 'html' | 'scss' | 'json' | 'markdown';
  readonly fileName: string;
  readonly source: string;
  readonly numberedSource: string;
}>;
