// --- AI Model File Path (DO NOT DELETE) ---
// FilePath: tools > documentation > enterprise-docs > tests > build-enterprise-docs.spec.mjs
// Updated: 2026-03-24 13:03
//	 Generated by pathcomment [tab] (see .vscode/typescript.code-snippets) or
//	 cmd+alt+j (see .vscode/keybindings.json)
// --- END AI MODEL FILE PATH ---

import fs from 'node:fs';

import { ExecModule } from '../../../utils/exec-sync.util.mjs';
import { parseFilePath } from '../../../utils/testing/parse-file-path.helper.mjs';
import {
  ArchiveModule,
  EnterpriseDocsBuilder
} from '../build-enterprise-docs.class.mjs';

describe('CLI: enterprise-docs-builder', () => {
  let builder;

  const existsSyncCalls = [];
  const renameSyncCalls = [];
  const chmodSyncCalls = [];
  const rmSyncCalls = [];
  const mkdirSyncCalls = [];
  const readdirSyncCalls = [];
  const copyFileSyncCalls = [];
  const writeFileSyncCalls = [];
  const createWriteStreamCalls = [];

  const output = [];

  let archiveMock;

  beforeEach(() => {
    spyOn(console, 'info');
    existsSyncCalls.length = 0;
    renameSyncCalls.length = 0;
    chmodSyncCalls.length = 0;
    rmSyncCalls.length = 0;
    mkdirSyncCalls.length = 0;
    readdirSyncCalls.length = 0;
    copyFileSyncCalls.length = 0;
    writeFileSyncCalls.length = 0;
    createWriteStreamCalls.length = 0;
    output.length = 0;

    spyOn(fs, 'existsSync').and.callFake((file) => {
      existsSyncCalls.push(parseFilePath(file));
      return true;
    });

    spyOn(fs, 'renameSync').and.callFake((file) => {
      renameSyncCalls.push(parseFilePath(file));
      return true;
    });

    spyOn(fs, 'chmodSync').and.callFake((file) => {
      chmodSyncCalls.push(parseFilePath(file));
      return true;
    });

    spyOn(fs, 'rmSync').and.callFake((file) => {
      rmSyncCalls.push(parseFilePath(file));
    });

    spyOn(fs, 'mkdirSync').and.callFake((file) => {
      mkdirSyncCalls.push(parseFilePath(file));
    });

    spyOn(fs, 'readdirSync').and.callFake(() => {
      readdirSyncCalls.push(true);
      return [];
    });

    spyOn(fs, 'statSync').and.returnValue({
      isDirectory: () => false
    });

    spyOn(fs, 'copyFileSync').and.callFake((src, dest) => {
      copyFileSyncCalls.push([parseFilePath(src), parseFilePath(dest)]);
    });

    spyOn(fs, 'writeFileSync').and.callFake((file, data) => {
      writeFileSyncCalls.push(parseFilePath(file));
      output.push(data);
    });

    spyOn(fs, 'createWriteStream').and.callFake((file) => {
      createWriteStreamCalls.push(parseFilePath(file));
      return {
        on: (event, cb) => {
          if (event === 'close') cb();
        }
      };
    });

    spyOn(ExecModule, 'exec').and.callFake(() => {});

    archiveMock = {
      pipe: jasmine.createSpy('pipe'),
      directory: jasmine.createSpy('directory'),
      finalize: jasmine.createSpy('finalize')
    };

    spyOn(ArchiveModule, 'create').and.returnValue(archiveMock);

    builder = new EnterpriseDocsBuilder({
      root: '/project'
    });
  });

  it('should build enterprise documentation bundle', async () => {
    await builder.run();

    expect(existsSyncCalls)
      .withContext('existSyncCalls')
      .toEqual([
        'dist/enterprise-docs',
        'webapp/browser',
        'assets/diagrams',
        'assets/search-index',
        'project/documentation',
        'enterprise-docs/index.offline.html'
      ]);

    expect(renameSyncCalls)
      .withContext('renameSyncCalls')
      .toEqual(['enterprise-docs/index.offline.html']);

    expect(chmodSyncCalls)
      .withContext('existSyncCalls')
      .toEqual([
        'enterprise-docs/start-docs.command',
        'enterprise-docs/start-docs.sh'
      ]);

    expect(mkdirSyncCalls)
      .withContext('mkdirSyncCalls')
      .toEqual([
        'dist/enterprise-docs',
        'dist/enterprise-docs',
        'enterprise-docs/diagrams',
        'enterprise-docs/search-index',
        'enterprise-docs/reference'
      ]);

    expect(writeFileSyncCalls)
      .withContext('writeFileSyncCalls')
      .toEqual([
        'enterprise-docs/enterprise-docs.json',
        'enterprise-docs/start-docs.js',
        'enterprise-docs/start-docs.command',
        'enterprise-docs/start-docs.bat',
        'enterprise-docs/start-docs.sh',
        'enterprise-docs/README.md'
      ]);

    expect(createWriteStreamCalls.length).toBe(1);

    expect(archiveMock.pipe).toHaveBeenCalled();

    expect(archiveMock.directory).toHaveBeenCalled();

    expect(archiveMock.finalize).toHaveBeenCalled();

    expect(output.length).withContext('output').toBe(6);

    const manifest = JSON.parse(output[0]);

    expect(manifest.name).toBe('SDuX Enterprise Documentation');
    expect(manifest.version).toBe('1.0.0');
    expect(manifest.offline).toBeTrue();
    expect(typeof manifest.generated).toBe('string');
  });
});
