// --- AI Model File Path (DO NOT DELETE) ---
// FilePath: tools > utils > exec-sync.util.mjs
// Updated: 2026-03-24 13:05
//	 Generated by pathcomment [tab] (see .vscode/typescript.code-snippets) or
//	 cmd+alt+j (see .vscode/keybindings.json)
// --- END AI MODEL FILE PATH ---

import * as childProcess from 'node:child_process';

export const ExecModule = {
  exec(cmd, options = {}) {
    return childProcess.execSync(cmd, {
      stdio: 'inherit',
      ...options
    });
  }
};
