// AUTO-GENERATED – DO NOT EDIT
export const p273Snapshot = [
  {
    id: 'id-removed',
    cell: 'partial-cache',
    behaviorKey: 'vault-feature-cell',
    name: 'lifecycle:start:initialized',
    timestamp: 'ts-removed',
    monotonicTimestamp: 'mts-removed',
    type: 'lifecycle',
    boundary: 'start'
  },
  {
    id: 'id-removed',
    cell: 'partial-cache',
    behaviorKey: 'partial-cache::license',
    name: 'lifecycle:notification:license-attempt',
    timestamp: 'ts-removed',
    monotonicTimestamp: 'mts-removed',
    type: 'lifecycle',
    boundary: 'notification'
  },
  {
    id: 'id-removed',
    cell: 'partial-cache',
    behaviorKey: 'partial-cache::license',
    name: 'lifecycle:notification:license-approved',
    timestamp: 'ts-removed',
    monotonicTimestamp: 'mts-removed',
    type: 'lifecycle',
    boundary: 'notification'
  },
  {
    id: 'id-removed',
    cell: 'partial-cache',
    behaviorKey: 'vault-conductor',
    name: 'conductor:start:attempt',
    timestamp: 'ts-removed',
    monotonicTimestamp: 'mts-removed',
    type: 'conductor',
    boundary: 'start',
    traceId: 'trace-id-removed'
  },
  {
    id: 'id-removed',
    cell: 'partial-cache',
    behaviorKey: 'vault-conductor',
    name: 'controller:start:attempt',
    timestamp: 'ts-removed',
    monotonicTimestamp: 'mts-removed',
    type: 'controller',
    boundary: 'start',
    traceId: 'trace-id-removed'
  },
  {
    id: 'id-removed',
    cell: 'partial-cache',
    behaviorKey: 'vault-conductor',
    name: 'controller:start:vote',
    timestamp: 'ts-removed',
    monotonicTimestamp: 'mts-removed',
    type: 'controller',
    boundary: 'start',
    traceId: 'trace-id-removed'
  },
  {
    id: 'id-removed',
    cell: 'partial-cache',
    behaviorKey: 'SDUX::Controller::Policy::CoreAbstain',
    name: 'controller:start:vote',
    timestamp: 'ts-removed',
    monotonicTimestamp: 'mts-removed',
    type: 'controller',
    boundary: 'start',
    traceId: 'trace-id-removed'
  },
  {
    id: 'id-removed',
    cell: 'partial-cache',
    behaviorKey: 'SDUX::Controller::Policy::CoreLicense',
    name: 'controller:start:vote',
    timestamp: 'ts-removed',
    monotonicTimestamp: 'mts-removed',
    type: 'controller',
    boundary: 'start',
    traceId: 'trace-id-removed'
  },
  {
    id: 'id-removed',
    cell: 'partial-cache',
    behaviorKey: 'SDUX::Controller::Policy::CoreError',
    name: 'controller:start:vote',
    timestamp: 'ts-removed',
    monotonicTimestamp: 'mts-removed',
    type: 'controller',
    boundary: 'start',
    traceId: 'trace-id-removed'
  },
  {
    id: 'id-removed',
    cell: 'partial-cache',
    behaviorKey: 'SDUX::Controller::Policy::CoreAbstain',
    name: 'controller:end:vote',
    timestamp: 'ts-removed',
    monotonicTimestamp: 'mts-removed',
    type: 'controller',
    boundary: 'end',
    traceId: 'trace-id-removed'
  },
  {
    id: 'id-removed',
    cell: 'partial-cache',
    behaviorKey: 'SDUX::Controller::Policy::CoreLicense',
    name: 'controller:end:vote',
    timestamp: 'ts-removed',
    monotonicTimestamp: 'mts-removed',
    type: 'controller',
    boundary: 'end',
    traceId: 'trace-id-removed'
  },
  {
    id: 'id-removed',
    cell: 'partial-cache',
    behaviorKey: 'SDUX::Controller::Policy::CoreError',
    name: 'controller:end:vote',
    timestamp: 'ts-removed',
    monotonicTimestamp: 'mts-removed',
    type: 'controller',
    boundary: 'end',
    traceId: 'trace-id-removed'
  },
  {
    id: 'id-removed',
    cell: 'partial-cache',
    behaviorKey: 'vault-conductor',
    name: 'controller:end:vote',
    timestamp: 'ts-removed',
    monotonicTimestamp: 'mts-removed',
    type: 'controller',
    boundary: 'end',
    traceId: 'trace-id-removed'
  },
  {
    id: 'id-removed',
    cell: 'partial-cache',
    behaviorKey: 'vault-feature-cell',
    name: 'lifecycle:end:initialized',
    timestamp: 'ts-removed',
    monotonicTimestamp: 'mts-removed',
    type: 'lifecycle',
    boundary: 'end'
  },
  {
    id: 'id-removed',
    cell: 'partial-cache',
    behaviorKey: 'vault-conductor',
    name: 'controller:end:attempt',
    timestamp: 'ts-removed',
    monotonicTimestamp: 'mts-removed',
    type: 'controller',
    boundary: 'end',
    traceId: 'trace-id-removed'
  },
  {
    id: 'id-removed',
    cell: 'partial-cache',
    behaviorKey: 'vault-orchestrator',
    name: 'lifecycle:start:set-initial-value',
    timestamp: 'ts-removed',
    monotonicTimestamp: 'mts-removed',
    type: 'lifecycle',
    boundary: 'start',
    traceId: 'trace-id-removed'
  },
  {
    id: 'id-removed',
    cell: 'partial-cache',
    behaviorKey: 'vault-orchestrator',
    name: 'lifecycle:end:set-initial-value',
    timestamp: 'ts-removed',
    monotonicTimestamp: 'mts-removed',
    type: 'lifecycle',
    boundary: 'end',
    traceId: 'trace-id-removed'
  },
  {
    id: 'id-removed',
    cell: 'partial-cache',
    behaviorKey: 'vault-orchestrator',
    name: 'pipeline:candidate:pipeline-start',
    timestamp: 'ts-removed',
    monotonicTimestamp: 'mts-removed',
    type: 'pipeline',
    boundary: 'candidate',
    traceId: 'trace-id-removed'
  },
  {
    id: 'id-removed',
    cell: 'partial-cache',
    behaviorKey: 'vault-orchestrator',
    name: 'lifecycle:start:replace',
    timestamp: 'ts-removed',
    monotonicTimestamp: 'mts-removed',
    type: 'lifecycle',
    boundary: 'start',
    traceId: 'trace-id-removed'
  },
  {
    id: 'id-removed',
    cell: 'partial-cache',
    behaviorKey: 'SDUX::Behavior::Core::Value',
    name: 'stage:start:resolve',
    timestamp: 'ts-removed',
    monotonicTimestamp: 'mts-removed',
    type: 'stage',
    boundary: 'start',
    traceId: 'trace-id-removed'
  },
  {
    id: 'id-removed',
    cell: 'partial-cache',
    behaviorKey: 'vault-orchestrator',
    name: 'pipeline:candidate:resolve',
    timestamp: 'ts-removed',
    monotonicTimestamp: 'mts-removed',
    type: 'pipeline',
    boundary: 'candidate',
    traceId: 'trace-id-removed'
  },
  {
    id: 'id-removed',
    cell: 'partial-cache',
    behaviorKey: 'SDUX::Behavior::Core::Value',
    name: 'stage:end:resolve',
    timestamp: 'ts-removed',
    monotonicTimestamp: 'mts-removed',
    type: 'stage',
    boundary: 'end',
    traceId: 'trace-id-removed'
  },
  {
    id: 'id-removed',
    cell: 'partial-cache',
    behaviorKey: 'vault-orchestrator',
    name: 'lifecycle:end:replace',
    timestamp: 'ts-removed',
    monotonicTimestamp: 'mts-removed',
    type: 'lifecycle',
    boundary: 'end',
    traceId: 'trace-id-removed'
  },
  {
    id: 'id-removed',
    cell: 'partial-cache',
    behaviorKey: 'vault-orchestrator',
    name: 'stage:start:core-state',
    timestamp: 'ts-removed',
    monotonicTimestamp: 'mts-removed',
    type: 'stage',
    boundary: 'start',
    traceId: 'trace-id-removed'
  },
  {
    id: 'id-removed',
    cell: 'partial-cache',
    behaviorKey: 'vault-orchestrator',
    name: 'pipeline:candidate:core-state',
    timestamp: 'ts-removed',
    monotonicTimestamp: 'mts-removed',
    type: 'pipeline',
    boundary: 'candidate',
    traceId: 'trace-id-removed'
  },
  {
    id: 'id-removed',
    cell: 'partial-cache',
    behaviorKey: 'vault-orchestrator',
    name: 'stage:end:core-state',
    timestamp: 'ts-removed',
    monotonicTimestamp: 'mts-removed',
    type: 'stage',
    boundary: 'end',
    traceId: 'trace-id-removed'
  },
  {
    id: 'id-removed',
    cell: 'partial-cache',
    behaviorKey: 'decision-engine',
    name: 'lifecycle:notification:success',
    timestamp: 'ts-removed',
    monotonicTimestamp: 'mts-removed',
    type: 'lifecycle',
    boundary: 'notification',
    traceId: 'trace-id-removed'
  },
  {
    id: 'id-removed',
    cell: 'partial-cache',
    behaviorKey: 'vault-conductor',
    name: 'conductor:end:attempt',
    timestamp: 'ts-removed',
    monotonicTimestamp: 'mts-removed',
    type: 'conductor',
    boundary: 'end',
    traceId: 'trace-id-removed'
  },
  {
    id: 'id-removed',
    cell: 'partial-cache',
    behaviorKey: 'decision-engine',
    name: 'lifecycle:notification:finalize',
    timestamp: 'ts-removed',
    monotonicTimestamp: 'mts-removed',
    type: 'lifecycle',
    boundary: 'notification',
    traceId: 'trace-id-removed'
  },
  {
    id: 'id-removed',
    cell: 'partial-cache',
    behaviorKey: 'vault-orchestrator',
    name: 'stage:start:core-state',
    timestamp: 'ts-removed',
    monotonicTimestamp: 'mts-removed',
    type: 'stage',
    boundary: 'start',
    traceId: 'trace-id-removed'
  },
  {
    id: 'id-removed',
    cell: 'partial-cache',
    behaviorKey: 'vault-orchestrator',
    name: 'stage:end:core-state',
    timestamp: 'ts-removed',
    monotonicTimestamp: 'mts-removed',
    type: 'stage',
    boundary: 'end',
    traceId: 'trace-id-removed'
  },
  {
    id: 'id-removed',
    cell: 'partial-cache',
    behaviorKey: 'vault-conductor',
    name: 'conductor:start:attempt',
    timestamp: 'ts-removed',
    monotonicTimestamp: 'mts-removed',
    type: 'conductor',
    boundary: 'start',
    traceId: 'trace-id-removed'
  },
  {
    id: 'id-removed',
    cell: 'partial-cache',
    behaviorKey: 'vault-conductor',
    name: 'controller:start:attempt',
    timestamp: 'ts-removed',
    monotonicTimestamp: 'mts-removed',
    type: 'controller',
    boundary: 'start',
    traceId: 'trace-id-removed'
  },
  {
    id: 'id-removed',
    cell: 'partial-cache',
    behaviorKey: 'vault-conductor',
    name: 'controller:start:vote',
    timestamp: 'ts-removed',
    monotonicTimestamp: 'mts-removed',
    type: 'controller',
    boundary: 'start',
    traceId: 'trace-id-removed'
  },
  {
    id: 'id-removed',
    cell: 'partial-cache',
    behaviorKey: 'SDUX::Controller::Policy::CoreAbstain',
    name: 'controller:start:vote',
    timestamp: 'ts-removed',
    monotonicTimestamp: 'mts-removed',
    type: 'controller',
    boundary: 'start',
    traceId: 'trace-id-removed'
  },
  {
    id: 'id-removed',
    cell: 'partial-cache',
    behaviorKey: 'SDUX::Controller::Policy::CoreLicense',
    name: 'controller:start:vote',
    timestamp: 'ts-removed',
    monotonicTimestamp: 'mts-removed',
    type: 'controller',
    boundary: 'start',
    traceId: 'trace-id-removed'
  },
  {
    id: 'id-removed',
    cell: 'partial-cache',
    behaviorKey: 'SDUX::Controller::Policy::CoreError',
    name: 'controller:start:vote',
    timestamp: 'ts-removed',
    monotonicTimestamp: 'mts-removed',
    type: 'controller',
    boundary: 'start',
    traceId: 'trace-id-removed'
  },
  {
    id: 'id-removed',
    cell: 'partial-cache',
    behaviorKey: 'SDUX::Controller::Policy::CoreAbstain',
    name: 'controller:end:vote',
    timestamp: 'ts-removed',
    monotonicTimestamp: 'mts-removed',
    type: 'controller',
    boundary: 'end',
    traceId: 'trace-id-removed'
  },
  {
    id: 'id-removed',
    cell: 'partial-cache',
    behaviorKey: 'SDUX::Controller::Policy::CoreLicense',
    name: 'controller:end:vote',
    timestamp: 'ts-removed',
    monotonicTimestamp: 'mts-removed',
    type: 'controller',
    boundary: 'end',
    traceId: 'trace-id-removed'
  },
  {
    id: 'id-removed',
    cell: 'partial-cache',
    behaviorKey: 'SDUX::Controller::Policy::CoreError',
    name: 'controller:end:vote',
    timestamp: 'ts-removed',
    monotonicTimestamp: 'mts-removed',
    type: 'controller',
    boundary: 'end',
    traceId: 'trace-id-removed'
  },
  {
    id: 'id-removed',
    cell: 'partial-cache',
    behaviorKey: 'vault-conductor',
    name: 'controller:end:vote',
    timestamp: 'ts-removed',
    monotonicTimestamp: 'mts-removed',
    type: 'controller',
    boundary: 'end',
    traceId: 'trace-id-removed'
  },
  {
    id: 'id-removed',
    cell: 'partial-cache',
    behaviorKey: 'vault-conductor',
    name: 'conductor:start:attempt',
    timestamp: 'ts-removed',
    monotonicTimestamp: 'mts-removed',
    type: 'conductor',
    boundary: 'start',
    traceId: 'trace-id-removed'
  },
  {
    id: 'id-removed',
    cell: 'partial-cache',
    behaviorKey: 'vault-conductor',
    name: 'conductor:start:attempt',
    timestamp: 'ts-removed',
    monotonicTimestamp: 'mts-removed',
    type: 'conductor',
    boundary: 'start',
    traceId: 'trace-id-removed'
  },
  {
    id: 'id-removed',
    cell: 'partial-cache',
    behaviorKey: 'vault-conductor',
    name: 'conductor:start:attempt',
    timestamp: 'ts-removed',
    monotonicTimestamp: 'mts-removed',
    type: 'conductor',
    boundary: 'start',
    traceId: 'trace-id-removed'
  },
  {
    id: 'id-removed',
    cell: 'partial-cache',
    behaviorKey: 'vault-conductor',
    name: 'conductor:start:attempt',
    timestamp: 'ts-removed',
    monotonicTimestamp: 'mts-removed',
    type: 'conductor',
    boundary: 'start',
    traceId: 'trace-id-removed'
  },
  {
    id: 'id-removed',
    cell: 'partial-cache',
    behaviorKey: 'vault-conductor',
    name: 'conductor:start:attempt',
    timestamp: 'ts-removed',
    monotonicTimestamp: 'mts-removed',
    type: 'conductor',
    boundary: 'start',
    traceId: 'trace-id-removed'
  },
  {
    id: 'id-removed',
    cell: 'partial-cache',
    behaviorKey: 'vault-conductor',
    name: 'conductor:start:attempt',
    timestamp: 'ts-removed',
    monotonicTimestamp: 'mts-removed',
    type: 'conductor',
    boundary: 'start',
    traceId: 'trace-id-removed'
  },
  {
    id: 'id-removed',
    cell: 'partial-cache',
    behaviorKey: 'vault-conductor',
    name: 'conductor:start:attempt',
    timestamp: 'ts-removed',
    monotonicTimestamp: 'mts-removed',
    type: 'conductor',
    boundary: 'start',
    traceId: 'trace-id-removed'
  },
  {
    id: 'id-removed',
    cell: 'partial-cache',
    behaviorKey: 'vault-conductor',
    name: 'conductor:start:attempt',
    timestamp: 'ts-removed',
    monotonicTimestamp: 'mts-removed',
    type: 'conductor',
    boundary: 'start',
    traceId: 'trace-id-removed'
  },
  {
    id: 'id-removed',
    cell: 'partial-cache',
    behaviorKey: 'vault-conductor',
    name: 'controller:end:attempt',
    timestamp: 'ts-removed',
    monotonicTimestamp: 'mts-removed',
    type: 'controller',
    boundary: 'end',
    traceId: 'trace-id-removed'
  },
  {
    id: 'id-removed',
    cell: 'partial-cache',
    behaviorKey: 'vault-orchestrator',
    name: 'pipeline:candidate:pipeline-start',
    timestamp: 'ts-removed',
    monotonicTimestamp: 'mts-removed',
    type: 'pipeline',
    boundary: 'candidate',
    traceId: 'trace-id-removed'
  },
  {
    id: 'id-removed',
    cell: 'partial-cache',
    behaviorKey: 'vault-orchestrator',
    name: 'lifecycle:start:merge',
    timestamp: 'ts-removed',
    monotonicTimestamp: 'mts-removed',
    type: 'lifecycle',
    boundary: 'start',
    traceId: 'trace-id-removed'
  },
  {
    id: 'id-removed',
    cell: 'partial-cache',
    behaviorKey: 'SDUX::Behavior::Core::Promise',
    name: 'stage:start:resolve',
    timestamp: 'ts-removed',
    monotonicTimestamp: 'mts-removed',
    type: 'stage',
    boundary: 'start',
    traceId: 'trace-id-removed'
  },
  {
    id: 'id-removed',
    cell: 'partial-cache',
    behaviorKey: 'vault-orchestrator',
    name: 'pipeline:candidate:resolve',
    timestamp: 'ts-removed',
    monotonicTimestamp: 'mts-removed',
    type: 'pipeline',
    boundary: 'candidate',
    traceId: 'trace-id-removed'
  },
  {
    id: 'id-removed',
    cell: 'partial-cache',
    behaviorKey: 'SDUX::Behavior::Core::Promise',
    name: 'stage:end:resolve',
    timestamp: 'ts-removed',
    monotonicTimestamp: 'mts-removed',
    type: 'stage',
    boundary: 'end',
    traceId: 'trace-id-removed'
  },
  {
    id: 'id-removed',
    cell: 'partial-cache',
    behaviorKey: 'vault-orchestrator',
    name: 'stage:start:compute-merge',
    timestamp: 'ts-removed',
    monotonicTimestamp: 'mts-removed',
    type: 'stage',
    boundary: 'start',
    traceId: 'trace-id-removed'
  },
  {
    id: 'id-removed',
    cell: 'partial-cache',
    behaviorKey: 'vault-orchestrator',
    name: 'pipeline:candidate:compute-merge',
    timestamp: 'ts-removed',
    monotonicTimestamp: 'mts-removed',
    type: 'pipeline',
    boundary: 'candidate',
    traceId: 'trace-id-removed'
  },
  {
    id: 'id-removed',
    cell: 'partial-cache',
    behaviorKey: 'vault-orchestrator',
    name: 'stage:end:compute-merge',
    timestamp: 'ts-removed',
    monotonicTimestamp: 'mts-removed',
    type: 'stage',
    boundary: 'end',
    traceId: 'trace-id-removed'
  },
  {
    id: 'id-removed',
    cell: 'partial-cache',
    behaviorKey: 'vault-orchestrator',
    name: 'lifecycle:end:merge',
    timestamp: 'ts-removed',
    monotonicTimestamp: 'mts-removed',
    type: 'lifecycle',
    boundary: 'end',
    traceId: 'trace-id-removed'
  },
  {
    id: 'id-removed',
    cell: 'partial-cache',
    behaviorKey: 'vault-orchestrator',
    name: 'stage:start:core-state',
    timestamp: 'ts-removed',
    monotonicTimestamp: 'mts-removed',
    type: 'stage',
    boundary: 'start',
    traceId: 'trace-id-removed'
  },
  {
    id: 'id-removed',
    cell: 'partial-cache',
    behaviorKey: 'vault-orchestrator',
    name: 'pipeline:candidate:core-state',
    timestamp: 'ts-removed',
    monotonicTimestamp: 'mts-removed',
    type: 'pipeline',
    boundary: 'candidate',
    traceId: 'trace-id-removed'
  },
  {
    id: 'id-removed',
    cell: 'partial-cache',
    behaviorKey: 'vault-orchestrator',
    name: 'stage:end:core-state',
    timestamp: 'ts-removed',
    monotonicTimestamp: 'mts-removed',
    type: 'stage',
    boundary: 'end',
    traceId: 'trace-id-removed'
  },
  {
    id: 'id-removed',
    cell: 'partial-cache',
    behaviorKey: 'decision-engine',
    name: 'lifecycle:notification:success',
    timestamp: 'ts-removed',
    monotonicTimestamp: 'mts-removed',
    type: 'lifecycle',
    boundary: 'notification',
    traceId: 'trace-id-removed'
  },
  {
    id: 'id-removed',
    cell: 'partial-cache',
    behaviorKey: 'vault-conductor',
    name: 'conductor:end:attempt',
    timestamp: 'ts-removed',
    monotonicTimestamp: 'mts-removed',
    type: 'conductor',
    boundary: 'end',
    traceId: 'trace-id-removed'
  },
  {
    id: 'id-removed',
    cell: 'partial-cache',
    behaviorKey: 'decision-engine',
    name: 'lifecycle:notification:finalize',
    timestamp: 'ts-removed',
    monotonicTimestamp: 'mts-removed',
    type: 'lifecycle',
    boundary: 'notification',
    traceId: 'trace-id-removed'
  },
  {
    id: 'id-removed',
    cell: 'partial-cache',
    behaviorKey: 'vault-conductor',
    name: 'controller:start:attempt',
    timestamp: 'ts-removed',
    monotonicTimestamp: 'mts-removed',
    type: 'controller',
    boundary: 'start',
    traceId: 'trace-id-removed'
  },
  {
    id: 'id-removed',
    cell: 'partial-cache',
    behaviorKey: 'vault-conductor',
    name: 'controller:start:vote',
    timestamp: 'ts-removed',
    monotonicTimestamp: 'mts-removed',
    type: 'controller',
    boundary: 'start',
    traceId: 'trace-id-removed'
  },
  {
    id: 'id-removed',
    cell: 'partial-cache',
    behaviorKey: 'SDUX::Controller::Policy::CoreAbstain',
    name: 'controller:start:vote',
    timestamp: 'ts-removed',
    monotonicTimestamp: 'mts-removed',
    type: 'controller',
    boundary: 'start',
    traceId: 'trace-id-removed'
  },
  {
    id: 'id-removed',
    cell: 'partial-cache',
    behaviorKey: 'SDUX::Controller::Policy::CoreLicense',
    name: 'controller:start:vote',
    timestamp: 'ts-removed',
    monotonicTimestamp: 'mts-removed',
    type: 'controller',
    boundary: 'start',
    traceId: 'trace-id-removed'
  },
  {
    id: 'id-removed',
    cell: 'partial-cache',
    behaviorKey: 'SDUX::Controller::Policy::CoreError',
    name: 'controller:start:vote',
    timestamp: 'ts-removed',
    monotonicTimestamp: 'mts-removed',
    type: 'controller',
    boundary: 'start',
    traceId: 'trace-id-removed'
  },
  {
    id: 'id-removed',
    cell: 'partial-cache',
    behaviorKey: 'SDUX::Controller::Policy::CoreAbstain',
    name: 'controller:end:vote',
    timestamp: 'ts-removed',
    monotonicTimestamp: 'mts-removed',
    type: 'controller',
    boundary: 'end',
    traceId: 'trace-id-removed'
  },
  {
    id: 'id-removed',
    cell: 'partial-cache',
    behaviorKey: 'SDUX::Controller::Policy::CoreLicense',
    name: 'controller:end:vote',
    timestamp: 'ts-removed',
    monotonicTimestamp: 'mts-removed',
    type: 'controller',
    boundary: 'end',
    traceId: 'trace-id-removed'
  },
  {
    id: 'id-removed',
    cell: 'partial-cache',
    behaviorKey: 'SDUX::Controller::Policy::CoreError',
    name: 'controller:end:vote',
    timestamp: 'ts-removed',
    monotonicTimestamp: 'mts-removed',
    type: 'controller',
    boundary: 'end',
    traceId: 'trace-id-removed'
  },
  {
    id: 'id-removed',
    cell: 'partial-cache',
    behaviorKey: 'vault-conductor',
    name: 'controller:end:vote',
    timestamp: 'ts-removed',
    monotonicTimestamp: 'mts-removed',
    type: 'controller',
    boundary: 'end',
    traceId: 'trace-id-removed'
  },
  {
    id: 'id-removed',
    cell: 'partial-cache',
    behaviorKey: 'vault-conductor',
    name: 'controller:end:attempt',
    timestamp: 'ts-removed',
    monotonicTimestamp: 'mts-removed',
    type: 'controller',
    boundary: 'end',
    traceId: 'trace-id-removed'
  },
  {
    id: 'id-removed',
    cell: 'partial-cache',
    behaviorKey: 'vault-orchestrator',
    name: 'pipeline:candidate:pipeline-start',
    timestamp: 'ts-removed',
    monotonicTimestamp: 'mts-removed',
    type: 'pipeline',
    boundary: 'candidate',
    traceId: 'trace-id-removed'
  },
  {
    id: 'id-removed',
    cell: 'partial-cache',
    behaviorKey: 'vault-orchestrator',
    name: 'lifecycle:start:merge',
    timestamp: 'ts-removed',
    monotonicTimestamp: 'mts-removed',
    type: 'lifecycle',
    boundary: 'start',
    traceId: 'trace-id-removed'
  },
  {
    id: 'id-removed',
    cell: 'partial-cache',
    behaviorKey: 'SDUX::Behavior::Core::Promise',
    name: 'stage:start:resolve',
    timestamp: 'ts-removed',
    monotonicTimestamp: 'mts-removed',
    type: 'stage',
    boundary: 'start',
    traceId: 'trace-id-removed'
  },
  {
    id: 'id-removed',
    cell: 'partial-cache',
    behaviorKey: 'vault-orchestrator',
    name: 'pipeline:candidate:resolve',
    timestamp: 'ts-removed',
    monotonicTimestamp: 'mts-removed',
    type: 'pipeline',
    boundary: 'candidate',
    traceId: 'trace-id-removed'
  },
  {
    id: 'id-removed',
    cell: 'partial-cache',
    behaviorKey: 'SDUX::Behavior::Core::Promise',
    name: 'stage:end:resolve',
    timestamp: 'ts-removed',
    monotonicTimestamp: 'mts-removed',
    type: 'stage',
    boundary: 'end',
    traceId: 'trace-id-removed'
  },
  {
    id: 'id-removed',
    cell: 'partial-cache',
    behaviorKey: 'vault-orchestrator',
    name: 'stage:start:compute-merge',
    timestamp: 'ts-removed',
    monotonicTimestamp: 'mts-removed',
    type: 'stage',
    boundary: 'start',
    traceId: 'trace-id-removed'
  },
  {
    id: 'id-removed',
    cell: 'partial-cache',
    behaviorKey: 'vault-orchestrator',
    name: 'pipeline:candidate:compute-merge',
    timestamp: 'ts-removed',
    monotonicTimestamp: 'mts-removed',
    type: 'pipeline',
    boundary: 'candidate',
    traceId: 'trace-id-removed'
  },
  {
    id: 'id-removed',
    cell: 'partial-cache',
    behaviorKey: 'vault-orchestrator',
    name: 'stage:end:compute-merge',
    timestamp: 'ts-removed',
    monotonicTimestamp: 'mts-removed',
    type: 'stage',
    boundary: 'end',
    traceId: 'trace-id-removed'
  },
  {
    id: 'id-removed',
    cell: 'partial-cache',
    behaviorKey: 'vault-orchestrator',
    name: 'lifecycle:end:merge',
    timestamp: 'ts-removed',
    monotonicTimestamp: 'mts-removed',
    type: 'lifecycle',
    boundary: 'end',
    traceId: 'trace-id-removed'
  },
  {
    id: 'id-removed',
    cell: 'partial-cache',
    behaviorKey: 'vault-orchestrator',
    name: 'stage:start:core-state',
    timestamp: 'ts-removed',
    monotonicTimestamp: 'mts-removed',
    type: 'stage',
    boundary: 'start',
    traceId: 'trace-id-removed'
  },
  {
    id: 'id-removed',
    cell: 'partial-cache',
    behaviorKey: 'vault-orchestrator',
    name: 'pipeline:candidate:core-state',
    timestamp: 'ts-removed',
    monotonicTimestamp: 'mts-removed',
    type: 'pipeline',
    boundary: 'candidate',
    traceId: 'trace-id-removed'
  },
  {
    id: 'id-removed',
    cell: 'partial-cache',
    behaviorKey: 'vault-orchestrator',
    name: 'stage:end:core-state',
    timestamp: 'ts-removed',
    monotonicTimestamp: 'mts-removed',
    type: 'stage',
    boundary: 'end',
    traceId: 'trace-id-removed'
  },
  {
    id: 'id-removed',
    cell: 'partial-cache',
    behaviorKey: 'decision-engine',
    name: 'lifecycle:notification:success',
    timestamp: 'ts-removed',
    monotonicTimestamp: 'mts-removed',
    type: 'lifecycle',
    boundary: 'notification',
    traceId: 'trace-id-removed'
  },
  {
    id: 'id-removed',
    cell: 'partial-cache',
    behaviorKey: 'vault-conductor',
    name: 'conductor:end:attempt',
    timestamp: 'ts-removed',
    monotonicTimestamp: 'mts-removed',
    type: 'conductor',
    boundary: 'end',
    traceId: 'trace-id-removed'
  },
  {
    id: 'id-removed',
    cell: 'partial-cache',
    behaviorKey: 'decision-engine',
    name: 'lifecycle:notification:finalize',
    timestamp: 'ts-removed',
    monotonicTimestamp: 'mts-removed',
    type: 'lifecycle',
    boundary: 'notification',
    traceId: 'trace-id-removed'
  },
  {
    id: 'id-removed',
    cell: 'partial-cache',
    behaviorKey: 'vault-conductor',
    name: 'controller:start:attempt',
    timestamp: 'ts-removed',
    monotonicTimestamp: 'mts-removed',
    type: 'controller',
    boundary: 'start',
    traceId: 'trace-id-removed'
  },
  {
    id: 'id-removed',
    cell: 'partial-cache',
    behaviorKey: 'vault-conductor',
    name: 'controller:start:vote',
    timestamp: 'ts-removed',
    monotonicTimestamp: 'mts-removed',
    type: 'controller',
    boundary: 'start',
    traceId: 'trace-id-removed'
  },
  {
    id: 'id-removed',
    cell: 'partial-cache',
    behaviorKey: 'SDUX::Controller::Policy::CoreAbstain',
    name: 'controller:start:vote',
    timestamp: 'ts-removed',
    monotonicTimestamp: 'mts-removed',
    type: 'controller',
    boundary: 'start',
    traceId: 'trace-id-removed'
  },
  {
    id: 'id-removed',
    cell: 'partial-cache',
    behaviorKey: 'SDUX::Controller::Policy::CoreLicense',
    name: 'controller:start:vote',
    timestamp: 'ts-removed',
    monotonicTimestamp: 'mts-removed',
    type: 'controller',
    boundary: 'start',
    traceId: 'trace-id-removed'
  },
  {
    id: 'id-removed',
    cell: 'partial-cache',
    behaviorKey: 'SDUX::Controller::Policy::CoreError',
    name: 'controller:start:vote',
    timestamp: 'ts-removed',
    monotonicTimestamp: 'mts-removed',
    type: 'controller',
    boundary: 'start',
    traceId: 'trace-id-removed'
  },
  {
    id: 'id-removed',
    cell: 'partial-cache',
    behaviorKey: 'SDUX::Controller::Policy::CoreAbstain',
    name: 'controller:end:vote',
    timestamp: 'ts-removed',
    monotonicTimestamp: 'mts-removed',
    type: 'controller',
    boundary: 'end',
    traceId: 'trace-id-removed'
  },
  {
    id: 'id-removed',
    cell: 'partial-cache',
    behaviorKey: 'SDUX::Controller::Policy::CoreLicense',
    name: 'controller:end:vote',
    timestamp: 'ts-removed',
    monotonicTimestamp: 'mts-removed',
    type: 'controller',
    boundary: 'end',
    traceId: 'trace-id-removed'
  },
  {
    id: 'id-removed',
    cell: 'partial-cache',
    behaviorKey: 'SDUX::Controller::Policy::CoreError',
    name: 'controller:end:vote',
    timestamp: 'ts-removed',
    monotonicTimestamp: 'mts-removed',
    type: 'controller',
    boundary: 'end',
    traceId: 'trace-id-removed'
  },
  {
    id: 'id-removed',
    cell: 'partial-cache',
    behaviorKey: 'vault-conductor',
    name: 'controller:end:vote',
    timestamp: 'ts-removed',
    monotonicTimestamp: 'mts-removed',
    type: 'controller',
    boundary: 'end',
    traceId: 'trace-id-removed'
  },
  {
    id: 'id-removed',
    cell: 'partial-cache',
    behaviorKey: 'vault-conductor',
    name: 'controller:end:attempt',
    timestamp: 'ts-removed',
    monotonicTimestamp: 'mts-removed',
    type: 'controller',
    boundary: 'end',
    traceId: 'trace-id-removed'
  },
  {
    id: 'id-removed',
    cell: 'partial-cache',
    behaviorKey: 'vault-orchestrator',
    name: 'pipeline:candidate:pipeline-start',
    timestamp: 'ts-removed',
    monotonicTimestamp: 'mts-removed',
    type: 'pipeline',
    boundary: 'candidate',
    traceId: 'trace-id-removed'
  },
  {
    id: 'id-removed',
    cell: 'partial-cache',
    behaviorKey: 'vault-orchestrator',
    name: 'lifecycle:start:merge',
    timestamp: 'ts-removed',
    monotonicTimestamp: 'mts-removed',
    type: 'lifecycle',
    boundary: 'start',
    traceId: 'trace-id-removed'
  },
  {
    id: 'id-removed',
    cell: 'partial-cache',
    behaviorKey: 'SDUX::Behavior::Core::Promise',
    name: 'stage:start:resolve',
    timestamp: 'ts-removed',
    monotonicTimestamp: 'mts-removed',
    type: 'stage',
    boundary: 'start',
    traceId: 'trace-id-removed'
  },
  {
    id: 'id-removed',
    cell: 'partial-cache',
    behaviorKey: 'vault-orchestrator',
    name: 'pipeline:candidate:resolve',
    timestamp: 'ts-removed',
    monotonicTimestamp: 'mts-removed',
    type: 'pipeline',
    boundary: 'candidate',
    traceId: 'trace-id-removed'
  },
  {
    id: 'id-removed',
    cell: 'partial-cache',
    behaviorKey: 'SDUX::Behavior::Core::Promise',
    name: 'stage:end:resolve',
    timestamp: 'ts-removed',
    monotonicTimestamp: 'mts-removed',
    type: 'stage',
    boundary: 'end',
    traceId: 'trace-id-removed'
  },
  {
    id: 'id-removed',
    cell: 'partial-cache',
    behaviorKey: 'vault-orchestrator',
    name: 'stage:start:compute-merge',
    timestamp: 'ts-removed',
    monotonicTimestamp: 'mts-removed',
    type: 'stage',
    boundary: 'start',
    traceId: 'trace-id-removed'
  },
  {
    id: 'id-removed',
    cell: 'partial-cache',
    behaviorKey: 'vault-orchestrator',
    name: 'pipeline:candidate:compute-merge',
    timestamp: 'ts-removed',
    monotonicTimestamp: 'mts-removed',
    type: 'pipeline',
    boundary: 'candidate',
    traceId: 'trace-id-removed'
  },
  {
    id: 'id-removed',
    cell: 'partial-cache',
    behaviorKey: 'vault-orchestrator',
    name: 'stage:end:compute-merge',
    timestamp: 'ts-removed',
    monotonicTimestamp: 'mts-removed',
    type: 'stage',
    boundary: 'end',
    traceId: 'trace-id-removed'
  },
  {
    id: 'id-removed',
    cell: 'partial-cache',
    behaviorKey: 'vault-orchestrator',
    name: 'lifecycle:end:merge',
    timestamp: 'ts-removed',
    monotonicTimestamp: 'mts-removed',
    type: 'lifecycle',
    boundary: 'end',
    traceId: 'trace-id-removed'
  },
  {
    id: 'id-removed',
    cell: 'partial-cache',
    behaviorKey: 'vault-orchestrator',
    name: 'stage:start:core-state',
    timestamp: 'ts-removed',
    monotonicTimestamp: 'mts-removed',
    type: 'stage',
    boundary: 'start',
    traceId: 'trace-id-removed'
  },
  {
    id: 'id-removed',
    cell: 'partial-cache',
    behaviorKey: 'vault-orchestrator',
    name: 'pipeline:candidate:core-state',
    timestamp: 'ts-removed',
    monotonicTimestamp: 'mts-removed',
    type: 'pipeline',
    boundary: 'candidate',
    traceId: 'trace-id-removed'
  },
  {
    id: 'id-removed',
    cell: 'partial-cache',
    behaviorKey: 'vault-orchestrator',
    name: 'stage:end:core-state',
    timestamp: 'ts-removed',
    monotonicTimestamp: 'mts-removed',
    type: 'stage',
    boundary: 'end',
    traceId: 'trace-id-removed'
  },
  {
    id: 'id-removed',
    cell: 'partial-cache',
    behaviorKey: 'decision-engine',
    name: 'lifecycle:notification:success',
    timestamp: 'ts-removed',
    monotonicTimestamp: 'mts-removed',
    type: 'lifecycle',
    boundary: 'notification',
    traceId: 'trace-id-removed'
  },
  {
    id: 'id-removed',
    cell: 'partial-cache',
    behaviorKey: 'vault-conductor',
    name: 'conductor:end:attempt',
    timestamp: 'ts-removed',
    monotonicTimestamp: 'mts-removed',
    type: 'conductor',
    boundary: 'end',
    traceId: 'trace-id-removed'
  },
  {
    id: 'id-removed',
    cell: 'partial-cache',
    behaviorKey: 'decision-engine',
    name: 'lifecycle:notification:finalize',
    timestamp: 'ts-removed',
    monotonicTimestamp: 'mts-removed',
    type: 'lifecycle',
    boundary: 'notification',
    traceId: 'trace-id-removed'
  },
  {
    id: 'id-removed',
    cell: 'partial-cache',
    behaviorKey: 'vault-conductor',
    name: 'controller:start:attempt',
    timestamp: 'ts-removed',
    monotonicTimestamp: 'mts-removed',
    type: 'controller',
    boundary: 'start',
    traceId: 'trace-id-removed'
  },
  {
    id: 'id-removed',
    cell: 'partial-cache',
    behaviorKey: 'vault-conductor',
    name: 'controller:start:vote',
    timestamp: 'ts-removed',
    monotonicTimestamp: 'mts-removed',
    type: 'controller',
    boundary: 'start',
    traceId: 'trace-id-removed'
  },
  {
    id: 'id-removed',
    cell: 'partial-cache',
    behaviorKey: 'SDUX::Controller::Policy::CoreAbstain',
    name: 'controller:start:vote',
    timestamp: 'ts-removed',
    monotonicTimestamp: 'mts-removed',
    type: 'controller',
    boundary: 'start',
    traceId: 'trace-id-removed'
  },
  {
    id: 'id-removed',
    cell: 'partial-cache',
    behaviorKey: 'SDUX::Controller::Policy::CoreLicense',
    name: 'controller:start:vote',
    timestamp: 'ts-removed',
    monotonicTimestamp: 'mts-removed',
    type: 'controller',
    boundary: 'start',
    traceId: 'trace-id-removed'
  },
  {
    id: 'id-removed',
    cell: 'partial-cache',
    behaviorKey: 'SDUX::Controller::Policy::CoreError',
    name: 'controller:start:vote',
    timestamp: 'ts-removed',
    monotonicTimestamp: 'mts-removed',
    type: 'controller',
    boundary: 'start',
    traceId: 'trace-id-removed'
  },
  {
    id: 'id-removed',
    cell: 'partial-cache',
    behaviorKey: 'SDUX::Controller::Policy::CoreAbstain',
    name: 'controller:end:vote',
    timestamp: 'ts-removed',
    monotonicTimestamp: 'mts-removed',
    type: 'controller',
    boundary: 'end',
    traceId: 'trace-id-removed'
  },
  {
    id: 'id-removed',
    cell: 'partial-cache',
    behaviorKey: 'SDUX::Controller::Policy::CoreLicense',
    name: 'controller:end:vote',
    timestamp: 'ts-removed',
    monotonicTimestamp: 'mts-removed',
    type: 'controller',
    boundary: 'end',
    traceId: 'trace-id-removed'
  },
  {
    id: 'id-removed',
    cell: 'partial-cache',
    behaviorKey: 'SDUX::Controller::Policy::CoreError',
    name: 'controller:end:vote',
    timestamp: 'ts-removed',
    monotonicTimestamp: 'mts-removed',
    type: 'controller',
    boundary: 'end',
    traceId: 'trace-id-removed'
  },
  {
    id: 'id-removed',
    cell: 'partial-cache',
    behaviorKey: 'vault-conductor',
    name: 'controller:end:vote',
    timestamp: 'ts-removed',
    monotonicTimestamp: 'mts-removed',
    type: 'controller',
    boundary: 'end',
    traceId: 'trace-id-removed'
  },
  {
    id: 'id-removed',
    cell: 'partial-cache',
    behaviorKey: 'vault-conductor',
    name: 'controller:end:attempt',
    timestamp: 'ts-removed',
    monotonicTimestamp: 'mts-removed',
    type: 'controller',
    boundary: 'end',
    traceId: 'trace-id-removed'
  },
  {
    id: 'id-removed',
    cell: 'partial-cache',
    behaviorKey: 'vault-orchestrator',
    name: 'pipeline:candidate:pipeline-start',
    timestamp: 'ts-removed',
    monotonicTimestamp: 'mts-removed',
    type: 'pipeline',
    boundary: 'candidate',
    traceId: 'trace-id-removed'
  },
  {
    id: 'id-removed',
    cell: 'partial-cache',
    behaviorKey: 'vault-orchestrator',
    name: 'lifecycle:start:merge',
    timestamp: 'ts-removed',
    monotonicTimestamp: 'mts-removed',
    type: 'lifecycle',
    boundary: 'start',
    traceId: 'trace-id-removed'
  },
  {
    id: 'id-removed',
    cell: 'partial-cache',
    behaviorKey: 'SDUX::Behavior::Core::Promise',
    name: 'stage:start:resolve',
    timestamp: 'ts-removed',
    monotonicTimestamp: 'mts-removed',
    type: 'stage',
    boundary: 'start',
    traceId: 'trace-id-removed'
  },
  {
    id: 'id-removed',
    cell: 'partial-cache',
    behaviorKey: 'vault-orchestrator',
    name: 'pipeline:candidate:resolve',
    timestamp: 'ts-removed',
    monotonicTimestamp: 'mts-removed',
    type: 'pipeline',
    boundary: 'candidate',
    traceId: 'trace-id-removed'
  },
  {
    id: 'id-removed',
    cell: 'partial-cache',
    behaviorKey: 'SDUX::Behavior::Core::Promise',
    name: 'stage:end:resolve',
    timestamp: 'ts-removed',
    monotonicTimestamp: 'mts-removed',
    type: 'stage',
    boundary: 'end',
    traceId: 'trace-id-removed'
  },
  {
    id: 'id-removed',
    cell: 'partial-cache',
    behaviorKey: 'vault-orchestrator',
    name: 'stage:start:compute-merge',
    timestamp: 'ts-removed',
    monotonicTimestamp: 'mts-removed',
    type: 'stage',
    boundary: 'start',
    traceId: 'trace-id-removed'
  },
  {
    id: 'id-removed',
    cell: 'partial-cache',
    behaviorKey: 'vault-orchestrator',
    name: 'pipeline:candidate:compute-merge',
    timestamp: 'ts-removed',
    monotonicTimestamp: 'mts-removed',
    type: 'pipeline',
    boundary: 'candidate',
    traceId: 'trace-id-removed'
  },
  {
    id: 'id-removed',
    cell: 'partial-cache',
    behaviorKey: 'vault-orchestrator',
    name: 'stage:end:compute-merge',
    timestamp: 'ts-removed',
    monotonicTimestamp: 'mts-removed',
    type: 'stage',
    boundary: 'end',
    traceId: 'trace-id-removed'
  },
  {
    id: 'id-removed',
    cell: 'partial-cache',
    behaviorKey: 'vault-orchestrator',
    name: 'lifecycle:end:merge',
    timestamp: 'ts-removed',
    monotonicTimestamp: 'mts-removed',
    type: 'lifecycle',
    boundary: 'end',
    traceId: 'trace-id-removed'
  },
  {
    id: 'id-removed',
    cell: 'partial-cache',
    behaviorKey: 'vault-orchestrator',
    name: 'stage:start:core-state',
    timestamp: 'ts-removed',
    monotonicTimestamp: 'mts-removed',
    type: 'stage',
    boundary: 'start',
    traceId: 'trace-id-removed'
  },
  {
    id: 'id-removed',
    cell: 'partial-cache',
    behaviorKey: 'vault-orchestrator',
    name: 'pipeline:candidate:core-state',
    timestamp: 'ts-removed',
    monotonicTimestamp: 'mts-removed',
    type: 'pipeline',
    boundary: 'candidate',
    traceId: 'trace-id-removed'
  },
  {
    id: 'id-removed',
    cell: 'partial-cache',
    behaviorKey: 'vault-orchestrator',
    name: 'stage:end:core-state',
    timestamp: 'ts-removed',
    monotonicTimestamp: 'mts-removed',
    type: 'stage',
    boundary: 'end',
    traceId: 'trace-id-removed'
  },
  {
    id: 'id-removed',
    cell: 'partial-cache',
    behaviorKey: 'decision-engine',
    name: 'lifecycle:notification:success',
    timestamp: 'ts-removed',
    monotonicTimestamp: 'mts-removed',
    type: 'lifecycle',
    boundary: 'notification',
    traceId: 'trace-id-removed'
  },
  {
    id: 'id-removed',
    cell: 'partial-cache',
    behaviorKey: 'vault-conductor',
    name: 'conductor:end:attempt',
    timestamp: 'ts-removed',
    monotonicTimestamp: 'mts-removed',
    type: 'conductor',
    boundary: 'end',
    traceId: 'trace-id-removed'
  },
  {
    id: 'id-removed',
    cell: 'partial-cache',
    behaviorKey: 'decision-engine',
    name: 'lifecycle:notification:finalize',
    timestamp: 'ts-removed',
    monotonicTimestamp: 'mts-removed',
    type: 'lifecycle',
    boundary: 'notification',
    traceId: 'trace-id-removed'
  },
  {
    id: 'id-removed',
    cell: 'partial-cache',
    behaviorKey: 'vault-conductor',
    name: 'controller:start:attempt',
    timestamp: 'ts-removed',
    monotonicTimestamp: 'mts-removed',
    type: 'controller',
    boundary: 'start',
    traceId: 'trace-id-removed'
  },
  {
    id: 'id-removed',
    cell: 'partial-cache',
    behaviorKey: 'vault-conductor',
    name: 'controller:start:vote',
    timestamp: 'ts-removed',
    monotonicTimestamp: 'mts-removed',
    type: 'controller',
    boundary: 'start',
    traceId: 'trace-id-removed'
  },
  {
    id: 'id-removed',
    cell: 'partial-cache',
    behaviorKey: 'SDUX::Controller::Policy::CoreAbstain',
    name: 'controller:start:vote',
    timestamp: 'ts-removed',
    monotonicTimestamp: 'mts-removed',
    type: 'controller',
    boundary: 'start',
    traceId: 'trace-id-removed'
  },
  {
    id: 'id-removed',
    cell: 'partial-cache',
    behaviorKey: 'SDUX::Controller::Policy::CoreLicense',
    name: 'controller:start:vote',
    timestamp: 'ts-removed',
    monotonicTimestamp: 'mts-removed',
    type: 'controller',
    boundary: 'start',
    traceId: 'trace-id-removed'
  },
  {
    id: 'id-removed',
    cell: 'partial-cache',
    behaviorKey: 'SDUX::Controller::Policy::CoreError',
    name: 'controller:start:vote',
    timestamp: 'ts-removed',
    monotonicTimestamp: 'mts-removed',
    type: 'controller',
    boundary: 'start',
    traceId: 'trace-id-removed'
  },
  {
    id: 'id-removed',
    cell: 'partial-cache',
    behaviorKey: 'SDUX::Controller::Policy::CoreAbstain',
    name: 'controller:end:vote',
    timestamp: 'ts-removed',
    monotonicTimestamp: 'mts-removed',
    type: 'controller',
    boundary: 'end',
    traceId: 'trace-id-removed'
  },
  {
    id: 'id-removed',
    cell: 'partial-cache',
    behaviorKey: 'SDUX::Controller::Policy::CoreLicense',
    name: 'controller:end:vote',
    timestamp: 'ts-removed',
    monotonicTimestamp: 'mts-removed',
    type: 'controller',
    boundary: 'end',
    traceId: 'trace-id-removed'
  },
  {
    id: 'id-removed',
    cell: 'partial-cache',
    behaviorKey: 'SDUX::Controller::Policy::CoreError',
    name: 'controller:end:vote',
    timestamp: 'ts-removed',
    monotonicTimestamp: 'mts-removed',
    type: 'controller',
    boundary: 'end',
    traceId: 'trace-id-removed'
  },
  {
    id: 'id-removed',
    cell: 'partial-cache',
    behaviorKey: 'vault-conductor',
    name: 'controller:end:vote',
    timestamp: 'ts-removed',
    monotonicTimestamp: 'mts-removed',
    type: 'controller',
    boundary: 'end',
    traceId: 'trace-id-removed'
  },
  {
    id: 'id-removed',
    cell: 'partial-cache',
    behaviorKey: 'vault-conductor',
    name: 'controller:end:attempt',
    timestamp: 'ts-removed',
    monotonicTimestamp: 'mts-removed',
    type: 'controller',
    boundary: 'end',
    traceId: 'trace-id-removed'
  },
  {
    id: 'id-removed',
    cell: 'partial-cache',
    behaviorKey: 'vault-orchestrator',
    name: 'pipeline:candidate:pipeline-start',
    timestamp: 'ts-removed',
    monotonicTimestamp: 'mts-removed',
    type: 'pipeline',
    boundary: 'candidate',
    traceId: 'trace-id-removed'
  },
  {
    id: 'id-removed',
    cell: 'partial-cache',
    behaviorKey: 'vault-orchestrator',
    name: 'lifecycle:start:merge',
    timestamp: 'ts-removed',
    monotonicTimestamp: 'mts-removed',
    type: 'lifecycle',
    boundary: 'start',
    traceId: 'trace-id-removed'
  },
  {
    id: 'id-removed',
    cell: 'partial-cache',
    behaviorKey: 'SDUX::Behavior::Core::Promise',
    name: 'stage:start:resolve',
    timestamp: 'ts-removed',
    monotonicTimestamp: 'mts-removed',
    type: 'stage',
    boundary: 'start',
    traceId: 'trace-id-removed'
  },
  {
    id: 'id-removed',
    cell: 'partial-cache',
    behaviorKey: 'vault-orchestrator',
    name: 'pipeline:candidate:resolve',
    timestamp: 'ts-removed',
    monotonicTimestamp: 'mts-removed',
    type: 'pipeline',
    boundary: 'candidate',
    traceId: 'trace-id-removed'
  },
  {
    id: 'id-removed',
    cell: 'partial-cache',
    behaviorKey: 'SDUX::Behavior::Core::Promise',
    name: 'stage:end:resolve',
    timestamp: 'ts-removed',
    monotonicTimestamp: 'mts-removed',
    type: 'stage',
    boundary: 'end',
    traceId: 'trace-id-removed'
  },
  {
    id: 'id-removed',
    cell: 'partial-cache',
    behaviorKey: 'vault-orchestrator',
    name: 'stage:start:compute-merge',
    timestamp: 'ts-removed',
    monotonicTimestamp: 'mts-removed',
    type: 'stage',
    boundary: 'start',
    traceId: 'trace-id-removed'
  },
  {
    id: 'id-removed',
    cell: 'partial-cache',
    behaviorKey: 'vault-orchestrator',
    name: 'pipeline:candidate:compute-merge',
    timestamp: 'ts-removed',
    monotonicTimestamp: 'mts-removed',
    type: 'pipeline',
    boundary: 'candidate',
    traceId: 'trace-id-removed'
  },
  {
    id: 'id-removed',
    cell: 'partial-cache',
    behaviorKey: 'vault-orchestrator',
    name: 'stage:end:compute-merge',
    timestamp: 'ts-removed',
    monotonicTimestamp: 'mts-removed',
    type: 'stage',
    boundary: 'end',
    traceId: 'trace-id-removed'
  },
  {
    id: 'id-removed',
    cell: 'partial-cache',
    behaviorKey: 'vault-orchestrator',
    name: 'lifecycle:end:merge',
    timestamp: 'ts-removed',
    monotonicTimestamp: 'mts-removed',
    type: 'lifecycle',
    boundary: 'end',
    traceId: 'trace-id-removed'
  },
  {
    id: 'id-removed',
    cell: 'partial-cache',
    behaviorKey: 'vault-orchestrator',
    name: 'stage:start:core-state',
    timestamp: 'ts-removed',
    monotonicTimestamp: 'mts-removed',
    type: 'stage',
    boundary: 'start',
    traceId: 'trace-id-removed'
  },
  {
    id: 'id-removed',
    cell: 'partial-cache',
    behaviorKey: 'vault-orchestrator',
    name: 'pipeline:candidate:core-state',
    timestamp: 'ts-removed',
    monotonicTimestamp: 'mts-removed',
    type: 'pipeline',
    boundary: 'candidate',
    traceId: 'trace-id-removed'
  },
  {
    id: 'id-removed',
    cell: 'partial-cache',
    behaviorKey: 'vault-orchestrator',
    name: 'stage:end:core-state',
    timestamp: 'ts-removed',
    monotonicTimestamp: 'mts-removed',
    type: 'stage',
    boundary: 'end',
    traceId: 'trace-id-removed'
  },
  {
    id: 'id-removed',
    cell: 'partial-cache',
    behaviorKey: 'decision-engine',
    name: 'lifecycle:notification:success',
    timestamp: 'ts-removed',
    monotonicTimestamp: 'mts-removed',
    type: 'lifecycle',
    boundary: 'notification',
    traceId: 'trace-id-removed'
  },
  {
    id: 'id-removed',
    cell: 'partial-cache',
    behaviorKey: 'vault-conductor',
    name: 'conductor:end:attempt',
    timestamp: 'ts-removed',
    monotonicTimestamp: 'mts-removed',
    type: 'conductor',
    boundary: 'end',
    traceId: 'trace-id-removed'
  },
  {
    id: 'id-removed',
    cell: 'partial-cache',
    behaviorKey: 'decision-engine',
    name: 'lifecycle:notification:finalize',
    timestamp: 'ts-removed',
    monotonicTimestamp: 'mts-removed',
    type: 'lifecycle',
    boundary: 'notification',
    traceId: 'trace-id-removed'
  },
  {
    id: 'id-removed',
    cell: 'partial-cache',
    behaviorKey: 'vault-conductor',
    name: 'controller:start:attempt',
    timestamp: 'ts-removed',
    monotonicTimestamp: 'mts-removed',
    type: 'controller',
    boundary: 'start',
    traceId: 'trace-id-removed'
  },
  {
    id: 'id-removed',
    cell: 'partial-cache',
    behaviorKey: 'vault-conductor',
    name: 'controller:start:vote',
    timestamp: 'ts-removed',
    monotonicTimestamp: 'mts-removed',
    type: 'controller',
    boundary: 'start',
    traceId: 'trace-id-removed'
  },
  {
    id: 'id-removed',
    cell: 'partial-cache',
    behaviorKey: 'SDUX::Controller::Policy::CoreAbstain',
    name: 'controller:start:vote',
    timestamp: 'ts-removed',
    monotonicTimestamp: 'mts-removed',
    type: 'controller',
    boundary: 'start',
    traceId: 'trace-id-removed'
  },
  {
    id: 'id-removed',
    cell: 'partial-cache',
    behaviorKey: 'SDUX::Controller::Policy::CoreLicense',
    name: 'controller:start:vote',
    timestamp: 'ts-removed',
    monotonicTimestamp: 'mts-removed',
    type: 'controller',
    boundary: 'start',
    traceId: 'trace-id-removed'
  },
  {
    id: 'id-removed',
    cell: 'partial-cache',
    behaviorKey: 'SDUX::Controller::Policy::CoreError',
    name: 'controller:start:vote',
    timestamp: 'ts-removed',
    monotonicTimestamp: 'mts-removed',
    type: 'controller',
    boundary: 'start',
    traceId: 'trace-id-removed'
  },
  {
    id: 'id-removed',
    cell: 'partial-cache',
    behaviorKey: 'SDUX::Controller::Policy::CoreAbstain',
    name: 'controller:end:vote',
    timestamp: 'ts-removed',
    monotonicTimestamp: 'mts-removed',
    type: 'controller',
    boundary: 'end',
    traceId: 'trace-id-removed'
  },
  {
    id: 'id-removed',
    cell: 'partial-cache',
    behaviorKey: 'SDUX::Controller::Policy::CoreLicense',
    name: 'controller:end:vote',
    timestamp: 'ts-removed',
    monotonicTimestamp: 'mts-removed',
    type: 'controller',
    boundary: 'end',
    traceId: 'trace-id-removed'
  },
  {
    id: 'id-removed',
    cell: 'partial-cache',
    behaviorKey: 'SDUX::Controller::Policy::CoreError',
    name: 'controller:end:vote',
    timestamp: 'ts-removed',
    monotonicTimestamp: 'mts-removed',
    type: 'controller',
    boundary: 'end',
    traceId: 'trace-id-removed'
  },
  {
    id: 'id-removed',
    cell: 'partial-cache',
    behaviorKey: 'vault-conductor',
    name: 'controller:end:vote',
    timestamp: 'ts-removed',
    monotonicTimestamp: 'mts-removed',
    type: 'controller',
    boundary: 'end',
    traceId: 'trace-id-removed'
  },
  {
    id: 'id-removed',
    cell: 'partial-cache',
    behaviorKey: 'vault-conductor',
    name: 'controller:end:attempt',
    timestamp: 'ts-removed',
    monotonicTimestamp: 'mts-removed',
    type: 'controller',
    boundary: 'end',
    traceId: 'trace-id-removed'
  },
  {
    id: 'id-removed',
    cell: 'partial-cache',
    behaviorKey: 'vault-orchestrator',
    name: 'pipeline:candidate:pipeline-start',
    timestamp: 'ts-removed',
    monotonicTimestamp: 'mts-removed',
    type: 'pipeline',
    boundary: 'candidate',
    traceId: 'trace-id-removed'
  },
  {
    id: 'id-removed',
    cell: 'partial-cache',
    behaviorKey: 'vault-orchestrator',
    name: 'lifecycle:start:merge',
    timestamp: 'ts-removed',
    monotonicTimestamp: 'mts-removed',
    type: 'lifecycle',
    boundary: 'start',
    traceId: 'trace-id-removed'
  },
  {
    id: 'id-removed',
    cell: 'partial-cache',
    behaviorKey: 'SDUX::Behavior::Core::Promise',
    name: 'stage:start:resolve',
    timestamp: 'ts-removed',
    monotonicTimestamp: 'mts-removed',
    type: 'stage',
    boundary: 'start',
    traceId: 'trace-id-removed'
  },
  {
    id: 'id-removed',
    cell: 'partial-cache',
    behaviorKey: 'vault-orchestrator',
    name: 'pipeline:candidate:resolve',
    timestamp: 'ts-removed',
    monotonicTimestamp: 'mts-removed',
    type: 'pipeline',
    boundary: 'candidate',
    traceId: 'trace-id-removed'
  },
  {
    id: 'id-removed',
    cell: 'partial-cache',
    behaviorKey: 'SDUX::Behavior::Core::Promise',
    name: 'stage:end:resolve',
    timestamp: 'ts-removed',
    monotonicTimestamp: 'mts-removed',
    type: 'stage',
    boundary: 'end',
    traceId: 'trace-id-removed'
  },
  {
    id: 'id-removed',
    cell: 'partial-cache',
    behaviorKey: 'vault-orchestrator',
    name: 'stage:start:compute-merge',
    timestamp: 'ts-removed',
    monotonicTimestamp: 'mts-removed',
    type: 'stage',
    boundary: 'start',
    traceId: 'trace-id-removed'
  },
  {
    id: 'id-removed',
    cell: 'partial-cache',
    behaviorKey: 'vault-orchestrator',
    name: 'pipeline:candidate:compute-merge',
    timestamp: 'ts-removed',
    monotonicTimestamp: 'mts-removed',
    type: 'pipeline',
    boundary: 'candidate',
    traceId: 'trace-id-removed'
  },
  {
    id: 'id-removed',
    cell: 'partial-cache',
    behaviorKey: 'vault-orchestrator',
    name: 'stage:end:compute-merge',
    timestamp: 'ts-removed',
    monotonicTimestamp: 'mts-removed',
    type: 'stage',
    boundary: 'end',
    traceId: 'trace-id-removed'
  },
  {
    id: 'id-removed',
    cell: 'partial-cache',
    behaviorKey: 'vault-orchestrator',
    name: 'lifecycle:end:merge',
    timestamp: 'ts-removed',
    monotonicTimestamp: 'mts-removed',
    type: 'lifecycle',
    boundary: 'end',
    traceId: 'trace-id-removed'
  },
  {
    id: 'id-removed',
    cell: 'partial-cache',
    behaviorKey: 'vault-orchestrator',
    name: 'stage:start:core-state',
    timestamp: 'ts-removed',
    monotonicTimestamp: 'mts-removed',
    type: 'stage',
    boundary: 'start',
    traceId: 'trace-id-removed'
  },
  {
    id: 'id-removed',
    cell: 'partial-cache',
    behaviorKey: 'vault-orchestrator',
    name: 'pipeline:candidate:core-state',
    timestamp: 'ts-removed',
    monotonicTimestamp: 'mts-removed',
    type: 'pipeline',
    boundary: 'candidate',
    traceId: 'trace-id-removed'
  },
  {
    id: 'id-removed',
    cell: 'partial-cache',
    behaviorKey: 'vault-orchestrator',
    name: 'stage:end:core-state',
    timestamp: 'ts-removed',
    monotonicTimestamp: 'mts-removed',
    type: 'stage',
    boundary: 'end',
    traceId: 'trace-id-removed'
  },
  {
    id: 'id-removed',
    cell: 'partial-cache',
    behaviorKey: 'decision-engine',
    name: 'lifecycle:notification:success',
    timestamp: 'ts-removed',
    monotonicTimestamp: 'mts-removed',
    type: 'lifecycle',
    boundary: 'notification',
    traceId: 'trace-id-removed'
  },
  {
    id: 'id-removed',
    cell: 'partial-cache',
    behaviorKey: 'vault-conductor',
    name: 'conductor:end:attempt',
    timestamp: 'ts-removed',
    monotonicTimestamp: 'mts-removed',
    type: 'conductor',
    boundary: 'end',
    traceId: 'trace-id-removed'
  },
  {
    id: 'id-removed',
    cell: 'partial-cache',
    behaviorKey: 'decision-engine',
    name: 'lifecycle:notification:finalize',
    timestamp: 'ts-removed',
    monotonicTimestamp: 'mts-removed',
    type: 'lifecycle',
    boundary: 'notification',
    traceId: 'trace-id-removed'
  },
  {
    id: 'id-removed',
    cell: 'partial-cache',
    behaviorKey: 'vault-conductor',
    name: 'controller:start:attempt',
    timestamp: 'ts-removed',
    monotonicTimestamp: 'mts-removed',
    type: 'controller',
    boundary: 'start',
    traceId: 'trace-id-removed'
  },
  {
    id: 'id-removed',
    cell: 'partial-cache',
    behaviorKey: 'vault-conductor',
    name: 'controller:start:vote',
    timestamp: 'ts-removed',
    monotonicTimestamp: 'mts-removed',
    type: 'controller',
    boundary: 'start',
    traceId: 'trace-id-removed'
  },
  {
    id: 'id-removed',
    cell: 'partial-cache',
    behaviorKey: 'SDUX::Controller::Policy::CoreAbstain',
    name: 'controller:start:vote',
    timestamp: 'ts-removed',
    monotonicTimestamp: 'mts-removed',
    type: 'controller',
    boundary: 'start',
    traceId: 'trace-id-removed'
  },
  {
    id: 'id-removed',
    cell: 'partial-cache',
    behaviorKey: 'SDUX::Controller::Policy::CoreLicense',
    name: 'controller:start:vote',
    timestamp: 'ts-removed',
    monotonicTimestamp: 'mts-removed',
    type: 'controller',
    boundary: 'start',
    traceId: 'trace-id-removed'
  },
  {
    id: 'id-removed',
    cell: 'partial-cache',
    behaviorKey: 'SDUX::Controller::Policy::CoreError',
    name: 'controller:start:vote',
    timestamp: 'ts-removed',
    monotonicTimestamp: 'mts-removed',
    type: 'controller',
    boundary: 'start',
    traceId: 'trace-id-removed'
  },
  {
    id: 'id-removed',
    cell: 'partial-cache',
    behaviorKey: 'SDUX::Controller::Policy::CoreAbstain',
    name: 'controller:end:vote',
    timestamp: 'ts-removed',
    monotonicTimestamp: 'mts-removed',
    type: 'controller',
    boundary: 'end',
    traceId: 'trace-id-removed'
  },
  {
    id: 'id-removed',
    cell: 'partial-cache',
    behaviorKey: 'SDUX::Controller::Policy::CoreLicense',
    name: 'controller:end:vote',
    timestamp: 'ts-removed',
    monotonicTimestamp: 'mts-removed',
    type: 'controller',
    boundary: 'end',
    traceId: 'trace-id-removed'
  },
  {
    id: 'id-removed',
    cell: 'partial-cache',
    behaviorKey: 'SDUX::Controller::Policy::CoreError',
    name: 'controller:end:vote',
    timestamp: 'ts-removed',
    monotonicTimestamp: 'mts-removed',
    type: 'controller',
    boundary: 'end',
    traceId: 'trace-id-removed'
  },
  {
    id: 'id-removed',
    cell: 'partial-cache',
    behaviorKey: 'vault-conductor',
    name: 'controller:end:vote',
    timestamp: 'ts-removed',
    monotonicTimestamp: 'mts-removed',
    type: 'controller',
    boundary: 'end',
    traceId: 'trace-id-removed'
  },
  {
    id: 'id-removed',
    cell: 'partial-cache',
    behaviorKey: 'vault-conductor',
    name: 'controller:end:attempt',
    timestamp: 'ts-removed',
    monotonicTimestamp: 'mts-removed',
    type: 'controller',
    boundary: 'end',
    traceId: 'trace-id-removed'
  },
  {
    id: 'id-removed',
    cell: 'partial-cache',
    behaviorKey: 'vault-orchestrator',
    name: 'pipeline:candidate:pipeline-start',
    timestamp: 'ts-removed',
    monotonicTimestamp: 'mts-removed',
    type: 'pipeline',
    boundary: 'candidate',
    traceId: 'trace-id-removed'
  },
  {
    id: 'id-removed',
    cell: 'partial-cache',
    behaviorKey: 'vault-orchestrator',
    name: 'lifecycle:start:merge',
    timestamp: 'ts-removed',
    monotonicTimestamp: 'mts-removed',
    type: 'lifecycle',
    boundary: 'start',
    traceId: 'trace-id-removed'
  },
  {
    id: 'id-removed',
    cell: 'partial-cache',
    behaviorKey: 'SDUX::Behavior::Core::Promise',
    name: 'stage:start:resolve',
    timestamp: 'ts-removed',
    monotonicTimestamp: 'mts-removed',
    type: 'stage',
    boundary: 'start',
    traceId: 'trace-id-removed'
  },
  {
    id: 'id-removed',
    cell: 'partial-cache',
    behaviorKey: 'vault-orchestrator',
    name: 'pipeline:candidate:resolve',
    timestamp: 'ts-removed',
    monotonicTimestamp: 'mts-removed',
    type: 'pipeline',
    boundary: 'candidate',
    traceId: 'trace-id-removed'
  },
  {
    id: 'id-removed',
    cell: 'partial-cache',
    behaviorKey: 'SDUX::Behavior::Core::Promise',
    name: 'stage:end:resolve',
    timestamp: 'ts-removed',
    monotonicTimestamp: 'mts-removed',
    type: 'stage',
    boundary: 'end',
    traceId: 'trace-id-removed'
  },
  {
    id: 'id-removed',
    cell: 'partial-cache',
    behaviorKey: 'vault-orchestrator',
    name: 'stage:start:compute-merge',
    timestamp: 'ts-removed',
    monotonicTimestamp: 'mts-removed',
    type: 'stage',
    boundary: 'start',
    traceId: 'trace-id-removed'
  },
  {
    id: 'id-removed',
    cell: 'partial-cache',
    behaviorKey: 'vault-orchestrator',
    name: 'pipeline:candidate:compute-merge',
    timestamp: 'ts-removed',
    monotonicTimestamp: 'mts-removed',
    type: 'pipeline',
    boundary: 'candidate',
    traceId: 'trace-id-removed'
  },
  {
    id: 'id-removed',
    cell: 'partial-cache',
    behaviorKey: 'vault-orchestrator',
    name: 'stage:end:compute-merge',
    timestamp: 'ts-removed',
    monotonicTimestamp: 'mts-removed',
    type: 'stage',
    boundary: 'end',
    traceId: 'trace-id-removed'
  },
  {
    id: 'id-removed',
    cell: 'partial-cache',
    behaviorKey: 'vault-orchestrator',
    name: 'lifecycle:end:merge',
    timestamp: 'ts-removed',
    monotonicTimestamp: 'mts-removed',
    type: 'lifecycle',
    boundary: 'end',
    traceId: 'trace-id-removed'
  },
  {
    id: 'id-removed',
    cell: 'partial-cache',
    behaviorKey: 'vault-orchestrator',
    name: 'stage:start:core-state',
    timestamp: 'ts-removed',
    monotonicTimestamp: 'mts-removed',
    type: 'stage',
    boundary: 'start',
    traceId: 'trace-id-removed'
  },
  {
    id: 'id-removed',
    cell: 'partial-cache',
    behaviorKey: 'vault-orchestrator',
    name: 'pipeline:candidate:core-state',
    timestamp: 'ts-removed',
    monotonicTimestamp: 'mts-removed',
    type: 'pipeline',
    boundary: 'candidate',
    traceId: 'trace-id-removed'
  },
  {
    id: 'id-removed',
    cell: 'partial-cache',
    behaviorKey: 'vault-orchestrator',
    name: 'stage:end:core-state',
    timestamp: 'ts-removed',
    monotonicTimestamp: 'mts-removed',
    type: 'stage',
    boundary: 'end',
    traceId: 'trace-id-removed'
  },
  {
    id: 'id-removed',
    cell: 'partial-cache',
    behaviorKey: 'decision-engine',
    name: 'lifecycle:notification:success',
    timestamp: 'ts-removed',
    monotonicTimestamp: 'mts-removed',
    type: 'lifecycle',
    boundary: 'notification',
    traceId: 'trace-id-removed'
  },
  {
    id: 'id-removed',
    cell: 'partial-cache',
    behaviorKey: 'vault-conductor',
    name: 'conductor:end:attempt',
    timestamp: 'ts-removed',
    monotonicTimestamp: 'mts-removed',
    type: 'conductor',
    boundary: 'end',
    traceId: 'trace-id-removed'
  },
  {
    id: 'id-removed',
    cell: 'partial-cache',
    behaviorKey: 'decision-engine',
    name: 'lifecycle:notification:finalize',
    timestamp: 'ts-removed',
    monotonicTimestamp: 'mts-removed',
    type: 'lifecycle',
    boundary: 'notification',
    traceId: 'trace-id-removed'
  },
  {
    id: 'id-removed',
    cell: 'partial-cache',
    behaviorKey: 'vault-conductor',
    name: 'controller:start:attempt',
    timestamp: 'ts-removed',
    monotonicTimestamp: 'mts-removed',
    type: 'controller',
    boundary: 'start',
    traceId: 'trace-id-removed'
  },
  {
    id: 'id-removed',
    cell: 'partial-cache',
    behaviorKey: 'vault-conductor',
    name: 'controller:start:vote',
    timestamp: 'ts-removed',
    monotonicTimestamp: 'mts-removed',
    type: 'controller',
    boundary: 'start',
    traceId: 'trace-id-removed'
  },
  {
    id: 'id-removed',
    cell: 'partial-cache',
    behaviorKey: 'SDUX::Controller::Policy::CoreAbstain',
    name: 'controller:start:vote',
    timestamp: 'ts-removed',
    monotonicTimestamp: 'mts-removed',
    type: 'controller',
    boundary: 'start',
    traceId: 'trace-id-removed'
  },
  {
    id: 'id-removed',
    cell: 'partial-cache',
    behaviorKey: 'SDUX::Controller::Policy::CoreLicense',
    name: 'controller:start:vote',
    timestamp: 'ts-removed',
    monotonicTimestamp: 'mts-removed',
    type: 'controller',
    boundary: 'start',
    traceId: 'trace-id-removed'
  },
  {
    id: 'id-removed',
    cell: 'partial-cache',
    behaviorKey: 'SDUX::Controller::Policy::CoreError',
    name: 'controller:start:vote',
    timestamp: 'ts-removed',
    monotonicTimestamp: 'mts-removed',
    type: 'controller',
    boundary: 'start',
    traceId: 'trace-id-removed'
  },
  {
    id: 'id-removed',
    cell: 'partial-cache',
    behaviorKey: 'SDUX::Controller::Policy::CoreAbstain',
    name: 'controller:end:vote',
    timestamp: 'ts-removed',
    monotonicTimestamp: 'mts-removed',
    type: 'controller',
    boundary: 'end',
    traceId: 'trace-id-removed'
  },
  {
    id: 'id-removed',
    cell: 'partial-cache',
    behaviorKey: 'SDUX::Controller::Policy::CoreLicense',
    name: 'controller:end:vote',
    timestamp: 'ts-removed',
    monotonicTimestamp: 'mts-removed',
    type: 'controller',
    boundary: 'end',
    traceId: 'trace-id-removed'
  },
  {
    id: 'id-removed',
    cell: 'partial-cache',
    behaviorKey: 'SDUX::Controller::Policy::CoreError',
    name: 'controller:end:vote',
    timestamp: 'ts-removed',
    monotonicTimestamp: 'mts-removed',
    type: 'controller',
    boundary: 'end',
    traceId: 'trace-id-removed'
  },
  {
    id: 'id-removed',
    cell: 'partial-cache',
    behaviorKey: 'vault-conductor',
    name: 'controller:end:vote',
    timestamp: 'ts-removed',
    monotonicTimestamp: 'mts-removed',
    type: 'controller',
    boundary: 'end',
    traceId: 'trace-id-removed'
  },
  {
    id: 'id-removed',
    cell: 'partial-cache',
    behaviorKey: 'vault-conductor',
    name: 'controller:end:attempt',
    timestamp: 'ts-removed',
    monotonicTimestamp: 'mts-removed',
    type: 'controller',
    boundary: 'end',
    traceId: 'trace-id-removed'
  },
  {
    id: 'id-removed',
    cell: 'partial-cache',
    behaviorKey: 'vault-orchestrator',
    name: 'pipeline:candidate:pipeline-start',
    timestamp: 'ts-removed',
    monotonicTimestamp: 'mts-removed',
    type: 'pipeline',
    boundary: 'candidate',
    traceId: 'trace-id-removed'
  },
  {
    id: 'id-removed',
    cell: 'partial-cache',
    behaviorKey: 'vault-orchestrator',
    name: 'lifecycle:start:merge',
    timestamp: 'ts-removed',
    monotonicTimestamp: 'mts-removed',
    type: 'lifecycle',
    boundary: 'start',
    traceId: 'trace-id-removed'
  },
  {
    id: 'id-removed',
    cell: 'partial-cache',
    behaviorKey: 'SDUX::Behavior::Core::Promise',
    name: 'stage:start:resolve',
    timestamp: 'ts-removed',
    monotonicTimestamp: 'mts-removed',
    type: 'stage',
    boundary: 'start',
    traceId: 'trace-id-removed'
  },
  {
    id: 'id-removed',
    cell: 'partial-cache',
    behaviorKey: 'vault-orchestrator',
    name: 'pipeline:candidate:resolve',
    timestamp: 'ts-removed',
    monotonicTimestamp: 'mts-removed',
    type: 'pipeline',
    boundary: 'candidate',
    traceId: 'trace-id-removed'
  },
  {
    id: 'id-removed',
    cell: 'partial-cache',
    behaviorKey: 'SDUX::Behavior::Core::Promise',
    name: 'stage:end:resolve',
    timestamp: 'ts-removed',
    monotonicTimestamp: 'mts-removed',
    type: 'stage',
    boundary: 'end',
    traceId: 'trace-id-removed'
  },
  {
    id: 'id-removed',
    cell: 'partial-cache',
    behaviorKey: 'vault-orchestrator',
    name: 'stage:start:compute-merge',
    timestamp: 'ts-removed',
    monotonicTimestamp: 'mts-removed',
    type: 'stage',
    boundary: 'start',
    traceId: 'trace-id-removed'
  },
  {
    id: 'id-removed',
    cell: 'partial-cache',
    behaviorKey: 'vault-orchestrator',
    name: 'pipeline:candidate:compute-merge',
    timestamp: 'ts-removed',
    monotonicTimestamp: 'mts-removed',
    type: 'pipeline',
    boundary: 'candidate',
    traceId: 'trace-id-removed'
  },
  {
    id: 'id-removed',
    cell: 'partial-cache',
    behaviorKey: 'vault-orchestrator',
    name: 'stage:end:compute-merge',
    timestamp: 'ts-removed',
    monotonicTimestamp: 'mts-removed',
    type: 'stage',
    boundary: 'end',
    traceId: 'trace-id-removed'
  },
  {
    id: 'id-removed',
    cell: 'partial-cache',
    behaviorKey: 'vault-orchestrator',
    name: 'lifecycle:end:merge',
    timestamp: 'ts-removed',
    monotonicTimestamp: 'mts-removed',
    type: 'lifecycle',
    boundary: 'end',
    traceId: 'trace-id-removed'
  },
  {
    id: 'id-removed',
    cell: 'partial-cache',
    behaviorKey: 'vault-orchestrator',
    name: 'stage:start:core-state',
    timestamp: 'ts-removed',
    monotonicTimestamp: 'mts-removed',
    type: 'stage',
    boundary: 'start',
    traceId: 'trace-id-removed'
  },
  {
    id: 'id-removed',
    cell: 'partial-cache',
    behaviorKey: 'vault-orchestrator',
    name: 'pipeline:candidate:core-state',
    timestamp: 'ts-removed',
    monotonicTimestamp: 'mts-removed',
    type: 'pipeline',
    boundary: 'candidate',
    traceId: 'trace-id-removed'
  },
  {
    id: 'id-removed',
    cell: 'partial-cache',
    behaviorKey: 'vault-orchestrator',
    name: 'stage:end:core-state',
    timestamp: 'ts-removed',
    monotonicTimestamp: 'mts-removed',
    type: 'stage',
    boundary: 'end',
    traceId: 'trace-id-removed'
  },
  {
    id: 'id-removed',
    cell: 'partial-cache',
    behaviorKey: 'decision-engine',
    name: 'lifecycle:notification:success',
    timestamp: 'ts-removed',
    monotonicTimestamp: 'mts-removed',
    type: 'lifecycle',
    boundary: 'notification',
    traceId: 'trace-id-removed'
  },
  {
    id: 'id-removed',
    cell: 'partial-cache',
    behaviorKey: 'vault-conductor',
    name: 'conductor:end:attempt',
    timestamp: 'ts-removed',
    monotonicTimestamp: 'mts-removed',
    type: 'conductor',
    boundary: 'end',
    traceId: 'trace-id-removed'
  },
  {
    id: 'id-removed',
    cell: 'partial-cache',
    behaviorKey: 'decision-engine',
    name: 'lifecycle:notification:finalize',
    timestamp: 'ts-removed',
    monotonicTimestamp: 'mts-removed',
    type: 'lifecycle',
    boundary: 'notification',
    traceId: 'trace-id-removed'
  },
  {
    id: 'id-removed',
    cell: 'partial-cache',
    behaviorKey: 'vault-conductor',
    name: 'controller:start:attempt',
    timestamp: 'ts-removed',
    monotonicTimestamp: 'mts-removed',
    type: 'controller',
    boundary: 'start',
    traceId: 'trace-id-removed'
  },
  {
    id: 'id-removed',
    cell: 'partial-cache',
    behaviorKey: 'vault-conductor',
    name: 'controller:start:vote',
    timestamp: 'ts-removed',
    monotonicTimestamp: 'mts-removed',
    type: 'controller',
    boundary: 'start',
    traceId: 'trace-id-removed'
  },
  {
    id: 'id-removed',
    cell: 'partial-cache',
    behaviorKey: 'SDUX::Controller::Policy::CoreAbstain',
    name: 'controller:start:vote',
    timestamp: 'ts-removed',
    monotonicTimestamp: 'mts-removed',
    type: 'controller',
    boundary: 'start',
    traceId: 'trace-id-removed'
  },
  {
    id: 'id-removed',
    cell: 'partial-cache',
    behaviorKey: 'SDUX::Controller::Policy::CoreLicense',
    name: 'controller:start:vote',
    timestamp: 'ts-removed',
    monotonicTimestamp: 'mts-removed',
    type: 'controller',
    boundary: 'start',
    traceId: 'trace-id-removed'
  },
  {
    id: 'id-removed',
    cell: 'partial-cache',
    behaviorKey: 'SDUX::Controller::Policy::CoreError',
    name: 'controller:start:vote',
    timestamp: 'ts-removed',
    monotonicTimestamp: 'mts-removed',
    type: 'controller',
    boundary: 'start',
    traceId: 'trace-id-removed'
  },
  {
    id: 'id-removed',
    cell: 'partial-cache',
    behaviorKey: 'SDUX::Controller::Policy::CoreAbstain',
    name: 'controller:end:vote',
    timestamp: 'ts-removed',
    monotonicTimestamp: 'mts-removed',
    type: 'controller',
    boundary: 'end',
    traceId: 'trace-id-removed'
  },
  {
    id: 'id-removed',
    cell: 'partial-cache',
    behaviorKey: 'SDUX::Controller::Policy::CoreLicense',
    name: 'controller:end:vote',
    timestamp: 'ts-removed',
    monotonicTimestamp: 'mts-removed',
    type: 'controller',
    boundary: 'end',
    traceId: 'trace-id-removed'
  },
  {
    id: 'id-removed',
    cell: 'partial-cache',
    behaviorKey: 'SDUX::Controller::Policy::CoreError',
    name: 'controller:end:vote',
    timestamp: 'ts-removed',
    monotonicTimestamp: 'mts-removed',
    type: 'controller',
    boundary: 'end',
    traceId: 'trace-id-removed'
  },
  {
    id: 'id-removed',
    cell: 'partial-cache',
    behaviorKey: 'vault-conductor',
    name: 'controller:end:vote',
    timestamp: 'ts-removed',
    monotonicTimestamp: 'mts-removed',
    type: 'controller',
    boundary: 'end',
    traceId: 'trace-id-removed'
  },
  {
    id: 'id-removed',
    cell: 'partial-cache',
    behaviorKey: 'vault-conductor',
    name: 'controller:end:attempt',
    timestamp: 'ts-removed',
    monotonicTimestamp: 'mts-removed',
    type: 'controller',
    boundary: 'end',
    traceId: 'trace-id-removed'
  },
  {
    id: 'id-removed',
    cell: 'partial-cache',
    behaviorKey: 'vault-orchestrator',
    name: 'pipeline:candidate:pipeline-start',
    timestamp: 'ts-removed',
    monotonicTimestamp: 'mts-removed',
    type: 'pipeline',
    boundary: 'candidate',
    traceId: 'trace-id-removed'
  },
  {
    id: 'id-removed',
    cell: 'partial-cache',
    behaviorKey: 'vault-orchestrator',
    name: 'lifecycle:start:merge',
    timestamp: 'ts-removed',
    monotonicTimestamp: 'mts-removed',
    type: 'lifecycle',
    boundary: 'start',
    traceId: 'trace-id-removed'
  },
  {
    id: 'id-removed',
    cell: 'partial-cache',
    behaviorKey: 'SDUX::Behavior::Core::Promise',
    name: 'stage:start:resolve',
    timestamp: 'ts-removed',
    monotonicTimestamp: 'mts-removed',
    type: 'stage',
    boundary: 'start',
    traceId: 'trace-id-removed'
  },
  {
    id: 'id-removed',
    cell: 'partial-cache',
    behaviorKey: 'vault-orchestrator',
    name: 'pipeline:candidate:resolve',
    timestamp: 'ts-removed',
    monotonicTimestamp: 'mts-removed',
    type: 'pipeline',
    boundary: 'candidate',
    traceId: 'trace-id-removed'
  },
  {
    id: 'id-removed',
    cell: 'partial-cache',
    behaviorKey: 'SDUX::Behavior::Core::Promise',
    name: 'stage:end:resolve',
    timestamp: 'ts-removed',
    monotonicTimestamp: 'mts-removed',
    type: 'stage',
    boundary: 'end',
    traceId: 'trace-id-removed'
  },
  {
    id: 'id-removed',
    cell: 'partial-cache',
    behaviorKey: 'vault-orchestrator',
    name: 'stage:start:compute-merge',
    timestamp: 'ts-removed',
    monotonicTimestamp: 'mts-removed',
    type: 'stage',
    boundary: 'start',
    traceId: 'trace-id-removed'
  },
  {
    id: 'id-removed',
    cell: 'partial-cache',
    behaviorKey: 'vault-orchestrator',
    name: 'pipeline:candidate:compute-merge',
    timestamp: 'ts-removed',
    monotonicTimestamp: 'mts-removed',
    type: 'pipeline',
    boundary: 'candidate',
    traceId: 'trace-id-removed'
  },
  {
    id: 'id-removed',
    cell: 'partial-cache',
    behaviorKey: 'vault-orchestrator',
    name: 'stage:end:compute-merge',
    timestamp: 'ts-removed',
    monotonicTimestamp: 'mts-removed',
    type: 'stage',
    boundary: 'end',
    traceId: 'trace-id-removed'
  },
  {
    id: 'id-removed',
    cell: 'partial-cache',
    behaviorKey: 'vault-orchestrator',
    name: 'lifecycle:end:merge',
    timestamp: 'ts-removed',
    monotonicTimestamp: 'mts-removed',
    type: 'lifecycle',
    boundary: 'end',
    traceId: 'trace-id-removed'
  },
  {
    id: 'id-removed',
    cell: 'partial-cache',
    behaviorKey: 'vault-orchestrator',
    name: 'stage:start:core-state',
    timestamp: 'ts-removed',
    monotonicTimestamp: 'mts-removed',
    type: 'stage',
    boundary: 'start',
    traceId: 'trace-id-removed'
  },
  {
    id: 'id-removed',
    cell: 'partial-cache',
    behaviorKey: 'vault-orchestrator',
    name: 'pipeline:candidate:core-state',
    timestamp: 'ts-removed',
    monotonicTimestamp: 'mts-removed',
    type: 'pipeline',
    boundary: 'candidate',
    traceId: 'trace-id-removed'
  },
  {
    id: 'id-removed',
    cell: 'partial-cache',
    behaviorKey: 'vault-orchestrator',
    name: 'stage:end:core-state',
    timestamp: 'ts-removed',
    monotonicTimestamp: 'mts-removed',
    type: 'stage',
    boundary: 'end',
    traceId: 'trace-id-removed'
  },
  {
    id: 'id-removed',
    cell: 'partial-cache',
    behaviorKey: 'decision-engine',
    name: 'lifecycle:notification:success',
    timestamp: 'ts-removed',
    monotonicTimestamp: 'mts-removed',
    type: 'lifecycle',
    boundary: 'notification',
    traceId: 'trace-id-removed'
  },
  {
    id: 'id-removed',
    cell: 'partial-cache',
    behaviorKey: 'vault-conductor',
    name: 'conductor:end:attempt',
    timestamp: 'ts-removed',
    monotonicTimestamp: 'mts-removed',
    type: 'conductor',
    boundary: 'end',
    traceId: 'trace-id-removed'
  },
  {
    id: 'id-removed',
    cell: 'partial-cache',
    behaviorKey: 'decision-engine',
    name: 'lifecycle:notification:finalize',
    timestamp: 'ts-removed',
    monotonicTimestamp: 'mts-removed',
    type: 'lifecycle',
    boundary: 'notification',
    traceId: 'trace-id-removed'
  },
  {
    id: 'id-removed',
    cell: 'partial-cache',
    behaviorKey: 'vault-feature-cell',
    name: 'lifecycle:start:initialized',
    timestamp: 'ts-removed',
    monotonicTimestamp: 'mts-removed',
    type: 'lifecycle',
    boundary: 'start'
  },
  {
    id: 'id-removed',
    cell: 'partial-cache',
    behaviorKey: 'partial-cache::license',
    name: 'lifecycle:notification:license-attempt',
    timestamp: 'ts-removed',
    monotonicTimestamp: 'mts-removed',
    type: 'lifecycle',
    boundary: 'notification'
  },
  {
    id: 'id-removed',
    cell: 'partial-cache',
    behaviorKey: 'partial-cache::license',
    name: 'lifecycle:notification:license-approved',
    timestamp: 'ts-removed',
    monotonicTimestamp: 'mts-removed',
    type: 'lifecycle',
    boundary: 'notification'
  },
  {
    id: 'id-removed',
    cell: 'partial-cache',
    behaviorKey: 'vault-conductor',
    name: 'conductor:start:attempt',
    timestamp: 'ts-removed',
    monotonicTimestamp: 'mts-removed',
    type: 'conductor',
    boundary: 'start',
    traceId: 'trace-id-removed'
  },
  {
    id: 'id-removed',
    cell: 'partial-cache',
    behaviorKey: 'vault-conductor',
    name: 'controller:start:attempt',
    timestamp: 'ts-removed',
    monotonicTimestamp: 'mts-removed',
    type: 'controller',
    boundary: 'start',
    traceId: 'trace-id-removed'
  },
  {
    id: 'id-removed',
    cell: 'partial-cache',
    behaviorKey: 'vault-conductor',
    name: 'controller:start:vote',
    timestamp: 'ts-removed',
    monotonicTimestamp: 'mts-removed',
    type: 'controller',
    boundary: 'start',
    traceId: 'trace-id-removed'
  },
  {
    id: 'id-removed',
    cell: 'partial-cache',
    behaviorKey: 'SDUX::Controller::Policy::CoreAbstain',
    name: 'controller:start:vote',
    timestamp: 'ts-removed',
    monotonicTimestamp: 'mts-removed',
    type: 'controller',
    boundary: 'start',
    traceId: 'trace-id-removed'
  },
  {
    id: 'id-removed',
    cell: 'partial-cache',
    behaviorKey: 'SDUX::Controller::Policy::CoreLicense',
    name: 'controller:start:vote',
    timestamp: 'ts-removed',
    monotonicTimestamp: 'mts-removed',
    type: 'controller',
    boundary: 'start',
    traceId: 'trace-id-removed'
  },
  {
    id: 'id-removed',
    cell: 'partial-cache',
    behaviorKey: 'SDUX::Controller::Policy::CoreError',
    name: 'controller:start:vote',
    timestamp: 'ts-removed',
    monotonicTimestamp: 'mts-removed',
    type: 'controller',
    boundary: 'start',
    traceId: 'trace-id-removed'
  },
  {
    id: 'id-removed',
    cell: 'partial-cache',
    behaviorKey: 'SDUX::Controller::Policy::CoreAbstain',
    name: 'controller:end:vote',
    timestamp: 'ts-removed',
    monotonicTimestamp: 'mts-removed',
    type: 'controller',
    boundary: 'end',
    traceId: 'trace-id-removed'
  },
  {
    id: 'id-removed',
    cell: 'partial-cache',
    behaviorKey: 'SDUX::Controller::Policy::CoreLicense',
    name: 'controller:end:vote',
    timestamp: 'ts-removed',
    monotonicTimestamp: 'mts-removed',
    type: 'controller',
    boundary: 'end',
    traceId: 'trace-id-removed'
  },
  {
    id: 'id-removed',
    cell: 'partial-cache',
    behaviorKey: 'SDUX::Controller::Policy::CoreError',
    name: 'controller:end:vote',
    timestamp: 'ts-removed',
    monotonicTimestamp: 'mts-removed',
    type: 'controller',
    boundary: 'end',
    traceId: 'trace-id-removed'
  },
  {
    id: 'id-removed',
    cell: 'partial-cache',
    behaviorKey: 'vault-conductor',
    name: 'controller:end:vote',
    timestamp: 'ts-removed',
    monotonicTimestamp: 'mts-removed',
    type: 'controller',
    boundary: 'end',
    traceId: 'trace-id-removed'
  },
  {
    id: 'id-removed',
    cell: 'partial-cache',
    behaviorKey: 'vault-feature-cell',
    name: 'lifecycle:end:initialized',
    timestamp: 'ts-removed',
    monotonicTimestamp: 'mts-removed',
    type: 'lifecycle',
    boundary: 'end'
  },
  {
    id: 'id-removed',
    cell: 'partial-cache',
    behaviorKey: 'vault-conductor',
    name: 'controller:end:attempt',
    timestamp: 'ts-removed',
    monotonicTimestamp: 'mts-removed',
    type: 'controller',
    boundary: 'end',
    traceId: 'trace-id-removed'
  },
  {
    id: 'id-removed',
    cell: 'partial-cache',
    behaviorKey: 'vault-orchestrator',
    name: 'lifecycle:start:set-initial-value',
    timestamp: 'ts-removed',
    monotonicTimestamp: 'mts-removed',
    type: 'lifecycle',
    boundary: 'start',
    traceId: 'trace-id-removed'
  },
  {
    id: 'id-removed',
    cell: 'partial-cache',
    behaviorKey: 'vault-orchestrator',
    name: 'lifecycle:end:set-initial-value',
    timestamp: 'ts-removed',
    monotonicTimestamp: 'mts-removed',
    type: 'lifecycle',
    boundary: 'end',
    traceId: 'trace-id-removed'
  },
  {
    id: 'id-removed',
    cell: 'partial-cache',
    behaviorKey: 'vault-orchestrator',
    name: 'pipeline:candidate:pipeline-start',
    timestamp: 'ts-removed',
    monotonicTimestamp: 'mts-removed',
    type: 'pipeline',
    boundary: 'candidate',
    traceId: 'trace-id-removed'
  },
  {
    id: 'id-removed',
    cell: 'partial-cache',
    behaviorKey: 'vault-orchestrator',
    name: 'lifecycle:start:replace',
    timestamp: 'ts-removed',
    monotonicTimestamp: 'mts-removed',
    type: 'lifecycle',
    boundary: 'start',
    traceId: 'trace-id-removed'
  },
  {
    id: 'id-removed',
    cell: 'partial-cache',
    behaviorKey: 'SDUX::Behavior::Core::Value',
    name: 'stage:start:resolve',
    timestamp: 'ts-removed',
    monotonicTimestamp: 'mts-removed',
    type: 'stage',
    boundary: 'start',
    traceId: 'trace-id-removed'
  },
  {
    id: 'id-removed',
    cell: 'partial-cache',
    behaviorKey: 'vault-orchestrator',
    name: 'pipeline:candidate:resolve',
    timestamp: 'ts-removed',
    monotonicTimestamp: 'mts-removed',
    type: 'pipeline',
    boundary: 'candidate',
    traceId: 'trace-id-removed'
  },
  {
    id: 'id-removed',
    cell: 'partial-cache',
    behaviorKey: 'SDUX::Behavior::Core::Value',
    name: 'stage:end:resolve',
    timestamp: 'ts-removed',
    monotonicTimestamp: 'mts-removed',
    type: 'stage',
    boundary: 'end',
    traceId: 'trace-id-removed'
  },
  {
    id: 'id-removed',
    cell: 'partial-cache',
    behaviorKey: 'vault-orchestrator',
    name: 'lifecycle:end:replace',
    timestamp: 'ts-removed',
    monotonicTimestamp: 'mts-removed',
    type: 'lifecycle',
    boundary: 'end',
    traceId: 'trace-id-removed'
  },
  {
    id: 'id-removed',
    cell: 'partial-cache',
    behaviorKey: 'vault-orchestrator',
    name: 'stage:start:core-state',
    timestamp: 'ts-removed',
    monotonicTimestamp: 'mts-removed',
    type: 'stage',
    boundary: 'start',
    traceId: 'trace-id-removed'
  },
  {
    id: 'id-removed',
    cell: 'partial-cache',
    behaviorKey: 'vault-orchestrator',
    name: 'pipeline:candidate:core-state',
    timestamp: 'ts-removed',
    monotonicTimestamp: 'mts-removed',
    type: 'pipeline',
    boundary: 'candidate',
    traceId: 'trace-id-removed'
  },
  {
    id: 'id-removed',
    cell: 'partial-cache',
    behaviorKey: 'vault-orchestrator',
    name: 'stage:end:core-state',
    timestamp: 'ts-removed',
    monotonicTimestamp: 'mts-removed',
    type: 'stage',
    boundary: 'end',
    traceId: 'trace-id-removed'
  },
  {
    id: 'id-removed',
    cell: 'partial-cache',
    behaviorKey: 'decision-engine',
    name: 'lifecycle:notification:success',
    timestamp: 'ts-removed',
    monotonicTimestamp: 'mts-removed',
    type: 'lifecycle',
    boundary: 'notification',
    traceId: 'trace-id-removed'
  },
  {
    id: 'id-removed',
    cell: 'partial-cache',
    behaviorKey: 'vault-conductor',
    name: 'conductor:end:attempt',
    timestamp: 'ts-removed',
    monotonicTimestamp: 'mts-removed',
    type: 'conductor',
    boundary: 'end',
    traceId: 'trace-id-removed'
  },
  {
    id: 'id-removed',
    cell: 'partial-cache',
    behaviorKey: 'decision-engine',
    name: 'lifecycle:notification:finalize',
    timestamp: 'ts-removed',
    monotonicTimestamp: 'mts-removed',
    type: 'lifecycle',
    boundary: 'notification',
    traceId: 'trace-id-removed'
  }
];
