/**
 * AUTO-GENERATED — do not edit manually.
 * Generated by: tools/sdux-comparison/sdux-comparison.mjs
 */
export const ANGULAR_REDUX_OUTPUT = [
  {
    type: 'typescript',
    fileName: 'main.ts',
    source:
      "import { bootstrapApplication } from '@angular/platform-browser';\nimport { appConfig } from './app.config';\nimport { ExampleComponent } from './example.component';\n\nbootstrapApplication(ExampleComponent, appConfig).catch((error: unknown) => {\n  console.error(error);\n});",
    numberedSource:
      "1 | import { bootstrapApplication } from '@angular/platform-browser';\n2 | import { appConfig } from './app.config';\n3 | import { ExampleComponent } from './example.component';\n4 | \n5 | bootstrapApplication(ExampleComponent, appConfig).catch((error: unknown) => {\n6 |   console.error(error);\n7 | });"
  },
  {
    type: 'typescript',
    fileName: 'app.config.ts',
    source:
      "import { ApplicationConfig } from '@angular/core';\nimport { provideStore } from '@ngrx/store';\nimport { employeeFeatureKey, employeeReducer } from './employee.reducer';\n\nexport const appConfig: ApplicationConfig = {\n  providers: [\n    provideStore({\n      [employeeFeatureKey]: employeeReducer\n    })\n  ]\n};",
    numberedSource:
      " 1 | import { ApplicationConfig } from '@angular/core';\n 2 | import { provideStore } from '@ngrx/store';\n 3 | import { employeeFeatureKey, employeeReducer } from './employee.reducer';\n 4 | \n 5 | export const appConfig: ApplicationConfig = {\n 6 |   providers: [\n 7 |     provideStore({\n 8 |       [employeeFeatureKey]: employeeReducer\n 9 |     })\n10 |   ]\n11 | };"
  },
  {
    type: 'typescript',
    fileName: 'employee.facade.ts',
    source:
      "import { Injectable, inject } from '@angular/core';\nimport { toSignal } from '@angular/core/rxjs-interop';\nimport { Store } from '@ngrx/store';\nimport { EmployeeActions } from './employee.actions';\nimport { Employee } from './employee.model';\nimport {\n  selectEmployees,\n  selectEmployeesError,\n  selectEmployeesLoading\n} from './employee.selectors';\n\n@Injectable({ providedIn: 'root' })\nexport class EmployeeFacade {\n  readonly #store = inject(Store);\n\n  readonly state = {\n    value: toSignal(this.#store.select(selectEmployees), {\n      initialValue: [] as Employee[]\n    }),\n    loading: toSignal(this.#store.select(selectEmployeesLoading), {\n      initialValue: false\n    }),\n    error: toSignal(this.#store.select(selectEmployeesError), {\n      initialValue: null as string | null\n    })\n  };\n\n  constructor() {\n    this.#store.dispatch(EmployeeActions.seed());\n  }\n\n  replace(employees: Employee[]): void {\n    this.#store.dispatch(EmployeeActions.replace({ employees }));\n  }\n\n  reset(): void {\n    this.#store.dispatch(EmployeeActions.reset());\n  }\n}",
    numberedSource:
      " 1 | import { Injectable, inject } from '@angular/core';\n 2 | import { toSignal } from '@angular/core/rxjs-interop';\n 3 | import { Store } from '@ngrx/store';\n 4 | import { EmployeeActions } from './employee.actions';\n 5 | import { Employee } from './employee.model';\n 6 | import {\n 7 |   selectEmployees,\n 8 |   selectEmployeesError,\n 9 |   selectEmployeesLoading\n10 | } from './employee.selectors';\n11 | \n12 | @Injectable({ providedIn: 'root' })\n13 | export class EmployeeFacade {\n14 |   readonly #store = inject(Store);\n15 | \n16 |   readonly state = {\n17 |     value: toSignal(this.#store.select(selectEmployees), {\n18 |       initialValue: [] as Employee[]\n19 |     }),\n20 |     loading: toSignal(this.#store.select(selectEmployeesLoading), {\n21 |       initialValue: false\n22 |     }),\n23 |     error: toSignal(this.#store.select(selectEmployeesError), {\n24 |       initialValue: null as string | null\n25 |     })\n26 |   };\n27 | \n28 |   constructor() {\n29 |     this.#store.dispatch(EmployeeActions.seed());\n30 |   }\n31 | \n32 |   replace(employees: Employee[]): void {\n33 |     this.#store.dispatch(EmployeeActions.replace({ employees }));\n34 |   }\n35 | \n36 |   reset(): void {\n37 |     this.#store.dispatch(EmployeeActions.reset());\n38 |   }\n39 | }"
  },
  {
    type: 'typescript',
    fileName: 'example.component.ts',
    source:
      "import { CommonModule } from '@angular/common';\nimport { Component, inject } from '@angular/core';\nimport { EmployeeFacade } from './employee.facade';\n\n@Component({\n  selector: 'example-view',\n  standalone: true,\n  imports: [CommonModule],\n  templateUrl: './example.component.html'\n})\nexport class ExampleComponent {\n  #employeeFacade = inject(EmployeeFacade);\n\n  readonly state = this.#employeeFacade.state;\n\n  readonly sample = [\n    { id: 11, name: 'Luke' },\n    { id: 38, name: 'Leia' },\n    { id: 9, name: 'Han' }\n  ];\n\n  loadSample(): void {\n    this.#employeeFacade.replace(this.sample);\n  }\n\n  resetState(): void {\n    this.#employeeFacade.reset();\n  }\n}",
    numberedSource:
      " 1 | import { CommonModule } from '@angular/common';\n 2 | import { Component, inject } from '@angular/core';\n 3 | import { EmployeeFacade } from './employee.facade';\n 4 | \n 5 | @Component({\n 6 |   selector: 'example-view',\n 7 |   standalone: true,\n 8 |   imports: [CommonModule],\n 9 |   templateUrl: './example.component.html'\n10 | })\n11 | export class ExampleComponent {\n12 |   #employeeFacade = inject(EmployeeFacade);\n13 | \n14 |   readonly state = this.#employeeFacade.state;\n15 | \n16 |   readonly sample = [\n17 |     { id: 11, name: 'Luke' },\n18 |     { id: 38, name: 'Leia' },\n19 |     { id: 9, name: 'Han' }\n20 |   ];\n21 | \n22 |   loadSample(): void {\n23 |     this.#employeeFacade.replace(this.sample);\n24 |   }\n25 | \n26 |   resetState(): void {\n27 |     this.#employeeFacade.reset();\n28 |   }\n29 | }"
  },
  {
    type: 'html',
    fileName: 'example.component.html',
    source:
      '<div>\n  <div>\n    @if (state.loading()) {\n      <div>Loading...</div>\n    } @else if (state.error()) {\n      <div>{{ state.error() }}</div>\n    } @else {\n      <textarea readonly>{{ state.value() | json }}</textarea>\n    }\n  </div>\n\n  <div>\n    <button type="button" (click)="loadSample()">\n      Load Sample State\n    </button>\n\n    <button type="button" (click)="resetState()">\n      Reset State\n    </button>\n  </div>\n</div>',
    numberedSource:
      ' 1 | <div>\n 2 |   <div>\n 3 |     @if (state.loading()) {\n 4 |       <div>Loading...</div>\n 5 |     } @else if (state.error()) {\n 6 |       <div>{{ state.error() }}</div>\n 7 |     } @else {\n 8 |       <textarea readonly>{{ state.value() | json }}</textarea>\n 9 |     }\n10 |   </div>\n11 | \n12 |   <div>\n13 |     <button type="button" (click)="loadSample()">\n14 |       Load Sample State\n15 |     </button>\n16 | \n17 |     <button type="button" (click)="resetState()">\n18 |       Reset State\n19 |     </button>\n20 |   </div>\n21 | </div>'
  },
  {
    type: 'typescript',
    fileName: 'employee.model.ts',
    source: 'export interface Employee {\n  id: number;\n  name: string;\n}',
    numberedSource:
      '1 | export interface Employee {\n2 |   id: number;\n3 |   name: string;\n4 | }'
  },
  {
    type: 'typescript',
    fileName: 'employee.actions.ts',
    source:
      "import { createActionGroup, emptyProps, props } from '@ngrx/store';\nimport { Employee } from './employee.model';\n\nexport const EmployeeActions = createActionGroup({\n  source: 'Employees',\n  events: {\n    Seed: emptyProps(),\n    Replace: props<{ employees: Employee[] }>(),\n    Reset: emptyProps()\n  }\n});",
    numberedSource:
      " 1 | import { createActionGroup, emptyProps, props } from '@ngrx/store';\n 2 | import { Employee } from './employee.model';\n 3 | \n 4 | export const EmployeeActions = createActionGroup({\n 5 |   source: 'Employees',\n 6 |   events: {\n 7 |     Seed: emptyProps(),\n 8 |     Replace: props<{ employees: Employee[] }>(),\n 9 |     Reset: emptyProps()\n10 |   }\n11 | });"
  },
  {
    type: 'typescript',
    fileName: 'employee.state.ts',
    source:
      "import { Employee } from './employee.model';\n\nexport interface EmployeeState {\n  loading: boolean;\n  value: Employee[];\n  error: string | null;\n}\n\nexport const initialEmployeeState: EmployeeState = {\n  loading: false,\n  value: [],\n  error: null\n};",
    numberedSource:
      " 1 | import { Employee } from './employee.model';\n 2 | \n 3 | export interface EmployeeState {\n 4 |   loading: boolean;\n 5 |   value: Employee[];\n 6 |   error: string | null;\n 7 | }\n 8 | \n 9 | export const initialEmployeeState: EmployeeState = {\n10 |   loading: false,\n11 |   value: [],\n12 |   error: null\n13 | };"
  },
  {
    type: 'typescript',
    fileName: 'employee.reducer.ts',
    source:
      "import { createReducer, on } from '@ngrx/store';\nimport { EmployeeActions } from './employee.actions';\nimport { Employee } from './employee.model';\nimport { EmployeeState, initialEmployeeState } from './employee.state';\n\nexport const employeeFeatureKey = 'employees';\n\nconst seededEmployees = [\n  { id: 1, name: 'Ada' },\n  { id: 2, name: 'Brian' }\n];\n\nconst filterOddEmployees = (employees: Employee[]): Employee[] => {\n  return employees.filter((employee) => employee.id % 2 !== 0);\n};\n\nconst sortEmployeesByName = (employees: Employee[]): Employee[] => {\n  const sortedEmployees = [...employees];\n\n  sortedEmployees.sort((left, right) => left.name.localeCompare(right.name));\n\n  return sortedEmployees;\n};\n\nconst prepareEmployees = (employees: Employee[]): Employee[] => {\n  return sortEmployeesByName(filterOddEmployees(employees));\n};\n\nexport const employeeReducer = createReducer<EmployeeState>(\n  initialEmployeeState,\n  on(EmployeeActions.seed, (state) => ({\n    ...state,\n    loading: false,\n    value: prepareEmployees(seededEmployees),\n    error: null\n  })),\n  on(EmployeeActions.replace, (state, { employees }) => ({\n    ...state,\n    loading: false,\n    value: prepareEmployees(employees),\n    error: null\n  })),\n  on(EmployeeActions.reset, () => initialEmployeeState)\n);",
    numberedSource:
      " 1 | import { createReducer, on } from '@ngrx/store';\n 2 | import { EmployeeActions } from './employee.actions';\n 3 | import { Employee } from './employee.model';\n 4 | import { EmployeeState, initialEmployeeState } from './employee.state';\n 5 | \n 6 | export const employeeFeatureKey = 'employees';\n 7 | \n 8 | const seededEmployees = [\n 9 |   { id: 1, name: 'Ada' },\n10 |   { id: 2, name: 'Brian' }\n11 | ];\n12 | \n13 | const filterOddEmployees = (employees: Employee[]): Employee[] => {\n14 |   return employees.filter((employee) => employee.id % 2 !== 0);\n15 | };\n16 | \n17 | const sortEmployeesByName = (employees: Employee[]): Employee[] => {\n18 |   const sortedEmployees = [...employees];\n19 | \n20 |   sortedEmployees.sort((left, right) => left.name.localeCompare(right.name));\n21 | \n22 |   return sortedEmployees;\n23 | };\n24 | \n25 | const prepareEmployees = (employees: Employee[]): Employee[] => {\n26 |   return sortEmployeesByName(filterOddEmployees(employees));\n27 | };\n28 | \n29 | export const employeeReducer = createReducer<EmployeeState>(\n30 |   initialEmployeeState,\n31 |   on(EmployeeActions.seed, (state) => ({\n32 |     ...state,\n33 |     loading: false,\n34 |     value: prepareEmployees(seededEmployees),\n35 |     error: null\n36 |   })),\n37 |   on(EmployeeActions.replace, (state, { employees }) => ({\n38 |     ...state,\n39 |     loading: false,\n40 |     value: prepareEmployees(employees),\n41 |     error: null\n42 |   })),\n43 |   on(EmployeeActions.reset, () => initialEmployeeState)\n44 | );"
  },
  {
    type: 'typescript',
    fileName: 'employee.selectors.ts',
    source:
      "import { createFeatureSelector, createSelector } from '@ngrx/store';\nimport { employeeFeatureKey } from './employee.reducer';\nimport { EmployeeState } from './employee.state';\n\nexport const selectEmployeeState =\n  createFeatureSelector<EmployeeState>(employeeFeatureKey);\n\nexport const selectEmployees = createSelector(\n  selectEmployeeState,\n  (state) => state.value\n);\n\nexport const selectEmployeesLoading = createSelector(\n  selectEmployeeState,\n  (state) => state.loading\n);\n\nexport const selectEmployeesError = createSelector(\n  selectEmployeeState,\n  (state) => state.error\n);",
    numberedSource:
      " 1 | import { createFeatureSelector, createSelector } from '@ngrx/store';\n 2 | import { employeeFeatureKey } from './employee.reducer';\n 3 | import { EmployeeState } from './employee.state';\n 4 | \n 5 | export const selectEmployeeState =\n 6 |   createFeatureSelector<EmployeeState>(employeeFeatureKey);\n 7 | \n 8 | export const selectEmployees = createSelector(\n 9 |   selectEmployeeState,\n10 |   (state) => state.value\n11 | );\n12 | \n13 | export const selectEmployeesLoading = createSelector(\n14 |   selectEmployeeState,\n15 |   (state) => state.loading\n16 | );\n17 | \n18 | export const selectEmployeesError = createSelector(\n19 |   selectEmployeeState,\n20 |   (state) => state.error\n21 | );"
  }
] as const satisfies ReadonlyArray<{
  readonly type:
    'typescript' | 'html' | 'svelte' | 'vue' | 'scss' | 'json' | 'markdown';
  readonly fileName: string;
  readonly source: string;
  readonly numberedSource: string;
}>;
