/**
 * AUTO-GENERATED — do not edit manually.
 * Generated by: tools/sdux-comparison/sdux-comparison.mjs
 */
export const ANGULAR_REDUX_OUTPUT = [
  {
    type: 'typescript',
    fileName: 'main.ts',
    source:
      "import { bootstrapApplication } from '@angular/platform-browser';\nimport { appConfig } from './app.config';\nimport { ExampleComponent } from './example.component';\n\nbootstrapApplication(ExampleComponent, appConfig).catch((error: unknown) => {\n  console.error(error);\n});",
    numberedSource:
      "1 | import { bootstrapApplication } from '@angular/platform-browser';\n2 | import { appConfig } from './app.config';\n3 | import { ExampleComponent } from './example.component';\n4 | \n5 | bootstrapApplication(ExampleComponent, appConfig).catch((error: unknown) => {\n6 |   console.error(error);\n7 | });"
  },
  {
    type: 'typescript',
    fileName: 'app.config.ts',
    source:
      "import { ApplicationConfig } from '@angular/core';\nimport { provideEffects } from '@ngrx/effects';\nimport { provideStore } from '@ngrx/store';\nimport { EmployeeEffects } from './employee.effects';\nimport { employeeFeatureKey, employeeReducer } from './employee.reducer';\n\nexport const appConfig: ApplicationConfig = {\n  providers: [\n    provideEffects(EmployeeEffects),\n    provideStore({\n      [employeeFeatureKey]: employeeReducer\n    })\n  ]\n};",
    numberedSource:
      " 1 | import { ApplicationConfig } from '@angular/core';\n 2 | import { provideEffects } from '@ngrx/effects';\n 3 | import { provideStore } from '@ngrx/store';\n 4 | import { EmployeeEffects } from './employee.effects';\n 5 | import { employeeFeatureKey, employeeReducer } from './employee.reducer';\n 6 | \n 7 | export const appConfig: ApplicationConfig = {\n 8 |   providers: [\n 9 |     provideEffects(EmployeeEffects),\n10 |     provideStore({\n11 |       [employeeFeatureKey]: employeeReducer\n12 |     })\n13 |   ]\n14 | };"
  },
  {
    type: 'typescript',
    fileName: 'employee.facade.ts',
    source:
      "import { Injectable, inject } from '@angular/core';\nimport { toSignal } from '@angular/core/rxjs-interop';\nimport { Store } from '@ngrx/store';\nimport { EmployeeActions } from './employee.actions';\nimport { Employee } from './employee.model';\nimport {\n  selectEmployees,\n  selectEmployeesError,\n  selectEmployeesLoading\n} from './employee.selectors';\n\n@Injectable({ providedIn: 'root' })\nexport class EmployeeFacade {\n  readonly #store = inject(Store);\n\n  readonly state = {\n    employees: toSignal(this.#store.select(selectEmployees), {\n      initialValue: [] as Employee[]\n    }),\n    loading: toSignal(this.#store.select(selectEmployeesLoading), {\n      initialValue: false\n    }),\n    error: toSignal(this.#store.select(selectEmployeesError), {\n      initialValue: null as string | null\n    })\n  };\n\n  replace(employees: Employee[]): void {\n    this.#store.dispatch(EmployeeActions.replace({ employees }));\n  }\n\n  replaceAsync(): void {\n    this.#store.dispatch(EmployeeActions.replaceAsync());\n  }\n\n  reset(): void {\n    this.#store.dispatch(EmployeeActions.reset());\n  }\n}\n",
    numberedSource:
      " 1 | import { Injectable, inject } from '@angular/core';\n 2 | import { toSignal } from '@angular/core/rxjs-interop';\n 3 | import { Store } from '@ngrx/store';\n 4 | import { EmployeeActions } from './employee.actions';\n 5 | import { Employee } from './employee.model';\n 6 | import {\n 7 |   selectEmployees,\n 8 |   selectEmployeesError,\n 9 |   selectEmployeesLoading\n10 | } from './employee.selectors';\n11 | \n12 | @Injectable({ providedIn: 'root' })\n13 | export class EmployeeFacade {\n14 |   readonly #store = inject(Store);\n15 | \n16 |   readonly state = {\n17 |     employees: toSignal(this.#store.select(selectEmployees), {\n18 |       initialValue: [] as Employee[]\n19 |     }),\n20 |     loading: toSignal(this.#store.select(selectEmployeesLoading), {\n21 |       initialValue: false\n22 |     }),\n23 |     error: toSignal(this.#store.select(selectEmployeesError), {\n24 |       initialValue: null as string | null\n25 |     })\n26 |   };\n27 | \n28 |   replace(employees: Employee[]): void {\n29 |     this.#store.dispatch(EmployeeActions.replace({ employees }));\n30 |   }\n31 | \n32 |   replaceAsync(): void {\n33 |     this.#store.dispatch(EmployeeActions.replaceAsync());\n34 |   }\n35 | \n36 |   reset(): void {\n37 |     this.#store.dispatch(EmployeeActions.reset());\n38 |   }\n39 | }\n40 | "
  },
  {
    type: 'typescript',
    fileName: 'example.component.ts',
    source:
      "import { CommonModule } from '@angular/common';\nimport { Component, inject } from '@angular/core';\nimport { EmployeeFacade } from './employee.facade';\n\n@Component({\n  selector: 'example-view',\n  standalone: true,\n  imports: [CommonModule],\n  templateUrl: './example.component.html'\n})\nexport class ExampleComponent {\n  #employeeFacade = inject(EmployeeFacade);\n\n  readonly state = this.#employeeFacade.state;\n\n  readonly sample = [\n    { id: 11, name: 'Luke' },\n    { id: 38, name: 'Leia' },\n    { id: 9, name: 'Han' }\n  ];\n\n  loadSample(): void {\n    this.#employeeFacade.replace(this.sample);\n  }\n\n  loadSampleAsync(): void {\n    this.#employeeFacade.replaceAsync();\n  }\n\n  resetState(): void {\n    this.#employeeFacade.reset();\n  }\n}",
    numberedSource:
      " 1 | import { CommonModule } from '@angular/common';\n 2 | import { Component, inject } from '@angular/core';\n 3 | import { EmployeeFacade } from './employee.facade';\n 4 | \n 5 | @Component({\n 6 |   selector: 'example-view',\n 7 |   standalone: true,\n 8 |   imports: [CommonModule],\n 9 |   templateUrl: './example.component.html'\n10 | })\n11 | export class ExampleComponent {\n12 |   #employeeFacade = inject(EmployeeFacade);\n13 | \n14 |   readonly state = this.#employeeFacade.state;\n15 | \n16 |   readonly sample = [\n17 |     { id: 11, name: 'Luke' },\n18 |     { id: 38, name: 'Leia' },\n19 |     { id: 9, name: 'Han' }\n20 |   ];\n21 | \n22 |   loadSample(): void {\n23 |     this.#employeeFacade.replace(this.sample);\n24 |   }\n25 | \n26 |   loadSampleAsync(): void {\n27 |     this.#employeeFacade.replaceAsync();\n28 |   }\n29 | \n30 |   resetState(): void {\n31 |     this.#employeeFacade.reset();\n32 |   }\n33 | }"
  },
  {
    type: 'html',
    fileName: 'example.component.html',
    source:
      '<div>\n  <div>\n    @if (state.loading()) {\n      <div>Loading...</div>\n    } @else if (state.error()) {\n      <div>{{ state.error() }}</div>\n    } @else {\n      <textarea readonly>{{ state.employees() | json }}</textarea>\n    }\n  </div>\n\n  <div>\n    <button type="button" (click)="loadSample()">\n      Load Sample State\n    </button>\n\n    <button type="button" (click)="loadSampleAsync()">\n      Load Async State\n    </button>\n\n    <button type="button" (click)="resetState()">\n      Reset State\n    </button>\n  </div>\n</div>\n',
    numberedSource:
      ' 1 | <div>\n 2 |   <div>\n 3 |     @if (state.loading()) {\n 4 |       <div>Loading...</div>\n 5 |     } @else if (state.error()) {\n 6 |       <div>{{ state.error() }}</div>\n 7 |     } @else {\n 8 |       <textarea readonly>{{ state.employees() | json }}</textarea>\n 9 |     }\n10 |   </div>\n11 | \n12 |   <div>\n13 |     <button type="button" (click)="loadSample()">\n14 |       Load Sample State\n15 |     </button>\n16 | \n17 |     <button type="button" (click)="loadSampleAsync()">\n18 |       Load Async State\n19 |     </button>\n20 | \n21 |     <button type="button" (click)="resetState()">\n22 |       Reset State\n23 |     </button>\n24 |   </div>\n25 | </div>\n26 | '
  },
  {
    type: 'typescript',
    fileName: 'employee.model.ts',
    source: 'export interface Employee {\n  id: number;\n  name: string;\n}',
    numberedSource:
      '1 | export interface Employee {\n2 |   id: number;\n3 |   name: string;\n4 | }'
  },
  {
    type: 'typescript',
    fileName: 'employee.effects.ts',
    source:
      "import { Injectable, inject } from '@angular/core';\nimport { Actions, createEffect, ofType } from '@ngrx/effects';\nimport { EmployeeActions } from './employee.actions';\nimport { Employee } from './employee.model';\nimport { catchError, from, map, of, switchMap } from 'rxjs';\n\n@Injectable()\nexport class EmployeeEffects {\n  readonly #actions$ = inject(Actions);\n\n  readonly replaceAsync$ = createEffect(() => {\n    return this.#actions$.pipe(\n      ofType(EmployeeActions.replaceAsync),\n      switchMap(() => {\n        return from(\n          fetch('/api/employees').then((response) => {\n            if (!response.ok) {\n              throw new Error(`Failed to load employees (${response.status})`);\n            }\n\n            return response.json() as Promise<Employee[]>;\n          })\n        ).pipe(\n          map((employees) => EmployeeActions.replaceAsyncSuccess({ employees })),\n          catchError((error: unknown) => {\n            return of(\n              EmployeeActions.replaceAsyncFailure({\n                error:\n                  error instanceof Error ? error.message : 'Failed to load employees'\n              })\n            );\n          })\n        );\n      })\n    );\n  });\n}\n",
    numberedSource:
      " 1 | import { Injectable, inject } from '@angular/core';\n 2 | import { Actions, createEffect, ofType } from '@ngrx/effects';\n 3 | import { EmployeeActions } from './employee.actions';\n 4 | import { Employee } from './employee.model';\n 5 | import { catchError, from, map, of, switchMap } from 'rxjs';\n 6 | \n 7 | @Injectable()\n 8 | export class EmployeeEffects {\n 9 |   readonly #actions$ = inject(Actions);\n10 | \n11 |   readonly replaceAsync$ = createEffect(() => {\n12 |     return this.#actions$.pipe(\n13 |       ofType(EmployeeActions.replaceAsync),\n14 |       switchMap(() => {\n15 |         return from(\n16 |           fetch('/api/employees').then((response) => {\n17 |             if (!response.ok) {\n18 |               throw new Error(`Failed to load employees (${response.status})`);\n19 |             }\n20 | \n21 |             return response.json() as Promise<Employee[]>;\n22 |           })\n23 |         ).pipe(\n24 |           map((employees) => EmployeeActions.replaceAsyncSuccess({ employees })),\n25 |           catchError((error: unknown) => {\n26 |             return of(\n27 |               EmployeeActions.replaceAsyncFailure({\n28 |                 error:\n29 |                   error instanceof Error ? error.message : 'Failed to load employees'\n30 |               })\n31 |             );\n32 |           })\n33 |         );\n34 |       })\n35 |     );\n36 |   });\n37 | }\n38 | "
  },
  {
    type: 'typescript',
    fileName: 'employee.actions.ts',
    source:
      "import { createActionGroup, emptyProps, props } from '@ngrx/store';\nimport { Employee } from './employee.model';\n\nexport const EmployeeActions = createActionGroup({\n  source: 'Employees',\n  events: {\n    Replace: props<{ employees: Employee[] }>(),\n    'Replace Async': emptyProps(),\n    'Replace Async Success': props<{ employees: Employee[] }>(),\n    'Replace Async Failure': props<{ error: string }>(),\n    Reset: emptyProps()\n  }\n});",
    numberedSource:
      " 1 | import { createActionGroup, emptyProps, props } from '@ngrx/store';\n 2 | import { Employee } from './employee.model';\n 3 | \n 4 | export const EmployeeActions = createActionGroup({\n 5 |   source: 'Employees',\n 6 |   events: {\n 7 |     Replace: props<{ employees: Employee[] }>(),\n 8 |     'Replace Async': emptyProps(),\n 9 |     'Replace Async Success': props<{ employees: Employee[] }>(),\n10 |     'Replace Async Failure': props<{ error: string }>(),\n11 |     Reset: emptyProps()\n12 |   }\n13 | });"
  },
  {
    type: 'typescript',
    fileName: 'employee.state.ts',
    source:
      "import { Employee } from './employee.model';\n\nexport interface EmployeeState {\n  loading: boolean;\n  employees: Employee[];\n  error: string | null;\n}\n\nexport const initialEmployeeState: EmployeeState = {\n  loading: false,\n  employees: [],\n  error: null\n};\n",
    numberedSource:
      " 1 | import { Employee } from './employee.model';\n 2 | \n 3 | export interface EmployeeState {\n 4 |   loading: boolean;\n 5 |   employees: Employee[];\n 6 |   error: string | null;\n 7 | }\n 8 | \n 9 | export const initialEmployeeState: EmployeeState = {\n10 |   loading: false,\n11 |   employees: [],\n12 |   error: null\n13 | };\n14 | "
  },
  {
    type: 'typescript',
    fileName: 'employee.reducer.ts',
    source:
      "import { createReducer, on } from '@ngrx/store';\nimport { EmployeeActions } from './employee.actions';\nimport { Employee } from './employee.model';\nimport { EmployeeState, initialEmployeeState } from './employee.state';\n\nexport const employeeFeatureKey = 'employees';\n\nconst filterOddEmployees = (employees: Employee[]): Employee[] => {\n  return employees.filter((employee) => employee.id % 2 !== 0);\n};\n\nconst sortEmployeesByName = (employees: Employee[]): Employee[] => {\n  const sortedEmployees = [...employees];\n\n  sortedEmployees.sort((left, right) => left.name.localeCompare(right.name));\n\n  return sortedEmployees;\n};\n\nconst prepareEmployees = (employees: Employee[]): Employee[] => {\n  return sortEmployeesByName(filterOddEmployees(employees));\n};\n\nexport const employeeReducer = createReducer<EmployeeState>(\n  initialEmployeeState,\n  on(EmployeeActions.replace, (state, { employees }) => ({\n    ...state,\n    loading: false,\n    employees: prepareEmployees(employees),\n    error: null\n  })),\n  on(EmployeeActions.replaceAsync, (state) => ({\n    ...state,\n    loading: true,\n    error: null\n  })),\n  on(EmployeeActions.replaceAsyncSuccess, (state, { employees }) => ({\n    ...state,\n    loading: false,\n    employees: prepareEmployees(employees),\n    error: null\n  })),\n  on(EmployeeActions.replaceAsyncFailure, (state, { error }) => ({\n    ...state,\n    loading: false,\n    error\n  })),\n  on(EmployeeActions.reset, () => initialEmployeeState)\n);\n",
    numberedSource:
      " 1 | import { createReducer, on } from '@ngrx/store';\n 2 | import { EmployeeActions } from './employee.actions';\n 3 | import { Employee } from './employee.model';\n 4 | import { EmployeeState, initialEmployeeState } from './employee.state';\n 5 | \n 6 | export const employeeFeatureKey = 'employees';\n 7 | \n 8 | const filterOddEmployees = (employees: Employee[]): Employee[] => {\n 9 |   return employees.filter((employee) => employee.id % 2 !== 0);\n10 | };\n11 | \n12 | const sortEmployeesByName = (employees: Employee[]): Employee[] => {\n13 |   const sortedEmployees = [...employees];\n14 | \n15 |   sortedEmployees.sort((left, right) => left.name.localeCompare(right.name));\n16 | \n17 |   return sortedEmployees;\n18 | };\n19 | \n20 | const prepareEmployees = (employees: Employee[]): Employee[] => {\n21 |   return sortEmployeesByName(filterOddEmployees(employees));\n22 | };\n23 | \n24 | export const employeeReducer = createReducer<EmployeeState>(\n25 |   initialEmployeeState,\n26 |   on(EmployeeActions.replace, (state, { employees }) => ({\n27 |     ...state,\n28 |     loading: false,\n29 |     employees: prepareEmployees(employees),\n30 |     error: null\n31 |   })),\n32 |   on(EmployeeActions.replaceAsync, (state) => ({\n33 |     ...state,\n34 |     loading: true,\n35 |     error: null\n36 |   })),\n37 |   on(EmployeeActions.replaceAsyncSuccess, (state, { employees }) => ({\n38 |     ...state,\n39 |     loading: false,\n40 |     employees: prepareEmployees(employees),\n41 |     error: null\n42 |   })),\n43 |   on(EmployeeActions.replaceAsyncFailure, (state, { error }) => ({\n44 |     ...state,\n45 |     loading: false,\n46 |     error\n47 |   })),\n48 |   on(EmployeeActions.reset, () => initialEmployeeState)\n49 | );\n50 | "
  },
  {
    type: 'typescript',
    fileName: 'employee.selectors.ts',
    source:
      "import { createFeatureSelector, createSelector } from '@ngrx/store';\nimport { employeeFeatureKey } from './employee.reducer';\nimport { EmployeeState } from './employee.state';\n\nexport const selectEmployeeState =\n  createFeatureSelector<EmployeeState>(employeeFeatureKey);\n\nexport const selectEmployees = createSelector(\n  selectEmployeeState,\n  (state) => state.employees\n);\n\nexport const selectEmployeesLoading = createSelector(\n  selectEmployeeState,\n  (state) => state.loading\n);\n\nexport const selectEmployeesError = createSelector(\n  selectEmployeeState,\n  (state) => state.error\n);\n",
    numberedSource:
      " 1 | import { createFeatureSelector, createSelector } from '@ngrx/store';\n 2 | import { employeeFeatureKey } from './employee.reducer';\n 3 | import { EmployeeState } from './employee.state';\n 4 | \n 5 | export const selectEmployeeState =\n 6 |   createFeatureSelector<EmployeeState>(employeeFeatureKey);\n 7 | \n 8 | export const selectEmployees = createSelector(\n 9 |   selectEmployeeState,\n10 |   (state) => state.employees\n11 | );\n12 | \n13 | export const selectEmployeesLoading = createSelector(\n14 |   selectEmployeeState,\n15 |   (state) => state.loading\n16 | );\n17 | \n18 | export const selectEmployeesError = createSelector(\n19 |   selectEmployeeState,\n20 |   (state) => state.error\n21 | );\n22 | "
  }
] as const satisfies ReadonlyArray<{
  readonly type:
    'typescript' | 'html' | 'svelte' | 'vue' | 'scss' | 'json' | 'markdown';
  readonly fileName: string;
  readonly source: string;
  readonly numberedSource: string;
}>;
