// --- AI Model File Path (DO NOT DELETE) ---
// FilePath: tools > documentation > component-generator > tests > component-generator.spec.mjs
// Updated: 2026-03-12 14:33
//	 Generated by pathcomment [tab] (see .vscode/typescript.code-snippets) or
//	 cmd+alt+j (see .vscode/keybindings.json)
// --- END AI MODEL FILE PATH ---

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { compareFiles } from '../../../utils/testing/compare-files.helper.mjs';
import { parseFilePath } from '../../../utils/testing/parse-file-path.helper.mjs';
import { ComponentGenerator } from '../component-generator.class.mjs';
import { ARTIFACTS } from './artifacts/input-files/artifact-file.ts.mjs';
import { COMPODOCS } from './artifacts/input-files/compodocs-file.ts.mjs';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

describe('CLI: component-generator.mjs', () => {
  let componentGenerator;
  let filesExist = [];
  const existsSync = [];
  const readFileSync = [];
  const writeFileSync = [];
  const mkdirSync = [];
  const output = [];
  let warnSpy;
  let isMalformedCompodocs = false;

  beforeEach(() => {
    isMalformedCompodocs = false;
    spyOn(Date.prototype, 'toLocaleString').and.returnValue(
      '11/25/2025, 8:33:29 PM'
    );
    warnSpy = spyOn(console, 'warn');
    existsSync.length = 0;
    readFileSync.length = 0;
    writeFileSync.length = 0;
    mkdirSync.length = 0;
    output.length = 0;

    spyOn(fs, 'readFileSync').and.callFake((filename) => {
      filename = parseFilePath(filename);
      readFileSync.push(filename);
      if (filename === 'compodocs') {
        if (isMalformedCompodocs) {
          return '}-//';
        } else {
          return JSON.stringify(COMPODOCS);
        }
      } else {
        return JSON.stringify(ARTIFACTS);
      }
    });
    spyOn(fs, 'writeFileSync').and.callFake((filename, data) => {
      output.push(data);
      writeFileSync.push(parseFilePath(filename));
    });
    spyOn(fs, 'mkdirSync').and.callFake((filename) => {
      mkdirSync.push(parseFilePath(filename));
    });
    spyOn(fs, 'existsSync').and.callFake((filename) => {
      existsSync.push(parseFilePath(filename));
      return filesExist.shift();
    });
  });

  it('should run the generator CLI and build an example', async () => {
    filesExist = [true, true, true];

    componentGenerator = new ComponentGenerator(
      'artifact-file',
      'output-dir',
      'compodocs'
    );
    await componentGenerator.run();

    expect(existsSync)
      .withContext('existsSync')
      .toEqual(['artifact-file', 'output-dir', 'compodocs']);

    expect(readFileSync)
      .withContext('readFileSync')
      .toEqual(['compodocs', 'artifact-file']);

    expect(writeFileSync)
      .withContext('writeFileSync')
      .toEqual([
        'classes/value-resolve-example-component.component.ts',
        'classes/abstract-active-controller.component.ts',
        'interfaces/bank-employee-model.component.ts',
        'const/dev-mode.component.ts',
        'const/cache-ttl.component.ts',
        'const/behavior_meta.component.ts',
        'functions/is-defined.component.ts',
        'functions/is-http-resource-ref.component.ts',
        'decorators/vault-behavior.component.ts',
        'types/behavior-type.component.ts'
      ]);

    expect(mkdirSync)
      .withContext('mkdirSync')
      .toEqual([
        'output-dir/classes',
        'output-dir/classes',
        'output-dir/interfaces',
        'output-dir/const',
        'output-dir/const',
        'output-dir/const',
        'output-dir/functions',
        'output-dir/functions',
        'output-dir/decorators',
        'output-dir/types'
      ]);

    expect(
      compareFiles(
        output.join('\n'),
        '01-component-generator.golden.txt',
        __dirname
      )
    )
      .withContext('output')
      .toBeTrue();

    expect(warnSpy).toHaveBeenCalledTimes(14);
    expect(warnSpy).toHaveBeenCalledWith('Loaded type index: artifact-file');
    expect(warnSpy).toHaveBeenCalledWith('Output directory: output-dir');
    expect(warnSpy).toHaveBeenCalledWith(
      'Generated: output-dir/classes/value-resolve-example-component.component.ts'
    );

    expect(warnSpy).toHaveBeenCalledWith(
      'Generated: output-dir/decorators/vault-behavior.component.ts'
    );

    expect(warnSpy).toHaveBeenCalledWith(
      'Generated: output-dir/types/behavior-type.component.ts'
    );

    expect(warnSpy).toHaveBeenCalledWith(
      'Generated: output-dir/functions/is-http-resource-ref.component.ts'
    );
    expect(warnSpy).toHaveBeenCalledWith(
      'Generated: output-dir/functions/is-defined.component.ts'
    );

    expect(warnSpy).toHaveBeenCalledWith(
      'Generated: output-dir/const/dev-mode.component.ts'
    );
    expect(warnSpy).toHaveBeenCalledWith(
      'Generated: output-dir/const/cache-ttl.component.ts'
    );
    expect(warnSpy).toHaveBeenCalledWith(
      'Generated: output-dir/const/behavior_meta.component.ts'
    );

    expect(warnSpy).toHaveBeenCalledWith(
      'Generated: output-dir/classes/abstract-active-controller.component.ts'
    );
    expect(warnSpy).toHaveBeenCalledWith(
      'Generated: output-dir/interfaces/bank-employee-model.component.ts'
    );

    expect(warnSpy).toHaveBeenCalledWith(
      'Documentation components created successfully!'
    );
    expect(warnSpy).toHaveBeenCalledWith(
      'Skipping NoDocLink (missing docLink)'
    );
  });

  describe('error', () => {
    it('should throw without an outputPath', async () => {
      filesExist = [true, false];

      expect(
        () => new ComponentGenerator('index', 'output', 'compodocs')
      ).toThrowError('Output directory not found: output');
    });

    it('should throw without an indexPath', async () => {
      filesExist = [false];

      expect(
        () => new ComponentGenerator('index', 'output', 'compodocs')
      ).toThrowError('Artifact file not found: index');
    });

    it('should throw without a compodocs param', async () => {
      filesExist = [true, true];

      await expectAsync(
        new ComponentGenerator('index', 'output').run()
      ).toBeRejectedWithError('Compodocs path was not provided.');
    });

    it('should throw without the compodocs file', async () => {
      filesExist = [true, true, false];

      await expectAsync(
        new ComponentGenerator('index', 'output', 'compodocs').run()
      ).toBeRejectedWithError('Compodocs file not found: compodocs');
    });

    it('should throw with a malformed compodocs file', async () => {
      filesExist = [true, true, true];
      isMalformedCompodocs = true;

      await expectAsync(
        new ComponentGenerator('index', 'output', 'compodocs').run()
      ).toBeRejectedWithError(
        `Failed to parse Compodocs JSON at compodocs: Unexpected token '}', "}-//" is not valid JSON`
      );
    });
  });
});
