/**
 * AUTO-GENERATED — do not edit manually.
 * Generated by: tools/sdux-comparison/sdux-comparison.mjs
 */
export const REACT_SDUX_OUTPUT_METADATA = {
  competitorTotalLines: 143,
  sduxTotalLines: 113,
  lineDifference: 30,
  percentageSavings: 20.98
} as const;

export const REACT_SDUX_OUTPUT = [
  {
    type: 'typescript',
    fileName: 'main.tsx',
    source:
      "import { StrictMode } from 'react';\nimport { createRoot } from 'react-dom/client';\nimport { ExampleView } from './ExampleView';\n\ncreateRoot(document.getElementById('root')!).render(\n  <StrictMode>\n    <ExampleView />\n  </StrictMode>\n);\n",
    numberedSource:
      " 1 | import { StrictMode } from 'react';\n 2 | import { createRoot } from 'react-dom/client';\n 3 | import { ExampleView } from './ExampleView';\n 4 | \n 5 | createRoot(document.getElementById('root')!).render(\n 6 |   <StrictMode>\n 7 |     <ExampleView />\n 8 |   </StrictMode>\n 9 | );\n10 | "
  },
  {
    type: 'typescript',
    fileName: 'employee.cell.ts',
    source:
      "import { FeatureCell, Vault } from '@sdux-vault/react';\nimport { Employee } from './employee.model';\n\nVault({\n  logLevel: 'off'\n});\n\nexport const employeeCell = FeatureCell<Employee[]>({\n  key: 'employees',\n  initialState: []\n});\n\nemployeeCell\n  .filters([\n    (examples: Employee[]) => examples.filter((example) => example.id % 2 !== 0)\n  ])\n  .reducers([\n    (examples: Employee[]) => {\n      examples.sort((left, right) => left.name.localeCompare(right.name));\n      return examples;\n    }\n  ])\n  .initialize();\n\nexport function replaceEmployees(employees: Employee[]): void {\n  employeeCell.replaceState({\n    value: employees\n  });\n}\n\nexport function replaceEmployeesAsync(): void {\n  employeeCell.replaceState({\n    value: () => fetch('/api/employees').then((response) => response.json())\n  });\n}\n\nexport function resetEmployees(): void {\n  employeeCell.reset();\n}\n",
    numberedSource:
      " 1 | import { FeatureCell, Vault } from '@sdux-vault/react';\n 2 | import { Employee } from './employee.model';\n 3 | \n 4 | Vault({\n 5 |   logLevel: 'off'\n 6 | });\n 7 | \n 8 | export const employeeCell = FeatureCell<Employee[]>({\n 9 |   key: 'employees',\n10 |   initialState: []\n11 | });\n12 | \n13 | employeeCell\n14 |   .filters([\n15 |     (examples: Employee[]) => examples.filter((example) => example.id % 2 !== 0)\n16 |   ])\n17 |   .reducers([\n18 |     (examples: Employee[]) => {\n19 |       examples.sort((left, right) => left.name.localeCompare(right.name));\n20 |       return examples;\n21 |     }\n22 |   ])\n23 |   .initialize();\n24 | \n25 | export function replaceEmployees(employees: Employee[]): void {\n26 |   employeeCell.replaceState({\n27 |     value: employees\n28 |   });\n29 | }\n30 | \n31 | export function replaceEmployeesAsync(): void {\n32 |   employeeCell.replaceState({\n33 |     value: () => fetch('/api/employees').then((response) => response.json())\n34 |   });\n35 | }\n36 | \n37 | export function resetEmployees(): void {\n38 |   employeeCell.reset();\n39 | }\n40 | "
  },
  {
    type: 'typescript',
    fileName: 'ExampleView.tsx',
    source:
      "import {\n  employeeCell,\n  replaceEmployees,\n  replaceEmployeesAsync,\n  resetEmployees\n} from './employee.cell';\nimport { Employee } from './employee.model';\n\nconst sample: Employee[] = [\n  { id: 11, name: 'Luke' },\n  { id: 38, name: 'Leia' },\n  { id: 9, name: 'Han' }\n];\n\nexport function ExampleView() {\n  const snapshot = employeeCell.useSyncExternalStore();\n\n  const loadSample = () => {\n    replaceEmployees(sample);\n  };\n\n  const loadSampleAsync = () => {\n    replaceEmployeesAsync();\n  };\n\n  const resetState = () => {\n    resetEmployees();\n  };\n\n  return (\n    <div>\n      <div>\n        {snapshot.isLoading ? (\n          <div>Loading...</div>\n        ) : snapshot.error ? (\n          <div>{String(snapshot.error)}</div>\n        ) : (\n          <textarea readOnly value={JSON.stringify(snapshot.value ?? [], null, 2)} />\n        )}\n      </div>\n\n      <div>\n        <button type=\"button\" onClick={loadSample}>\n          Load Sample State\n        </button>\n\n        <button type=\"button\" onClick={loadSampleAsync}>\n          Load Async State\n        </button>\n\n        <button type=\"button\" onClick={resetState}>\n          Reset State\n        </button>\n      </div>\n    </div>\n  );\n}\n",
    numberedSource:
      " 1 | import {\n 2 |   employeeCell,\n 3 |   replaceEmployees,\n 4 |   replaceEmployeesAsync,\n 5 |   resetEmployees\n 6 | } from './employee.cell';\n 7 | import { Employee } from './employee.model';\n 8 | \n 9 | const sample: Employee[] = [\n10 |   { id: 11, name: 'Luke' },\n11 |   { id: 38, name: 'Leia' },\n12 |   { id: 9, name: 'Han' }\n13 | ];\n14 | \n15 | export function ExampleView() {\n16 |   const snapshot = employeeCell.useSyncExternalStore();\n17 | \n18 |   const loadSample = () => {\n19 |     replaceEmployees(sample);\n20 |   };\n21 | \n22 |   const loadSampleAsync = () => {\n23 |     replaceEmployeesAsync();\n24 |   };\n25 | \n26 |   const resetState = () => {\n27 |     resetEmployees();\n28 |   };\n29 | \n30 |   return (\n31 |     <div>\n32 |       <div>\n33 |         {snapshot.isLoading ? (\n34 |           <div>Loading...</div>\n35 |         ) : snapshot.error ? (\n36 |           <div>{String(snapshot.error)}</div>\n37 |         ) : (\n38 |           <textarea readOnly value={JSON.stringify(snapshot.value ?? [], null, 2)} />\n39 |         )}\n40 |       </div>\n41 | \n42 |       <div>\n43 |         <button type=\"button\" onClick={loadSample}>\n44 |           Load Sample State\n45 |         </button>\n46 | \n47 |         <button type=\"button\" onClick={loadSampleAsync}>\n48 |           Load Async State\n49 |         </button>\n50 | \n51 |         <button type=\"button\" onClick={resetState}>\n52 |           Reset State\n53 |         </button>\n54 |       </div>\n55 |     </div>\n56 |   );\n57 | }\n58 | "
  },
  {
    type: 'typescript',
    fileName: 'employee.model.ts',
    source: 'export interface Employee {\n  id: number;\n  name: string;\n}\n',
    numberedSource:
      '1 | export interface Employee {\n2 |   id: number;\n3 |   name: string;\n4 | }\n5 | '
  }
] as const satisfies ReadonlyArray<{
  readonly type:
    'typescript' | 'html' | 'svelte' | 'vue' | 'scss' | 'json' | 'markdown';
  readonly fileName: string;
  readonly source: string;
  readonly numberedSource: string;
}>;
