/**
 * AUTO-GENERATED — do not edit manually.
 * Generated by: tools/sdux-comparison/sdux-comparison.mjs
 */
export const REACT_SDUX_OUTPUT = [
  {
    type: 'typescript',
    fileName: 'main.tsx',
    source:
      "import { StrictMode } from 'react';\nimport { createRoot } from 'react-dom/client';\nimport { ExampleView } from './ExampleView';\n\ncreateRoot(document.getElementById('root')!).render(\n  <StrictMode>\n    <ExampleView />\n  </StrictMode>\n);",
    numberedSource:
      "1 | import { StrictMode } from 'react';\n2 | import { createRoot } from 'react-dom/client';\n3 | import { ExampleView } from './ExampleView';\n4 | \n5 | createRoot(document.getElementById('root')!).render(\n6 |   <StrictMode>\n7 |     <ExampleView />\n8 |   </StrictMode>\n9 | );"
  },
  {
    type: 'typescript',
    fileName: 'employee.cell.ts',
    source:
      "import { FeatureCell, Vault } from '@sdux-vault/react';\nimport { Employee } from './employee.model';\n\nVault({\n  logLevel: 'off'\n});\n\nexport const employeeCell = FeatureCell<Employee[]>({\n  key: 'employees',\n  initialState: []\n});\n\nemployeeCell\n  .filters([\n    (examples: Employee[]) =>\n      examples.filter((example) => example.id % 2 !== 0)\n  ])\n  .reducers([\n    (examples: Employee[]) => {\n      examples.sort((left, right) => left.name.localeCompare(right.name));\n      return examples;\n    }\n  ])\n  .initialize();",
    numberedSource:
      " 1 | import { FeatureCell, Vault } from '@sdux-vault/react';\n 2 | import { Employee } from './employee.model';\n 3 | \n 4 | Vault({\n 5 |   logLevel: 'off'\n 6 | });\n 7 | \n 8 | export const employeeCell = FeatureCell<Employee[]>({\n 9 |   key: 'employees',\n10 |   initialState: []\n11 | });\n12 | \n13 | employeeCell\n14 |   .filters([\n15 |     (examples: Employee[]) =>\n16 |       examples.filter((example) => example.id % 2 !== 0)\n17 |   ])\n18 |   .reducers([\n19 |     (examples: Employee[]) => {\n20 |       examples.sort((left, right) => left.name.localeCompare(right.name));\n21 |       return examples;\n22 |     }\n23 |   ])\n24 |   .initialize();"
  },
  {
    type: 'typescript',
    fileName: 'ExampleView.tsx',
    source:
      "import { employeeCell } from './employee.cell';\nimport { Employee } from './employee.model';\n\nconst sample: Employee[] = [\n  { id: 11, name: 'Luke' },\n  { id: 38, name: 'Leia' },\n  { id: 9, name: 'Han' }\n];\n\nexport function ExampleView() {\n  const snapshot = employeeCell.useSyncExternalStore();\n\n  const loadSample = () => {\n    employeeCell.replaceState({ value: sample });\n  };\n\n  const resetState = () => {\n    employeeCell.reset();\n  };\n\n  return (\n    <div>\n      <div>\n        {snapshot.isLoading ? (\n          <div>Loading...</div>\n        ) : snapshot.error ? (\n          <div>{String(snapshot.error)}</div>\n        ) : (\n          <textarea readOnly value={JSON.stringify(snapshot.value ?? [], null, 2)} />\n        )}\n      </div>\n\n      <div>\n        <button type=\"button\" onClick={loadSample}>\n          Load Sample State\n        </button>\n\n        <button type=\"button\" onClick={resetState}>\n          Reset State\n        </button>\n      </div>\n    </div>\n  );\n}",
    numberedSource:
      " 1 | import { employeeCell } from './employee.cell';\n 2 | import { Employee } from './employee.model';\n 3 | \n 4 | const sample: Employee[] = [\n 5 |   { id: 11, name: 'Luke' },\n 6 |   { id: 38, name: 'Leia' },\n 7 |   { id: 9, name: 'Han' }\n 8 | ];\n 9 | \n10 | export function ExampleView() {\n11 |   const snapshot = employeeCell.useSyncExternalStore();\n12 | \n13 |   const loadSample = () => {\n14 |     employeeCell.replaceState({ value: sample });\n15 |   };\n16 | \n17 |   const resetState = () => {\n18 |     employeeCell.reset();\n19 |   };\n20 | \n21 |   return (\n22 |     <div>\n23 |       <div>\n24 |         {snapshot.isLoading ? (\n25 |           <div>Loading...</div>\n26 |         ) : snapshot.error ? (\n27 |           <div>{String(snapshot.error)}</div>\n28 |         ) : (\n29 |           <textarea readOnly value={JSON.stringify(snapshot.value ?? [], null, 2)} />\n30 |         )}\n31 |       </div>\n32 | \n33 |       <div>\n34 |         <button type=\"button\" onClick={loadSample}>\n35 |           Load Sample State\n36 |         </button>\n37 | \n38 |         <button type=\"button\" onClick={resetState}>\n39 |           Reset State\n40 |         </button>\n41 |       </div>\n42 |     </div>\n43 |   );\n44 | }"
  },
  {
    type: 'typescript',
    fileName: 'employee.model.ts',
    source: 'export interface Employee {\n  id: number;\n  name: string;\n}',
    numberedSource:
      '1 | export interface Employee {\n2 |   id: number;\n3 |   name: string;\n4 | }'
  }
] as const satisfies ReadonlyArray<{
  readonly type:
    'typescript' | 'html' | 'svelte' | 'vue' | 'scss' | 'json' | 'markdown';
  readonly fileName: string;
  readonly source: string;
  readonly numberedSource: string;
}>;
