/**
 * AUTO-GENERATED — do not edit manually.
 * Generated by: tools/sdux-comparison/sdux-comparison.mjs
 */
export const VUE_SDUX_OUTPUT = [
  {
    type: 'typescript',
    fileName: 'main.ts',
    source:
      "import { createApp } from 'vue';\nimport App from './App.vue';\n\ncreateApp(App).mount('#app');",
    numberedSource:
      "1 | import { createApp } from 'vue';\n2 | import App from './App.vue';\n3 | \n4 | createApp(App).mount('#app');"
  },
  {
    type: 'vue',
    fileName: 'App.vue',
    source:
      '<script setup lang="ts">\nimport ExampleView from \'./ExampleView.vue\';\n</script>\n\n<template>\n  <ExampleView />\n</template>',
    numberedSource:
      '1 | <script setup lang="ts">\n2 | import ExampleView from \'./ExampleView.vue\';\n3 | </script>\n4 | \n5 | <template>\n6 |   <ExampleView />\n7 | </template>'
  },
  {
    type: 'typescript',
    fileName: 'employee.cell.ts',
    source:
      "import { FeatureCell, Vault } from '@sdux-vault/vue';\nimport { Employee } from './employee.model';\n\nVault({\n  logLevel: 'off'\n});\n\nexport const employeeCell = FeatureCell<Employee[]>({\n  key: 'employees',\n  initialState: []\n});\n\nemployeeCell\n  .filters([\n    (examples: Employee[]) =>\n      examples.filter((example) => example.id % 2 !== 0)\n  ])\n  .reducers([\n    (examples: Employee[]) => {\n      examples.sort((left, right) => left.name.localeCompare(right.name));\n      return examples;\n    }\n  ])\n  .initialize();",
    numberedSource:
      " 1 | import { FeatureCell, Vault } from '@sdux-vault/vue';\n 2 | import { Employee } from './employee.model';\n 3 | \n 4 | Vault({\n 5 |   logLevel: 'off'\n 6 | });\n 7 | \n 8 | export const employeeCell = FeatureCell<Employee[]>({\n 9 |   key: 'employees',\n10 |   initialState: []\n11 | });\n12 | \n13 | employeeCell\n14 |   .filters([\n15 |     (examples: Employee[]) =>\n16 |       examples.filter((example) => example.id % 2 !== 0)\n17 |   ])\n18 |   .reducers([\n19 |     (examples: Employee[]) => {\n20 |       examples.sort((left, right) => left.name.localeCompare(right.name));\n21 |       return examples;\n22 |     }\n23 |   ])\n24 |   .initialize();"
  },
  {
    type: 'vue',
    fileName: 'ExampleView.vue',
    source:
      '<script setup lang="ts">\nimport { employeeCell } from \'./employee.cell\';\nimport { Employee } from \'./employee.model\';\n\nconst sample: Employee[] = [\n  { id: 11, name: \'Luke\' },\n  { id: 38, name: \'Leia\' },\n  { id: 9, name: \'Han\' }\n];\n\nconst snapshot = employeeCell.useReactiveState();\n\nfunction loadSample(): void {\n  employeeCell.replaceState({ value: sample });\n}\n\nfunction resetState(): void {\n  employeeCell.reset();\n}\n</script>\n\n<template>\n  <div>\n    <div>\n      <div v-if="snapshot.isLoading">Loading...</div>\n      <div v-else-if="snapshot.error" v-text="String(snapshot.error)" />\n      <textarea v-else readonly :value="JSON.stringify(snapshot.value ?? [], null, 2)" />\n    </div>\n\n    <div>\n      <button type="button" @click="loadSample">Load Sample State</button>\n\n      <button type="button" @click="resetState">Reset State</button>\n    </div>\n  </div>\n</template>',
    numberedSource:
      ' 1 | <script setup lang="ts">\n 2 | import { employeeCell } from \'./employee.cell\';\n 3 | import { Employee } from \'./employee.model\';\n 4 | \n 5 | const sample: Employee[] = [\n 6 |   { id: 11, name: \'Luke\' },\n 7 |   { id: 38, name: \'Leia\' },\n 8 |   { id: 9, name: \'Han\' }\n 9 | ];\n10 | \n11 | const snapshot = employeeCell.useReactiveState();\n12 | \n13 | function loadSample(): void {\n14 |   employeeCell.replaceState({ value: sample });\n15 | }\n16 | \n17 | function resetState(): void {\n18 |   employeeCell.reset();\n19 | }\n20 | </script>\n21 | \n22 | <template>\n23 |   <div>\n24 |     <div>\n25 |       <div v-if="snapshot.isLoading">Loading...</div>\n26 |       <div v-else-if="snapshot.error" v-text="String(snapshot.error)" />\n27 |       <textarea v-else readonly :value="JSON.stringify(snapshot.value ?? [], null, 2)" />\n28 |     </div>\n29 | \n30 |     <div>\n31 |       <button type="button" @click="loadSample">Load Sample State</button>\n32 | \n33 |       <button type="button" @click="resetState">Reset State</button>\n34 |     </div>\n35 |   </div>\n36 | </template>'
  },
  {
    type: 'typescript',
    fileName: 'employee.model.ts',
    source: 'export interface Employee {\n  id: number;\n  name: string;\n}',
    numberedSource:
      '1 | export interface Employee {\n2 |   id: number;\n3 |   name: string;\n4 | }'
  }
] as const satisfies ReadonlyArray<{
  readonly type:
    'typescript' | 'html' | 'svelte' | 'vue' | 'scss' | 'json' | 'markdown';
  readonly fileName: string;
  readonly source: string;
  readonly numberedSource: string;
}>;
