/**
 * AUTO-GENERATED — do not edit manually.
 * Generated by: tools/sdux-comparison/sdux-comparison.mjs
 */
export const VUE_SDUX_OUTPUT_METADATA = {
  competitorTotalLines: 118,
  sduxTotalLines: 102,
  lineDifference: 16,
  percentageSavings: 13.56
} as const;

export const VUE_SDUX_OUTPUT = [
  {
    type: 'typescript',
    fileName: 'main.ts',
    source:
      "import { createApp } from 'vue';\nimport App from './App.vue';\n\ncreateApp(App).mount('#app');",
    numberedSource:
      "1 | import { createApp } from 'vue';\n2 | import App from './App.vue';\n3 | \n4 | createApp(App).mount('#app');"
  },
  {
    type: 'vue',
    fileName: 'App.vue',
    source:
      '<script setup lang="ts">\nimport ExampleView from \'./ExampleView.vue\';\n</script>\n\n<template>\n  <ExampleView />\n</template>',
    numberedSource:
      '1 | <script setup lang="ts">\n2 | import ExampleView from \'./ExampleView.vue\';\n3 | </script>\n4 | \n5 | <template>\n6 |   <ExampleView />\n7 | </template>'
  },
  {
    type: 'typescript',
    fileName: 'employee.cell.ts',
    source:
      "import { FeatureCell, Vault } from '@sdux-vault/vue';\nimport { Employee } from './employee.model';\n\nVault({\n  logLevel: 'off'\n});\n\nexport const employeeCell = FeatureCell<Employee[]>({\n  key: 'employees',\n  initialState: []\n});\n\nemployeeCell\n  .filters([\n    (examples: Employee[]) =>\n      examples.filter((example) => example.id % 2 !== 0)\n  ])\n  .reducers([\n    (examples: Employee[]) => {\n      examples.sort((left, right) => left.name.localeCompare(right.name));\n      return examples;\n    }\n  ])\n  .initialize();\n\nexport function replaceEmployees(employees: Employee[]): void {\n  employeeCell.replaceState({\n    value: employees\n  });\n}\n\nexport function replaceEmployeesAsync(): void {\n  employeeCell.replaceState({\n    value: () => fetch('/api/employees').then((response) => response.json())\n  });\n}\n\nexport function resetEmployees(): void {\n  employeeCell.reset();\n}",
    numberedSource:
      " 1 | import { FeatureCell, Vault } from '@sdux-vault/vue';\n 2 | import { Employee } from './employee.model';\n 3 | \n 4 | Vault({\n 5 |   logLevel: 'off'\n 6 | });\n 7 | \n 8 | export const employeeCell = FeatureCell<Employee[]>({\n 9 |   key: 'employees',\n10 |   initialState: []\n11 | });\n12 | \n13 | employeeCell\n14 |   .filters([\n15 |     (examples: Employee[]) =>\n16 |       examples.filter((example) => example.id % 2 !== 0)\n17 |   ])\n18 |   .reducers([\n19 |     (examples: Employee[]) => {\n20 |       examples.sort((left, right) => left.name.localeCompare(right.name));\n21 |       return examples;\n22 |     }\n23 |   ])\n24 |   .initialize();\n25 | \n26 | export function replaceEmployees(employees: Employee[]): void {\n27 |   employeeCell.replaceState({\n28 |     value: employees\n29 |   });\n30 | }\n31 | \n32 | export function replaceEmployeesAsync(): void {\n33 |   employeeCell.replaceState({\n34 |     value: () => fetch('/api/employees').then((response) => response.json())\n35 |   });\n36 | }\n37 | \n38 | export function resetEmployees(): void {\n39 |   employeeCell.reset();\n40 | }"
  },
  {
    type: 'vue',
    fileName: 'ExampleView.vue',
    source:
      '<script setup lang="ts">\nimport {\n  employeeCell,\n  replaceEmployees,\n  replaceEmployeesAsync,\n  resetEmployees\n} from \'./employee.cell\';\nimport { Employee } from \'./employee.model\';\n\nconst sample: Employee[] = [\n  { id: 11, name: \'Luke\' },\n  { id: 38, name: \'Leia\' },\n  { id: 9, name: \'Han\' }\n];\n\nconst snapshot = employeeCell.useReactiveState();\n\nfunction loadSample(): void {\n  replaceEmployees(sample);\n}\n\nfunction loadSampleAsync(): void {\n  replaceEmployeesAsync();\n}\n\nfunction resetState(): void {\n  resetEmployees();\n}\n</script>\n\n<template>\n  <div>\n    <div>\n      <div v-if="snapshot.isLoading">Loading...</div>\n      <div v-else-if="snapshot.error" v-text="String(snapshot.error)" />\n      <textarea v-else readonly :value="JSON.stringify(snapshot.value ?? [], null, 2)" />\n    </div>\n\n    <div>\n      <button type="button" @click="loadSample">Load Sample State</button>\n\n      <button type="button" @click="loadSampleAsync">Load Async State</button>\n\n      <button type="button" @click="resetState">Reset State</button>\n    </div>\n  </div>\n</template>',
    numberedSource:
      ' 1 | <script setup lang="ts">\n 2 | import {\n 3 |   employeeCell,\n 4 |   replaceEmployees,\n 5 |   replaceEmployeesAsync,\n 6 |   resetEmployees\n 7 | } from \'./employee.cell\';\n 8 | import { Employee } from \'./employee.model\';\n 9 | \n10 | const sample: Employee[] = [\n11 |   { id: 11, name: \'Luke\' },\n12 |   { id: 38, name: \'Leia\' },\n13 |   { id: 9, name: \'Han\' }\n14 | ];\n15 | \n16 | const snapshot = employeeCell.useReactiveState();\n17 | \n18 | function loadSample(): void {\n19 |   replaceEmployees(sample);\n20 | }\n21 | \n22 | function loadSampleAsync(): void {\n23 |   replaceEmployeesAsync();\n24 | }\n25 | \n26 | function resetState(): void {\n27 |   resetEmployees();\n28 | }\n29 | </script>\n30 | \n31 | <template>\n32 |   <div>\n33 |     <div>\n34 |       <div v-if="snapshot.isLoading">Loading...</div>\n35 |       <div v-else-if="snapshot.error" v-text="String(snapshot.error)" />\n36 |       <textarea v-else readonly :value="JSON.stringify(snapshot.value ?? [], null, 2)" />\n37 |     </div>\n38 | \n39 |     <div>\n40 |       <button type="button" @click="loadSample">Load Sample State</button>\n41 | \n42 |       <button type="button" @click="loadSampleAsync">Load Async State</button>\n43 | \n44 |       <button type="button" @click="resetState">Reset State</button>\n45 |     </div>\n46 |   </div>\n47 | </template>'
  },
  {
    type: 'typescript',
    fileName: 'employee.model.ts',
    source: 'export interface Employee {\n  id: number;\n  name: string;\n}',
    numberedSource:
      '1 | export interface Employee {\n2 |   id: number;\n3 |   name: string;\n4 | }'
  }
] as const satisfies ReadonlyArray<{
  readonly type:
    'typescript' | 'html' | 'svelte' | 'vue' | 'scss' | 'json' | 'markdown';
  readonly fileName: string;
  readonly source: string;
  readonly numberedSource: string;
}>;
